/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.Topology.Constructions

@[expose] public section

namespace LeanCategories.Topology

open Set TopologicalSpace

universe u v

/-- A box in an indexed product: every coordinate is restricted to an open set. -/
def IsOpenBox {ι : Type u} (X : ι → Type v) [∀ i, TopologicalSpace (X i)]
    (s : Set (∀ i, X i)) : Prop :=
  ∃ U : ∀ i, Set (X i), (∀ i, IsOpen (U i)) ∧ s = Set.pi Set.univ U

/-- The box topology on an arbitrary indexed product, generated by all open boxes.
This is Munkres FC02-C02-U096/U097. -/
@[instance_reducible]
def boxTopology {ι : Type u} (X : ι → Type v) [∀ i, TopologicalSpace (X i)] :
    TopologicalSpace (∀ i, X i) :=
  generateFrom {s | IsOpenBox X s}

end LeanCategories.Topology
