/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.Analysis.SpecialFunctions.Complex.Circle
public import Mathlib.Topology.Constructions

@[expose] public section

noncomputable section

namespace LeanCategories.Topology

open Metric

/-!
# The n-fold dunce cap

Definition-level realization of Munkres FC02-C11-U062.  The quotient relation is generated by
rotation through `2π/n` on the boundary of the closed unit disk.  Compactness, Hausdorffness, and
the fundamental-group computation belong to Sweep IV.
-/

/-- The closed complex unit disk. -/
abbrev ClosedUnitDisk := closedBall (0 : ℂ) 1

/-- Rotation through angle `2π/n`. -/
noncomputable def dunceCapBoundaryRotation (n : ℕ) : ℂ :=
  Complex.exp (((2 * Real.pi / n : ℝ) : ℂ) * Complex.I)

/-- Generator of the boundary identifications defining the `n`-fold dunce cap. -/
inductive DunceCapGenerator (n : ℕ) : ClosedUnitDisk → ClosedUnitDisk → Prop
  | rotate (x y : ClosedUnitDisk)
      (hx : ‖(x : ℂ)‖ = 1)
      (hy : (y : ℂ) = dunceCapBoundaryRotation n * (x : ℂ)) :
      DunceCapGenerator n x y

/-- Equivalence relation generated by the order-`n` boundary rotation. -/
def dunceCapSetoid (n : ℕ) : Setoid ClosedUnitDisk :=
  Relation.EqvGen.setoid (DunceCapGenerator n)

/-- The `n`-fold dunce cap: the closed disk with boundary points identified by rotation through
`2π/n` (FC02-C11-U062).  The source assumes `1 < n`; keeping `n` as a parameter makes the
construction reusable, while source theorems impose that hypothesis where needed. -/
abbrev DunceCap (n : ℕ) := Quotient (dunceCapSetoid n)

end LeanCategories.Topology
