/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.Geometry.Manifold.Instances.Sphere
public import Mathlib.Topology.Constructions

@[expose] public section

/-!
# The real projective plane as an antipodal quotient

This realizes Munkres FC02-C09-U079: `P²` is the quotient of the unit two-sphere by
identifying each point with its antipode.
-/

namespace LeanCategories.Topology

open Metric

/-- The unit two-sphere in `ℝ³`. -/
abbrev Sphere2 := sphere (0 : EuclideanSpace ℝ (Fin 3)) 1

/-- The antipodal involution of the two-sphere. -/
def sphere2Antipodal (x : Sphere2) : Sphere2 :=
  ⟨-x.1, by
    rw [mem_sphere, dist_zero_right, norm_neg]
    simpa only [mem_sphere, dist_zero_right] using x.2⟩

@[simp]
theorem sphere2Antipodal_involutive (x : Sphere2) :
    sphere2Antipodal (sphere2Antipodal x) = x := by
  apply Subtype.ext
  simp [sphere2Antipodal]

/-- Two points of `S²` represent the same projective point exactly when they are equal or
antipodal. -/
def sphere2AntipodalRel (x y : Sphere2) : Prop :=
  y = x ∨ y = sphere2Antipodal x

theorem sphere2AntipodalRel_refl (x : Sphere2) : sphere2AntipodalRel x x :=
  Or.inl rfl

theorem sphere2AntipodalRel_symm {x y : Sphere2} :
    sphere2AntipodalRel x y → sphere2AntipodalRel y x := by
  intro h
  rcases h with rfl | h
  · exact Or.inl rfl
  · right
    rw [h]
    simp

theorem sphere2AntipodalRel_trans {x y z : Sphere2} :
    sphere2AntipodalRel x y → sphere2AntipodalRel y z → sphere2AntipodalRel x z := by
  intro hxy hyz
  rcases hxy with rfl | hxy
  · exact hyz
  · rcases hyz with rfl | hyz
    · exact Or.inr hxy
    · left
      rw [hyz, hxy]
      simp

/-- The setoid generated by the antipodal identification on `S²`. -/
def sphere2AntipodalSetoid : Setoid Sphere2 where
  r := sphere2AntipodalRel
  iseqv := ⟨sphere2AntipodalRel_refl, @sphere2AntipodalRel_symm,
    @sphere2AntipodalRel_trans⟩

/-- The real projective plane `P² = S²/(x ∼ -x)` (FC02-C09-U079). -/
abbrev RealProjectivePlane := Quotient sphere2AntipodalSetoid

end LeanCategories.Topology
