/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.Topology.MetricSpace.Basic

@[expose] public section

namespace LeanCategories.Topology

open Set

universe u

/-- The standard bounded distance associated to a metric: `min (d x y) 1`.
This is Munkres FC02-C02-U118. -/
def boundedDist (X : Type u) [MetricSpace X] (x y : X) : ℝ :=
  min (dist x y) 1

lemma boundedDist_self (X : Type u) [MetricSpace X] (x : X) : boundedDist X x x = 0 := by
  simp [boundedDist]

lemma boundedDist_comm (X : Type u) [MetricSpace X] (x y : X) :
    boundedDist X x y = boundedDist X y x := by
  simp [boundedDist, dist_comm]

lemma boundedDist_triangle (X : Type u) [MetricSpace X] (x y z : X) :
    boundedDist X x z ≤ boundedDist X x y + boundedDist X y z := by
  unfold boundedDist
  by_cases hxy : 1 ≤ dist x y
  · rw [min_eq_right hxy]
    have hz : 0 ≤ min (dist y z) 1 := le_min (dist_nonneg) zero_le_one
    linarith [min_le_right (dist x z) 1]
  by_cases hyz : 1 ≤ dist y z
  · rw [min_eq_right hyz]
    have hxy0 : 0 ≤ min (dist x y) 1 := le_min (dist_nonneg) zero_le_one
    linarith [min_le_right (dist x z) 1]
  rw [min_eq_left (le_of_not_ge hxy), min_eq_left (le_of_not_ge hyz)]
  exact (min_le_left _ _).trans (dist_triangle _ _ _)

lemma boundedDist_eq_zero_iff (X : Type u) [MetricSpace X] (x y : X) :
    boundedDist X x y = 0 ↔ x = y := by
  constructor
  · intro h
    have hd : dist x y = 0 := by
      by_cases hle : dist x y ≤ 1
      · simpa [boundedDist, min_eq_left hle] using h
      · have hge : 1 ≤ dist x y := le_of_not_ge hle
        rw [boundedDist, min_eq_right hge] at h
        norm_num at h
    exact dist_eq_zero.mp hd
  · rintro rfl
    exact boundedDist_self X x

/-- The metric-space structure associated to the standard bounded metric. -/
@[instance_reducible]
noncomputable def boundedMetricSpace (X : Type u) [MetricSpace X] : MetricSpace X where
  dist := boundedDist X
  dist_self := boundedDist_self X
  dist_comm := boundedDist_comm X
  dist_triangle := boundedDist_triangle X
  eq_of_dist_eq_zero := (boundedDist_eq_zero_iff X _ _).mp

/-- The uniform-distance formula on an arbitrary power `ℝ^J`: the supremum of
coordinatewise standard bounded distances. This is the definition-level content
of Munkres FC02-C02-U124/U125. -/
noncomputable def uniformDist {J : Type u} (x y : J → ℝ) : ℝ :=
  sSup (Set.range fun j : J => min (dist (x j) (y j)) 1)

/-- The topology generated by open balls for Munkres' uniform-distance formula. -/
@[instance_reducible]
noncomputable def uniformTopology {J : Type u} : TopologicalSpace (J → ℝ) :=
  TopologicalSpace.generateFrom
    {s | ∃ x : J → ℝ, ∃ ε > 0, s = {y | uniformDist x y < ε}}

end LeanCategories.Topology
