/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import LeanCategories.AlgebraicGeometry.ProjectiveAlgebraicSet
public import Mathlib.RingTheory.GradedAlgebra.Homogeneous.Ideal
public import Mathlib.RingTheory.Ideal.Quotient.Basic

/-!
# Homogeneous ideals and projective coordinate rings

Hartshorne, *Algebraic Geometry* (1977), Chapter I, §2, pp. 8--13
(FC06-C01-U045).

For `Y ⊆ P^n_k`, `I(Y)` is the homogeneous ideal generated by homogeneous
polynomials vanishing on `Y`.  For a projective algebraic set, its homogeneous
coordinate ring is

`S(Y) = k[x₀,…,xₙ] / I(Y)`.
-/

@[expose] public noncomputable section

namespace LeanCategories.AlgebraicGeometry

universe u

variable (k : Type u) [Field k] [IsAlgClosed k]

/-- The underlying homogeneous polynomials vanishing on every point of `Y`. -/
def projectiveVanishingPolynomials {n : ℕ}
    (Y : Set (ProjectivePointSpace k n)) :
    Set (MvPolynomial (Fin (n + 1)) k) :=
  {p | ∃ f : ProjectiveHomogeneousPolynomial k n,
    f.polynomial = p ∧ ∀ P ∈ Y, f.VanishesAt k P}

/-- Hartshorne's homogeneous vanishing ideal `I(Y)`. -/
def projectiveVanishingIdeal {n : ℕ}
    (Y : Set (ProjectivePointSpace k n)) :
    Ideal (MvPolynomial (Fin (n + 1)) k) :=
  Ideal.span (projectiveVanishingPolynomials k Y)

attribute [local instance] MvPolynomial.gradedAlgebra

/-- The ideal `I(Y)` is homogeneous for the standard total-degree grading. -/
theorem projectiveVanishingIdeal_isHomogeneous {n : ℕ}
    (Y : Set (ProjectivePointSpace k n)) :
    (projectiveVanishingIdeal k Y).IsHomogeneous
      (MvPolynomial.homogeneousSubmodule (Fin (n + 1)) k) := by
  apply Ideal.homogeneous_span
  intro p hp
  rcases hp with ⟨f, rfl, -⟩
  exact ⟨f.degree, f.homogeneous⟩

/-- The homogeneous coordinate ring `S(Y)`. -/
abbrev projectiveCoordinateRing {n : ℕ}
    (Y : Set (ProjectivePointSpace k n)) :=
  MvPolynomial (Fin (n + 1)) k ⧸ projectiveVanishingIdeal k Y

/-- The homogeneous coordinate ring of a projective algebraic set. -/
abbrev ProjectiveAlgebraicSet.coordinateRing {n : ℕ}
    (Y : ProjectiveAlgebraicSet k n) :=
  projectiveCoordinateRing k Y.carrier

/-- The canonical quotient map to the homogeneous coordinate ring. -/
def ProjectiveAlgebraicSet.coordinateRingQuotient {n : ℕ}
    (Y : ProjectiveAlgebraicSet k n) :
    MvPolynomial (Fin (n + 1)) k →+* Y.coordinateRing :=
  Ideal.Quotient.mk (projectiveVanishingIdeal k Y.carrier)

end LeanCategories.AlgebraicGeometry
