/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.Algebra.Category.ModuleCat.Products
public import Mathlib.Algebra.Category.ModuleCat.Monoidal.Basic
public import Mathlib.Algebra.Homology.ShortComplex.ModuleCat
public import Mathlib.LinearAlgebra.Charpoly.Basic
public import Mathlib.LinearAlgebra.Dual.Defs
public import Mathlib.LinearAlgebra.Eigenspace.Basic
public import Mathlib.LinearAlgebra.Matrix.Charpoly.Basic
public import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
public import Mathlib.LinearAlgebra.Matrix.Trace
public import LeanCategories.Modules.Mathlib

/-!
# Basic module and linear-algebra routes

This file exposes the standard Chapter 10--12 objects through Mathlib.
It adds no parallel module, tensor-product, exactness, or canonical-form theory.
-/

@[expose] public section

open CategoryTheory

namespace LeanCategories.Modules

universe u v w

section ModuleTheory

variable (R : Type u) [Ring R]

/** A submodule of an `R`-module. */
abbrev Submodule (M : Type v) [AddCommMonoid M] [Module R M] :=
  _root_.Submodule R M

/** The module quotient by a submodule. */
abbrev QuotientModule (M : Type v) [AddCommMonoid M] [Module R M]
    (N : Submodule R M) := M ⧸ N

/** The submodule generated by a set. */
abbrev GeneratedSubmodule (M : Type v) [AddCommMonoid M] [Module R M]
    (s : Set M) : Submodule R M :=
  _root_.Submodule.span R s

/** The direct sum of a family of modules. */
abbrev DirectSum (ι : Type v) (M : ι → Type w)
    [∀ i, AddCommMonoid (M i)] [∀ i, Module R (M i)] :=
  ⨁ i, M i

/** The category of exact three-term complexes of `R`-modules. */
abbrev ExactModuleSequences : Type (max u v) :=
  ObjectProperty.FullSubcategory
    (C := ShortComplex (ModuleCat.{v} R)) (fun S => S.Exact)

/** The category of short exact sequences of `R`-modules. */
abbrev ShortExactModuleSequences : Type (max u v) :=
  ObjectProperty.FullSubcategory
    (C := ShortComplex (ModuleCat.{v} R)) (fun S => S.ShortExact)

end ModuleTheory

section TensorAndProducts

variable (R : Type u) [CommRing R]

/** The tensor product module, using Mathlib's standard construction. */
abbrev TensorProduct (M N : Type v) [AddCommMonoid M] [AddCommMonoid N]
    [Module R M] [Module R N] :=
  _root_.TensorProduct R M N

/** The tensor product object in the monoidal category `ModuleCat R`. */
abbrev TensorProductModuleCat (M N : ModuleCat.{v} R) : ModuleCat.{v} R :=
  ModuleCat.of R (_root_.TensorProduct R M N)

/** The canonical tensor product bifunctor on `ModuleCat R`. */
abbrev TensorProductFunctor : ModuleCat.{v} R ⥤ ModuleCat.{v} R ⥤ ModuleCat.{v} R :=
  ModuleCat.tensorObj

/** The product module of a family. */
abbrev ProductModule (ι : Type v) (M : ι → Type w)
    [∀ i, AddCommMonoid (M i)] [∀ i, Module R (M i)] :=
  ∀ i, M i

end TensorAndProducts

section LinearAlgebra

variable (R : Type u) [CommRing R]

/** The algebraic dual module. */
abbrev AlgebraicDual (M : Type v) [AddCommMonoid M] [Module R M] :=
  Module.Dual R M

/** A basis of an `R`-module. */
abbrev ModuleBasis (ι : Type v) (M : Type w)
    [AddCommMonoid M] [Module R M] :=
  Module.Basis ι R M

/** The determinant of a square matrix. */
abbrev MatrixDeterminant {n : Type v} [Fintype n] [DecidableEq n]
    (A : Matrix n n R) : R :=
  Matrix.det A

/** The trace of a square matrix. */
abbrev MatrixTrace {n : Type v} [Fintype n] (A : Matrix n n R) : R :=
  Matrix.trace A

/** The characteristic polynomial of a square matrix. */
abbrev MatrixCharacteristicPolynomial {n : Type v} [Fintype n] [DecidableEq n]
    (A : Matrix n n R) : Polynomial R :=
  Matrix.charpoly A

/** The characteristic polynomial of a finite free endomorphism. */
abbrev LinearMapCharacteristicPolynomial (M : Type v)
    [AddCommGroup M] [Module R M] [Module.Free R M] [Module.Finite R M]
    (f : M →ₗ[R] M) : Polynomial R :=
  f.charpoly

/** The eigenspace of an endomorphism. */
abbrev Eigenspace (M : Type v) [AddCommGroup M] [Module R M]
    (f : Module.End R M) (μ : R) : Submodule R M :=
  f.eigenspace μ

/** The generalized eigenspace of an endomorphism. */
abbrev GeneralizedEigenspace (M : Type v) [AddCommGroup M] [Module R M]
    (f : Module.End R M) (μ : R) (k : ℕ) : Submodule R M :=
  f.genEigenspace μ k

end LinearAlgebra

end LeanCategories.Modules
