/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import LeanCategories.Homological.FourTermCrossedExtension
public import Mathlib.Algebra.Category.Grp.Basic

/-!
# Equivalence of crossed-module extensions

Weibel, *An Introduction to Homological Algebra* (1994), §6.6, pp. 182--188
(FC05-C06-U078).

Crossed modules with fixed kernel `A` and cokernel `G` are compared by
commutative morphisms inducing the identity on those fixed ends.  Weibel's
equivalence relation is generated by these elementary comparisons.  The
associated `H³(G;A)` class and its invariance are theorem-layer statements and
are not asserted here.
-/

@[expose] public section

namespace LeanCategories.Homological

open CategoryTheory

universe u

/-- A four-term crossed extension with fixed end groups, bundling the two
middle groups so different presentations inhabit one type. -/
structure BundledCrossedExtension (A G : GrpCat.{u}) where
  /-- The degree-two middle group. -/
  N : GrpCat.{u}
  /-- The degree-one middle group. -/
  E : GrpCat.{u}
  /-- The exact crossed-module data. -/
  data : FourTermCrossedExtension A N E G

namespace BundledCrossedExtension

variable {A G : GrpCat.{u}}

/-- An elementary comparison of crossed-module extensions fixing `A` and `G`.
It is a morphism of the middle crossed modules and its outer squares are the
identity maps on the fixed kernel and cokernel. -/
structure Hom (X Y : BundledCrossedExtension A G) where
  /-- Map on the `N` terms. -/
  left : X.N →* Y.N
  /-- Map on the `E` terms. -/
  right : X.E →* Y.E
  /-- Identity on the fixed kernel `A`. -/
  inl_comm : left.comp X.data.inl = Y.data.inl
  /-- Compatibility with the crossed-module boundary. -/
  boundary_comm : Y.data.boundary.comp left = right.comp X.data.boundary
  /-- Identity on the fixed cokernel `G`. -/
  projection_comm : Y.data.projection.comp right = X.data.projection
  /-- Compatibility with the crossed-module actions. -/
  action_comm : ∀ e n,
    left (X.data.act e n) = Y.data.act (right e) (left n)

/-- Two presentations are elementarily related if there is a comparison in
either direction. -/
def ElementaryEquivalent (X Y : BundledCrossedExtension A G) : Prop :=
  Nonempty (Hom X Y) ∨ Nonempty (Hom Y X)

/-- Weibel's equivalence relation generated by elementary equivalences of
crossed modules with the same kernel and cokernel. -/
def Equivalent : BundledCrossedExtension A G → BundledCrossedExtension A G → Prop :=
  Relation.EqvGen ElementaryEquivalent

end BundledCrossedExtension

end LeanCategories.Homological
