/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.GroupTheory.FreeGroup.Basic

/-!
# Free presentations of groups

Weibel, *An Introduction to Homological Algebra* (1994), §6.8,
"Presentations 6.8.7", p. 198 (FC05-C06-U104).

Weibel begins the calculation by identifying a presentation of `G` by
generators and relations with a short exact sequence

`1 ⟶ R ⟶ F ⟶ G ⟶ 1`,

where `F` is the free group on the chosen generators and `R` is the normal
subgroup generated by the relations.  Equivalently, one may specify a
surjective homomorphism from the free group and take `R` to be its kernel.

Only that presentation datum belongs to Sweep III.  The freeness of `R`, the
Lyndon--Hochschild--Serre calculation, the low-degree sequence, and Hopf's
formula are result-level statements and are not asserted here.
-/

@[expose] public noncomputable section

namespace LeanCategories.Homological

universe u v

/-- A presentation of a group `G` by generators and relations, represented by
a surjection from the free group on the generators.  The relation subgroup is
the kernel of this surjection, exactly as in Weibel 6.8.7. -/
structure FreeGroupPresentation (G : Type u) [Group G] where
  /-- The chosen set of generators. -/
  Generators : Type v
  /-- The quotient map from the free group on the generators to `G`. -/
  quotientMap : FreeGroup Generators →* G
  /-- The chosen generators generate `G`. -/
  quotientMap_surjective : Function.Surjective quotientMap

namespace FreeGroupPresentation

variable {G : Type u} [Group G] (P : FreeGroupPresentation.{u, v} G)

/-- The relation subgroup `R` of a free presentation. -/
def relations : Subgroup (FreeGroup P.Generators) :=
  P.quotientMap.ker

/-- The inclusion `R ⟶ F` in the short exact sequence attached to the
presentation. -/
def relationsInclusion : P.relations →* FreeGroup P.Generators :=
  P.relations.subtype

/-- The quotient map kills every relation. -/
lemma quotientMap_relationsInclusion :
    P.quotientMap.comp P.relationsInclusion = 1 := by
  ext x
  exact x.2

end FreeGroupPresentation

end LeanCategories.Homological
