/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import LeanCategories.Homological.CyclicOperators
public import LeanCategories.Homological.HochschildComplex
public import Mathlib.RingTheory.GradedAlgebra.Basic

/-!
# Weight grading on Hochschild and cyclic chains

Weibel, *An Introduction to Homological Algebra* (1994), §9.9, pp. 354--361
(FC05-C09-U137).

For an `ℕ`-graded `k`-algebra `R`, a homogeneous Hochschild tensor
`r₀ ⊗ ... ⊗ rₙ` has weight `|r₀| + ... + |rₙ|`.  This file records the
degreewise weight submodules generated by homogeneous pure tensors.  The
assertions that the Hochschild/cyclic operators preserve these submodules and
that homology decomposes into weight summands are theorem-layer content.
-/

@[expose] public section

namespace LeanCategories.Homological

open scoped BigOperators TensorProduct

universe u v

variable (k : Type u) [CommRing k]
variable (R : Type v) [Ring R] [Algebra k R]
variable (𝒜 : ℕ → Submodule k R) [GradedAlgebra 𝒜]

/-- A homogeneous pure Hochschild tensor together with the degrees of all of
its factors. -/
structure HomogeneousHochschildTensor (n : ℕ) where
  /-- Degree of the distinguished first factor. -/
  degree0 : ℕ
  /-- Degrees of the remaining `n` factors. -/
  degrees : Fin n → ℕ
  /-- The distinguished first homogeneous factor. -/
  r0 : 𝒜 degree0
  /-- The remaining homogeneous factors. -/
  r : ∀ i : Fin n, 𝒜 (degrees i)

namespace HomogeneousHochschildTensor

/-- Weibel's weight `|r₀|+⋯+|rₙ|` of a homogeneous Hochschild tensor. -/
def weight {n : ℕ} (x : HomogeneousHochschildTensor k R 𝒜 n) : ℕ :=
  x.degree0 + ∑ i, x.degrees i

/-- The underlying pure Hochschild chain represented by homogeneous factors. -/
def toChain {n : ℕ} (x : HomogeneousHochschildTensor k R 𝒜 n) :
    HochschildChainDegree (k := k) (R := R) (M := R) n :=
  hochschildChainPure (k := k) (R := R) (M := R) (x.r0 : R)
    (fun i => (x.r i : R))

end HomogeneousHochschildTensor

/-- Pure homogeneous degree-`n` Hochschild chains of weight `w`. -/
def hochschildWeightGenerators (n w : ℕ) :
    Set (HochschildChainDegree (k := k) (R := R) (M := R) n) :=
  {z | ∃ x : HomogeneousHochschildTensor k R 𝒜 n,
    x.weight = w ∧ x.toChain = z}

/-- The weight-`w` submodule in degree `n` of the Hochschild chain module. -/
def hochschildWeightSubmodule (n w : ℕ) :
    Submodule k (HochschildChainDegree (k := k) (R := R) (M := R) n) :=
  Submodule.span k (hochschildWeightGenerators k R 𝒜 n w)

/-- The degree-`n` Hochschild weight grading, indexed by total weight. -/
def hochschildWeightGrading (n : ℕ) :
    ℕ → Submodule k (HochschildChainDegree (k := k) (R := R) (M := R) n) :=
  hochschildWeightSubmodule k R 𝒜 n

/-- The cyclic complex uses the same underlying degreewise modules and hence
the same weight submodules as the Hochschild complex. -/
def cyclicWeightGrading (n : ℕ) :
    ℕ → Submodule k (HochschildChainDegree (k := k) (R := R) (M := R) n) :=
  hochschildWeightSubmodule k R 𝒜 n

end LeanCategories.Homological
