/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import LeanCategories.Homological.RelativeCyclicHomology

/-!
# The I-adic filtration of the cyclic module of an algebra

Weibel, *An Introduction to Homological Algebra* (1994), §9.9,
pp. 358--359 (FC05-C09-U146).

For `Z_p(R)=R^{⊗(p+1)}`, Weibel lets `F_p^i` be generated by tensor products

`I^{i₀} ⊗ ⋯ ⊗ I^{iₚ}`, with `i₀+⋯+iₚ=i`.

The structure maps of the cyclic module preserve these submodules, producing
a decreasing filtration by cyclic submodules; moreover `F_*^1=Z(R,I)`.
This file records the generators exactly and packages those preservation and
kernel-identification clauses.  Nilpotent-invariance consequences are later
result-level units.
-/

@[expose] public noncomputable section

namespace LeanCategories.Homological

open CategoryTheory Opposite Simplicial
open scoped TensorProduct

universe u v

variable (k : Type u) [CommRing k]
variable (R : Type v) [Ring R] [Algebra k R]
variable (I : Ideal R) [I.IsTwoSided]
variable [Algebra k (R ⧸ I)]

/-- A pure tensor generator of `F_p^i`: each factor is supplied together with
an exponent `i_j` and a proof that it lies in `I^{i_j}`, while the exponents
sum to `i`. -/
structure IAdicHochschildGenerator (p i : ℕ) where
  /-- The exponent attached to each of the `p+1` tensor factors. -/
  exponent : Fin (p + 1) → ℕ
  /-- The exponents have total `i`. -/
  exponent_sum : ∑ j, exponent j = i
  /-- The tensor factors. -/
  factor : Fin (p + 1) → R
  /-- The `j`th factor lies in `I^(i_j)`. -/
  factor_mem : ∀ j, factor j ∈ I ^ exponent j

/-- The pure Hochschild tensor represented by an `I`-adic generator. -/
def iAdicHochschildPure {p i : ℕ}
    (g : IAdicHochschildGenerator R I p i) :
    HochschildChainDegree (k := k) (R := R) (M := R) p :=
  hochschildChainPure (k := k) (R := R) (M := R)
    (g.factor 0) (fun j => g.factor j.succ)

/-- Weibel's degree-`p`, filtration-`i` submodule `F_p^i`. -/
def iAdicHochschildFiltration (p i : ℕ) :
    Submodule k (HochschildChainDegree (k := k) (R := R) (M := R) p) :=
  Submodule.span k
    (Set.range (iAdicHochschildPure (k := k) (R := R) (I := I) (p := p) (i := i)))

/-- Definition-layer realization that the `F_p^i` form Weibel's decreasing
filtration by cyclic submodules of `Z(R)` and that `F_*^1` is the relative
cyclic module `Z(R,I)`. -/
structure IAdicCyclicFiltrationRealization
    (D : RelativeCyclicIdealRealization k R I) where
  /-- Face maps preserve every filtration level. -/
  face_preserves : ∀ (p i : ℕ) (j : Fin (p + 2))
      (x : HochschildChainDegree (k := k) (R := R) (M := R) (p + 1)),
    x ∈ iAdicHochschildFiltration k R I (p + 1) i →
      (D.sourceDegreeIso p).hom
          (D.ZR.obj.δ j ((D.sourceDegreeIso (p + 1)).inv x)) ∈
        iAdicHochschildFiltration k R I p i
  /-- Degeneracy maps preserve every filtration level. -/
  degeneracy_preserves : ∀ (p i : ℕ) (j : Fin (p + 1))
      (x : HochschildChainDegree (k := k) (R := R) (M := R) p),
    x ∈ iAdicHochschildFiltration k R I p i →
      (D.sourceDegreeIso (p + 1)).hom
          (D.ZR.obj.σ j ((D.sourceDegreeIso p).inv x)) ∈
        iAdicHochschildFiltration k R I (p + 1) i
  /-- The cyclic operator preserves every filtration level. -/
  cyclic_preserves : ∀ (p i : ℕ)
      (x : HochschildChainDegree (k := k) (R := R) (M := R) p),
    x ∈ iAdicHochschildFiltration k R I p i →
      (D.sourceDegreeIso p).hom
          ((D.ZR.t p).hom ((D.sourceDegreeIso p).inv x)) ∈
        iAdicHochschildFiltration k R I p i
  /-- The filtration is decreasing in `i`. -/
  decreasing : ∀ (p i : ℕ),
    iAdicHochschildFiltration k R I p (i + 1) ≤
      iAdicHochschildFiltration k R I p i
  /-- Degreewise identification `F_p^1 ≅ Z_p(R,I)`. -/
  relativeDegreeIso : ∀ p : ℕ,
    D.kernel.obj.obj.obj (op ⦋p⦌) ≅
      ModuleCat.of k (iAdicHochschildFiltration k R I p 1)
  /-- Under that identification, the relative cyclic-module inclusion is the
  ordinary submodule inclusion `F_p^1 ↪ Z_p(R)`. -/
  relative_inclusion : ∀ (p : ℕ) (x : D.kernel.obj.obj.obj (op ⦋p⦌)),
    (((relativeDegreeIso p).hom x : iAdicHochschildFiltration k R I p 1) :
        HochschildChainDegree (k := k) (R := R) (M := R) p) =
      (D.sourceDegreeIso p).hom (D.kernel.ι.hom.app (op ⦋p⦌) x)

end LeanCategories.Homological
