/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.Algebra.Lie.Nilpotent
public import Mathlib.Algebra.Lie.Quotient

/-!
# Lie abelianization and the lower central series

Weibel, *An Introduction to Homological Algebra* (1994), §7.1, pp. 216--218
(FC05-C07-U004 and FC05-C07-U009).

Mathlib already owns the derived ideal, quotient Lie algebra, lower central series,
and nilpotence predicate.  This file only fixes Weibel's notation and one-based
indexing: `g¹=g`, `g²=[g,g]`, and `gⁿ=[g,gⁿ⁻¹]`.
-/

@[expose] public section

namespace LeanCategories.Homological

universe u v

variable (R : Type u) (L : Type v) [CommRing R] [LieRing L] [LieAlgebra R L]

/-- The commutator ideal `[L,L]`, i.e. the ideal generated by all brackets. -/
abbrev lieCommutatorIdeal : LieIdeal R L :=
  LieAlgebra.derivedSeries R L 1

/-- The Lie algebra abelianization `Lᵃᵇ = L/[L,L]`. -/
abbrev lieAbelianization :=
  L ⧸ lieCommutatorIdeal R L

/-- Weibel's one-based lower central series: `L¹=L` and
`Lⁿ⁺¹=[L,Lⁿ]`.

Mathlib's `LieModule.lowerCentralSeries` is zero-based, so degree `n+1`
here is Mathlib degree `n`. -/
def weibelLowerCentralSeries : ℕ → LieSubmodule R L L
  | 0 => ⊤
  | n + 1 => LieModule.lowerCentralSeries R L L n

@[simp]
theorem weibelLowerCentralSeries_one :
    weibelLowerCentralSeries R L 1 = ⊤ :=
  rfl

@[simp]
theorem weibelLowerCentralSeries_two :
    weibelLowerCentralSeries R L 2 = lieCommutatorIdeal R L := by
  rw [weibelLowerCentralSeries, LieModule.lowerCentralSeries_succ,
    LieModule.lowerCentralSeries_zero]
  change ⁅(⊤ : LieIdeal R L), (⊤ : LieSubmodule R L L)⁆ =
    LieAlgebra.derivedSeries R L 1
  rw [LieAlgebra.derivedSeries_def, LieAlgebra.derivedSeriesOfIdeal_succ,
    LieAlgebra.derivedSeriesOfIdeal_zero]

/-- Weibel's nilpotence predicate: the one-based lower central series reaches zero. -/
def IsNilpotentLieAlgebra : Prop :=
  ∃ n : ℕ, weibelLowerCentralSeries R L n = ⊥

end LeanCategories.Homological
