/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.Algebra.Category.ModuleCat.Basic
public import Mathlib.Algebra.Lie.Abelian
public import Mathlib.Algebra.Lie.Nilpotent
public import Mathlib.CategoryTheory.Preadditive.AdditiveFunctor

/-!
# The category of modules over a Lie algebra

Weibel, *An Introduction to Homological Algebra*, §7.2, pp. 219--222
(FC05-C07-U015, FC05-C07-U016).

Mathlib already owns Lie-module structures, their equivariant linear maps, the maximal trivial
submodule, the trivial Lie-module construction, and the lower central series.  This file only
bundles those owners into the fixed-Lie-algebra category needed by Weibel and names the invariant
and coinvariant constructions.  Exactness, adjunctions, and the assertion that this preadditive
category has finite biproducts are result-level statements and are not included in the Definitions
sweep.
-/

@[expose] public section

open CategoryTheory

namespace LeanCategories.Homological

universe u v w

variable (R : Type u) (L : Type v) [CommRing R] [LieRing L] [LieAlgebra R L]

/-- A bundled left module over the fixed Lie algebra `L` over `R`.

Morphisms are supplied below by Mathlib's `LieModuleHom`, i.e. `R`-linear maps commuting with the
`L`-action.

Source: Weibel, §7.2, pp. 219--222 (FC05-C07-U015). -/
structure LieModuleCat where
  /-- The carrier of the Lie module. -/
  carrier : Type w
  [addCommGroup : AddCommGroup carrier]
  [module : Module R carrier]
  [lieRingModule : LieRingModule L carrier]
  [lieModule : LieModule R L carrier]

namespace LieModuleCat

attribute [instance] addCommGroup module lieRingModule lieModule

instance : CoeSort (LieModuleCat.{u, v, w} R L) (Type w) := ⟨carrier⟩

/-- Bundle an existing Lie module as an object of `LieModuleCat`. -/
abbrev of (M : Type w) [AddCommGroup M] [Module R M] [LieRingModule L M] [LieModule R L M] :
    LieModuleCat.{u, v, w} R L :=
  ⟨M⟩

/-- The category structure on left `L`-modules, with Mathlib's `LieModuleHom` as morphisms.

Source: Weibel, §7.2, pp. 219--222 (FC05-C07-U015). -/
instance : Category (LieModuleCat.{u, v, w} R L) where
  Hom M N := M →ₗ⁅R,L⁆ N
  id M := LieModuleHom.id
  comp f g := g.comp f
  assoc _ _ _ := by ext; rfl
  id_comp _ := by ext; rfl
  comp_id _ := by ext; rfl

/-- The additive-group structure on Lie-module morphisms, inherited from `LieModuleHom`. -/
instance (M N : LieModuleCat.{u, v, w} R L) : AddCommGroup (M ⟶ N) := by
  change AddCommGroup (M →ₗ⁅R,L⁆ N)
  infer_instance

theorem lieModuleHom_comp_add {M N P : LieModuleCat.{u, v, w} R L}
    (f : M →ₗ⁅R,L⁆ N) (g h : N →ₗ⁅R,L⁆ P) :
    (g + h).comp f = g.comp f + h.comp f := by
  apply LieModuleHom.ext
  intro m
  rfl

theorem lieModuleHom_add_comp {M N P : LieModuleCat.{u, v, w} R L}
    (f g : M →ₗ⁅R,L⁆ N) (h : N →ₗ⁅R,L⁆ P) :
    h.comp (f + g) = h.comp f + h.comp g := by
  apply LieModuleHom.ext
  intro m
  exact map_add h (f m) (g m)

/-- Lie-module hom sets have their source additive-group structure, and composition is bilinear. -/
instance : Preadditive (LieModuleCat.{u, v, w} R L) where
  comp_add _ _ _ f g h := by
    change (g + h).comp f = g.comp f + h.comp f
    exact lieModuleHom_comp_add R L f g h
  add_comp _ _ _ f g h := by
    change h.comp (f + g) = h.comp f + h.comp g
    exact lieModuleHom_add_comp R L f g h

/-- The trivial `L`-module associated to an `R`-module.

This is the object part of Weibel's trivial-module functor.  Mathlib's `TrivialLieModule` owns the
zero action.

Source: Weibel, §7.2, pp. 219--222 (FC05-C07-U016). -/
abbrev trivialObject (M : ModuleCat.{w} R) : LieModuleCat.{u, v, w} R L :=
  of R L (TrivialLieModule R L M)

/-- The trivial-module functor `R-mod ⥤ L-mod`.

Source: Weibel, §7.2, pp. 219--222 (FC05-C07-U016). -/
def trivialFunctor : ModuleCat.{w} R ⥤ LieModuleCat.{u, v, w} R L where
  obj M := trivialObject R L M
  map f :=
    { toLinearMap := f.hom
      map_lie' := by simp [trivial_lie_zero] }
  map_id _ := by
    apply LieModuleHom.ext
    intro m
    rfl
  map_comp _ _ := by
    apply LieModuleHom.ext
    intro m
    rfl

/-- Lie invariants `M^L`: the submodule annihilated by every element of `L`.

This is Mathlib's maximal trivial Lie submodule, whose membership condition is exactly
`∀ x : L, ⁅x,m⁆ = 0`.

Source: Weibel, §7.2, pp. 219--222 (FC05-C07-U016). -/
abbrev invariants (M : LieModuleCat.{u, v, w} R L) : ModuleCat.{w} R :=
  ModuleCat.of R (LieModule.maxTrivSubmodule R L M)

/-- Lie coinvariants `M_L = M / LM`, where `LM` is the submodule generated by all action values
`⁅x,m⁆`.  Mathlib's first lower-central-series term is exactly that action submodule.

Source: Weibel, §7.2, pp. 219--222 (FC05-C07-U016). -/
abbrev coinvariants (M : LieModuleCat.{u, v, w} R L) : ModuleCat.{w} R :=
  ModuleCat.of R (M ⧸ LieModule.lowerCentralSeries R L M 1)

/-- Lie invariants as a functor from `L`-modules to `R`-modules.

On a Lie-module morphism this is Mathlib's functorial map on maximal trivial submodules.

Source: Weibel, §7.2, pp. 219--222 (FC05-C07-U016--U017). -/
noncomputable def invariantsFunctor :
    LieModuleCat.{u, v, w} R L ⥤ ModuleCat.{w} R where
  obj M := invariants R L M
  map f := ModuleCat.ofHom (LieModule.maxTrivHom f).toLinearMap
  map_id M := by
    apply ModuleCat.hom_ext
    ext m
    rfl
  map_comp f g := by
    apply ModuleCat.hom_ext
    ext m
    rfl

instance invariantsFunctor_additive : Functor.Additive (invariantsFunctor R L) where
  map_add := by
    intro M N f g
    apply ModuleCat.hom_ext
    ext m
    rfl

/-- The map on Lie coinvariants induced by a Lie-module morphism. -/
noncomputable def coinvariantsMap {M N : LieModuleCat.{u, v, w} R L} (f : M ⟶ N) :
    coinvariants R L M ⟶ coinvariants R L N :=
  ModuleCat.ofHom <|
    Submodule.mapQ
      (LieModule.lowerCentralSeries R L M 1 : Submodule R M)
      (LieModule.lowerCentralSeries R L N 1 : Submodule R N)
      f.toLinearMap <| by
        rw [← Submodule.map_le_iff_le_comap, ← LieSubmodule.toSubmodule_map]
        exact LieModule.map_lowerCentralSeries_le (R := R) (L := L) (M := M) 1 f

/-- Lie coinvariants as a functor from `L`-modules to `R`-modules.

The denominator is the first lower-central-series term, and functoriality follows from Mathlib's
`map_lowerCentralSeries_le`.

Source: Weibel, §7.2, pp. 219--222 (FC05-C07-U016--U017). -/
noncomputable def coinvariantsFunctor :
    LieModuleCat.{u, v, w} R L ⥤ ModuleCat.{w} R where
  obj M := coinvariants R L M
  map f := coinvariantsMap R L f
  map_id M := by
    apply ModuleCat.hom_ext
    apply LinearMap.ext
    intro x
    induction x using Submodule.Quotient.induction_on with
    | _ x => rfl
  map_comp f g := by
    apply ModuleCat.hom_ext
    apply LinearMap.ext
    intro x
    induction x using Submodule.Quotient.induction_on with
    | _ x => rfl

instance coinvariantsFunctor_additive : Functor.Additive (coinvariantsFunctor R L) where
  map_add := by
    intro M N f g
    apply ModuleCat.hom_ext
    apply LinearMap.ext
    intro x
    induction x using Submodule.Quotient.induction_on with
    | _ x => rfl

end LieModuleCat

end LeanCategories.Homological
