/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.CategoryTheory.Monoidal.Bimod
public import Mathlib.Algebra.Category.ModuleCat.Monoidal.Symmetric
public import Mathlib.Algebra.Category.ModuleCat.ChangeOfRings
public import Mathlib.Algebra.Category.ModuleCat.Projective
public import Mathlib.CategoryTheory.Monoidal.Internal.Module
public import Mathlib.Algebra.Category.ModuleCat.Abelian
public import Mathlib.CategoryTheory.Abelian.LeftDerived
public import Mathlib.CategoryTheory.Limits.ExactFunctor
public import LeanCategories.Modules.FractionRingQuotient

/-!
# Tensor products over an associative ring

Weibel, *An Introduction to Homological Algebra* (1994), §§2.6--3.2.

The source convention is genuinely noncommutative: a tensor product over an
associative ring pairs a right module with a left module.  Mathlib's native
`TensorProduct R` is specialized to commutative scalars, so here the relative
tensor product is constructed from `A ⊗_ℤ B` by quotienting by the span of the
balancing relations `(ar) ⊗ b - a ⊗ (rb)`.  This is the concrete module model
of the standard coequalizer over the underlying abelian groups.
-/

@[expose] public section

namespace LeanCategories.Homological

open CategoryTheory Limits MonoidalCategory
open scoped TensorProduct

universe u v

/-- The elementary balancing relations `(ar) ⊗ b - a ⊗ (rb)` in `A ⊗_ℤ B`. -/
def balancedRelationSet (R : Type u) [Ring R]
    (A : ModuleCat Rᵐᵒᵖ) (B : ModuleCat R) : Set (A ⊗[ℤ] B) :=
  {x | ∃ (a : A) (r : R) (b : B),
    x = ((MulOpposite.op r : Rᵐᵒᵖ) • a) ⊗ₜ[ℤ] b - a ⊗ₜ[ℤ] (r • b)}

/-- The submodule generated by the balancing relations for a right/left module pair. -/
def balancedRelations (R : Type u) [Ring R]
    (A : ModuleCat Rᵐᵒᵖ) (B : ModuleCat R) : Submodule ℤ (A ⊗[ℤ] B) :=
  Submodule.span ℤ (balancedRelationSet R A B)

/-- The tensor product of a right and a left module over an associative ring. -/
abbrev RelativeTensor (R : Type u) [Ring R]
    (A : ModuleCat Rᵐᵒᵖ) (B : ModuleCat R) :=
  (A ⊗[ℤ] B) ⧸ balancedRelations R A B

/-- The relative tensor product as an object of abelian groups. -/
def relativeTensorModule (R : Type u) [Ring R]
    (A : ModuleCat Rᵐᵒᵖ) (B : ModuleCat R) : ModuleCat ℤ :=
  ModuleCat.of ℤ (RelativeTensor R A B)

/-- The map on underlying integral tensor products induced by module morphisms in both variables. -/
def relativeTensorUnderlyingMap (R : Type u) [Ring R]
    {A A' : ModuleCat Rᵐᵒᵖ} {B B' : ModuleCat R}
    (f : A ⟶ A') (g : B ⟶ B') : (A ⊗[ℤ] B) →ₗ[ℤ] (A' ⊗[ℤ] B') :=
  (TensorProduct.map f.hom.toAddMonoidHom.toIntLinearMap
      g.hom.toAddMonoidHom.toIntLinearMap).toAddMonoidHom.toIntLinearMap

@[simp]
theorem relativeTensorUnderlyingMap_tmul (R : Type u) [Ring R]
    {A A' : ModuleCat Rᵐᵒᵖ} {B B' : ModuleCat R}
    (f : A ⟶ A') (g : B ⟶ B') (a : A) (b : B) :
    relativeTensorUnderlyingMap R f g (a ⊗ₜ[ℤ] b) = f.hom a ⊗ₜ[ℤ] g.hom b :=
  rfl

theorem relativeTensorUnderlyingMap_balanced (R : Type u) [Ring R]
    {A A' : ModuleCat Rᵐᵒᵖ} {B B' : ModuleCat R}
    (f : A ⟶ A') (g : B ⟶ B') :
    balancedRelations R A B ≤
      (balancedRelations R A' B').comap (relativeTensorUnderlyingMap R f g) := by
  rw [balancedRelations]
  apply Submodule.span_le.2
  intro x hx
  rcases hx with ⟨a, r, b, rfl⟩
  change relativeTensorUnderlyingMap R f g
      (((MulOpposite.op r : Rᵐᵒᵖ) • a) ⊗ₜ[ℤ] b - a ⊗ₜ[ℤ] (r • b)) ∈
    balancedRelations R A' B'
  simp only [map_sub, relativeTensorUnderlyingMap_tmul]
  rw [f.hom.map_smul, g.hom.map_smul]
  apply Submodule.subset_span
  exact ⟨f.hom a, r, g.hom b, rfl⟩

/-- The morphism on relative tensor products induced by module morphisms in both variables. -/
def relativeTensorMap (R : Type u) [Ring R]
    {A A' : ModuleCat Rᵐᵒᵖ} {B B' : ModuleCat R}
    (f : A ⟶ A') (g : B ⟶ B') :
    relativeTensorModule R A B ⟶ relativeTensorModule R A' B' :=
  ModuleCat.ofHom <|
    Submodule.mapQ (balancedRelations R A B) (balancedRelations R A' B')
      (relativeTensorUnderlyingMap R f g) (relativeTensorUnderlyingMap_balanced R f g)

@[simp]
theorem relativeTensorMap_mk (R : Type u) [Ring R]
    {A A' : ModuleCat Rᵐᵒᵖ} {B B' : ModuleCat R}
    (f : A ⟶ A') (g : B ⟶ B') (x : A ⊗[ℤ] B) :
    relativeTensorMap R f g (Submodule.Quotient.mk x) =
      Submodule.Quotient.mk (relativeTensorUnderlyingMap R f g x) :=
  rfl

theorem relativeTensorUnderlyingMap_id (R : Type u) [Ring R]
    (A : ModuleCat Rᵐᵒᵖ) (B : ModuleCat R) :
    relativeTensorUnderlyingMap R (𝟙 A) (𝟙 B) = LinearMap.id := by
  apply LinearMap.ext
  intro x
  induction x using TensorProduct.induction_on with
  | zero => simp
  | add x y hx hy => simp [hx, hy]
  | tmul a b => rfl

theorem relativeTensorUnderlyingMap_comp (R : Type u) [Ring R]
    {A A' A'' : ModuleCat Rᵐᵒᵖ} {B B' B'' : ModuleCat R}
    (f : A ⟶ A') (f' : A' ⟶ A'') (g : B ⟶ B') (g' : B' ⟶ B'') :
    relativeTensorUnderlyingMap R (f ≫ f') (g ≫ g') =
      (relativeTensorUnderlyingMap R f' g').comp (relativeTensorUnderlyingMap R f g) := by
  apply LinearMap.ext
  intro x
  induction x using TensorProduct.induction_on with
  | zero => simp
  | add x y hx hy => simp [hx, hy]
  | tmul a b => rfl

theorem relativeTensorUnderlyingMap_add_left (R : Type u) [Ring R]
    {A A' : ModuleCat Rᵐᵒᵖ} {B B' : ModuleCat R}
    (f g : A ⟶ A') (h : B ⟶ B') :
    relativeTensorUnderlyingMap R (f + g) h =
      relativeTensorUnderlyingMap R f h + relativeTensorUnderlyingMap R g h := by
  apply LinearMap.ext
  intro x
  induction x using TensorProduct.induction_on with
  | zero => simp
  | add x y hx hy =>
      simp only [map_add, LinearMap.add_apply, hx, hy]
  | tmul a b => simp [relativeTensorUnderlyingMap_tmul, TensorProduct.add_tmul]

theorem relativeTensorUnderlyingMap_add_right (R : Type u) [Ring R]
    {A A' : ModuleCat Rᵐᵒᵖ} {B B' : ModuleCat R}
    (f : A ⟶ A') (g h : B ⟶ B') :
    relativeTensorUnderlyingMap R f (g + h) =
      relativeTensorUnderlyingMap R f g + relativeTensorUnderlyingMap R f h := by
  apply LinearMap.ext
  intro x
  induction x using TensorProduct.induction_on with
  | zero => simp
  | add x y hx hy =>
      simp only [map_add, LinearMap.add_apply, hx, hy]
  | tmul a b => simp [relativeTensorUnderlyingMap_tmul, TensorProduct.tmul_add]

theorem relativeTensorMap_id (R : Type u) [Ring R]
    (A : ModuleCat Rᵐᵒᵖ) (B : ModuleCat R) :
    relativeTensorMap R (𝟙 A) (𝟙 B) = 𝟙 (relativeTensorModule R A B) := by
  apply ModuleCat.hom_ext
  apply LinearMap.ext
  intro x
  induction x using Submodule.Quotient.induction_on with
  | _ x =>
      rw [relativeTensorMap_mk, relativeTensorUnderlyingMap_id]
      rfl

theorem relativeTensorMap_comp (R : Type u) [Ring R]
    {A A' A'' : ModuleCat Rᵐᵒᵖ} {B B' B'' : ModuleCat R}
    (f : A ⟶ A') (f' : A' ⟶ A'') (g : B ⟶ B') (g' : B' ⟶ B'') :
    relativeTensorMap R (f ≫ f') (g ≫ g') =
      relativeTensorMap R f g ≫ relativeTensorMap R f' g' := by
  apply ModuleCat.hom_ext
  apply LinearMap.ext
  intro x
  induction x using Submodule.Quotient.induction_on with
  | _ x =>
      change relativeTensorMap R (f ≫ f') (g ≫ g') (Submodule.Quotient.mk x) =
        relativeTensorMap R f' g' (relativeTensorMap R f g (Submodule.Quotient.mk x))
      rw [relativeTensorMap_mk, relativeTensorMap_mk, relativeTensorMap_mk]
      exact congrArg Submodule.Quotient.mk
        (DFunLike.congr_fun (relativeTensorUnderlyingMap_comp R f f' g g') x)

theorem relativeTensorMap_add_left (R : Type u) [Ring R]
    {A A' : ModuleCat Rᵐᵒᵖ} {B : ModuleCat R}
    (f g : A ⟶ A') :
    relativeTensorMap R (f + g) (𝟙 B) =
      relativeTensorMap R f (𝟙 B) + relativeTensorMap R g (𝟙 B) := by
  apply ModuleCat.hom_ext
  apply LinearMap.ext
  intro x
  induction x using Submodule.Quotient.induction_on with
  | _ x =>
      change relativeTensorMap R (f + g) (𝟙 B) (Submodule.Quotient.mk x) =
        relativeTensorMap R f (𝟙 B) (Submodule.Quotient.mk x) +
          relativeTensorMap R g (𝟙 B) (Submodule.Quotient.mk x)
      rw [relativeTensorMap_mk, relativeTensorMap_mk, relativeTensorMap_mk]
      exact congrArg Submodule.Quotient.mk
        (DFunLike.congr_fun (relativeTensorUnderlyingMap_add_left R f g (𝟙 B)) x)

theorem relativeTensorMap_add_right (R : Type u) [Ring R]
    {A : ModuleCat Rᵐᵒᵖ} {B B' : ModuleCat R}
    (f g : B ⟶ B') :
    relativeTensorMap R (𝟙 A) (f + g) =
      relativeTensorMap R (𝟙 A) f + relativeTensorMap R (𝟙 A) g := by
  apply ModuleCat.hom_ext
  apply LinearMap.ext
  intro x
  induction x using Submodule.Quotient.induction_on with
  | _ x =>
      change relativeTensorMap R (𝟙 A) (f + g) (Submodule.Quotient.mk x) =
        relativeTensorMap R (𝟙 A) f (Submodule.Quotient.mk x) +
          relativeTensorMap R (𝟙 A) g (Submodule.Quotient.mk x)
      rw [relativeTensorMap_mk, relativeTensorMap_mk, relativeTensorMap_mk]
      exact congrArg Submodule.Quotient.mk
        (DFunLike.congr_fun (relativeTensorUnderlyingMap_add_right R (𝟙 A) f g) x)

/-- Tensoring a right `R`-module with a fixed left `R`-module. -/
def tensorRightFunctor (R : Type u) [Ring R] (B : ModuleCat R) :
    ModuleCat Rᵐᵒᵖ ⥤ ModuleCat ℤ where
  obj A := relativeTensorModule R A B
  map f := relativeTensorMap R f (𝟙 B)
  map_id A := relativeTensorMap_id R A B
  map_comp f g := by simpa using relativeTensorMap_comp R f g (𝟙 B) (𝟙 B)

/-- Tensoring a fixed right `R`-module with a left `R`-module. -/
def tensorLeftFunctor (R : Type u) [Ring R] (A : ModuleCat Rᵐᵒᵖ) :
    ModuleCat R ⥤ ModuleCat ℤ where
  obj B := relativeTensorModule R A B
  map g := relativeTensorMap R (𝟙 A) g
  map_id B := relativeTensorMap_id R A B
  map_comp f g := by simpa using relativeTensorMap_comp R (𝟙 A) (𝟙 A) f g

instance tensorRightFunctor_additive (R : Type u) [Ring R] (B : ModuleCat R) :
    Functor.Additive (tensorRightFunctor R B) where
  map_add := by
    intro A A' f g
    exact relativeTensorMap_add_left (R := R) (B := B) f g

instance tensorLeftFunctor_additive (R : Type u) [Ring R] (A : ModuleCat Rᵐᵒᵖ) :
    Functor.Additive (tensorLeftFunctor R A) where
  map_add := by
    intro B B' f g
    exact relativeTensorMap_add_right (R := R) (A := A) f g

/-! ## Tor and flat modules -/

/-- Weibel's `Tor_n^R(-,B)` for an arbitrary associative ring: the `n`-th left-derived functor of
`- ⊗_R B` on right `R`-modules.

Source: Weibel, Definition 2.6.4, pp. 51--57 (FC05-C02-U056). -/
noncomputable def torFunctor (R : Type u) [Ring R] (B : ModuleCat R) (n : ℕ) :
    ModuleCat Rᵐᵒᵖ ⥤ ModuleCat ℤ :=
  (tensorRightFunctor R B).leftDerived n

/-- The value `Tor_n^R(A,B)` of the noncommutative Tor functor. -/
noncomputable def tor (R : Type u) [Ring R]
    (A : ModuleCat Rᵐᵒᵖ) (B : ModuleCat R) (n : ℕ) : ModuleCat ℤ :=
  (torFunctor R B n).obj A

/-- A left `R`-module is flat when tensoring right `R`-modules with it is exact.

Source: Weibel, Definition 3.2.1, pp. 77--80 (FC05-C03-U009). -/
def IsFlatLeftModule (R : Type u) [Ring R] (B : ModuleCat.{v} R) : Prop :=
  let F : ModuleCat.{v} Rᵐᵒᵖ ⥤ ModuleCat.{v} ℤ := tensorRightFunctor R B
  PreservesFiniteLimits F ∧ PreservesFiniteColimits F

/-- A right `R`-module is flat when tensoring it with left `R`-modules is exact.

This is the right-module dual in Weibel, Definition 3.2.1 (FC05-C03-U009). -/
def IsFlatRightModule (R : Type u) [Ring R] (A : ModuleCat.{v} Rᵐᵒᵖ) : Prop :=
  let F : ModuleCat.{v} R ⥤ ModuleCat.{v} ℤ := tensorLeftFunctor R A
  PreservesFiniteLimits F ∧ PreservesFiniteColimits F


end LeanCategories.Homological
