name = "lean_categories_sphere_packing"
version = "0.1.0"
defaultTargets = ["LeanCategoriesSpherePacking"]

[[require]]
name = "lean_categories"
path = "../.."

[[require]]
name = "SpherePacking"
git = "https://github.com/thefundamentaltheor3m/Sphere-Packing-Lean"
rev = "bad3de916074748eb88b7d1ee6dbf9494361ad17"

[[lean_lib]]
name = "LeanCategoriesSpherePacking"
srcDir = "../.."
