/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import LeanCategories.Lattices.Valued.Arithmetic
public import Mathlib.LinearAlgebra.Basis.Basic
public import Mathlib.LinearAlgebra.Basis.Prod
public import Mathlib.LinearAlgebra.DFinsupp
public import Mathlib.LinearAlgebra.Determinant
public import Mathlib.LinearAlgebra.Dual.Lemmas
public import Mathlib.LinearAlgebra.Dual.Basis
public import Mathlib.LinearAlgebra.Matrix.BilinearForm
public import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
public import Mathlib.RingTheory.Finiteness.Prod

@[expose] public section

open CategoryTheory
open LeanCategories.Modules.Bilinear.Valued

namespace LeanCategories.Lattices.Valued

universe u

variable {R W : Type u} [CommRing R] [AddCommGroup W] [Module R W]

/-- Scale the form of a lattice without changing its module. -/
def scaleLattice (L : LatticeCat R W) (a : R) : LatticeCat R W := by
  let scaled := LinearMap.mk₂ R
    (fun x y ↦ a • L.obj.pairing x y)
    (fun _ _ _ ↦ by simp [smul_add])
    (fun _ _ _ ↦ by simp [smul_smul, mul_comm])
    (fun _ _ _ ↦ by simp [smul_add])
    (fun _ _ _ ↦ by simp [smul_smul, mul_comm])
  refine ⟨BilinModuleCat.ofBilinMap scaled, L.property.1, ?_⟩
  intro x y
  change a • L.obj.pairing x y = a • L.obj.pairing y x
  rw [L.property.2 x y]

/-- Change a lattice form to its negative. -/
def oppositeLattice (L : LatticeCat R W) : LatticeCat R W :=
  scaleLattice L (-1)

/-- Change a finite projective lattice form to its negative. -/
def oppositeFiniteProjectiveLattice (L : FiniteProjectiveLatticeCat R W) :
    FiniteProjectiveLatticeCat R W :=
  ⟨oppositeLattice L.obj, L.property⟩

@[simp]
theorem oppositeLattice_pairing (L : LatticeCat R W) (x y : L.obj.carrier) :
    (oppositeLattice L).obj.pairing x y = -L.obj.pairing x y := by
  simp [oppositeLattice, scaleLattice]

/-- The tensor product of two integral lattices. -/
def tensorProductLattice (L M : IntegralLatticeCat R) :
    IntegralLatticeCat R := by
  refine ⟨BilinModuleCat.ofBilinMap
    (LinearMap.BilinForm.tmul L.obj.bilinMap M.obj.bilinMap), ?_, ?_⟩
  · letI : Module.Projective R L.obj.carrier := L.property.1
    letI : Module.Projective R M.obj.carrier := M.property.1
    change Module.Projective R
      (TensorProduct R L.obj.carrier M.obj.carrier)
    infer_instance
  · let hL : LinearMap.IsSymm L.obj.bilinMap :=
      ⟨fun x y ↦ by simpa using L.property.2 x y⟩
    let hM : LinearMap.IsSymm M.obj.bilinMap :=
      ⟨fun x y ↦ by simpa using M.property.2 x y⟩
    exact (hL.tmul hM).eq

@[simp]
theorem tensorProductLattice_pairing_tmul
    (L M : IntegralLatticeCat R)
    (x x' : L.obj.carrier) (y y' : M.obj.carrier) :
    (tensorProductLattice L M).obj.pairing
      (x ⊗ₜ[R] y) (x' ⊗ₜ[R] y') =
        L.obj.pairing x x' * M.obj.pairing y y' :=
  by
    change LinearMap.BilinForm.tmul L.obj.bilinMap M.obj.bilinMap
      (x ⊗ₜ[R] y) (x' ⊗ₜ[R] y') = _
    rw [LinearMap.BilinForm.tensorDistrib_tmul]
    simp [smul_eq_mul, mul_comm]

/-- A vector is isotropic when its self-pairing is zero. -/
def IsIsotropic (L : LatticeCat R W) (x : L.obj.carrier) : Prop :=
  L.obj.pairing x x = 0

/-- A vector in an integral lattice is a root of square `1`, `-1`, `2`, or `-2`. -/
def IsRoot (L : IntegralLatticeCat R) (x : L.obj.carrier) : Prop :=
  L.obj.pairing x x = 2 ∨ L.obj.pairing x x = -2 ∨
    L.obj.pairing x x = 1 ∨ L.obj.pairing x x = -1

/-- The ideal generated by all pairings with a fixed vector. -/
def divisibility (L : IntegralLatticeCat R) (x : L.obj.carrier) : Ideal R :=
  LinearMap.range (L.obj.bilinMap x)

/-- The Gram matrix of a lattice in a selected basis. -/
noncomputable def gramMatrix {I : Type*} [Fintype I] [DecidableEq I]
    (L : IntegralLatticeCat R)
    (b : Module.Basis I R L.obj.carrier) : Matrix I I R :=
  LinearMap.BilinForm.toMatrix b L.obj.bilinMap

@[simp]
theorem gramMatrix_opposite {I : Type*} [Fintype I] [DecidableEq I]
    (L : IntegralLatticeCat R)
    (b : Module.Basis I R L.obj.carrier) :
    gramMatrix (oppositeLattice L) b = -gramMatrix L b := by
  ext i j
  simp [gramMatrix, LinearMap.BilinForm.toMatrix_apply]
  rfl

/-- The determinant of a finite Gram matrix. -/
noncomputable def determinant {I : Type*} [Fintype I] [DecidableEq I]
    (L : IntegralLatticeCat R) (b : Module.Basis I R L.obj.carrier) : R :=
  (gramMatrix L b).det

/-- Gram determinants from two bases with the same index are associated. -/
theorem determinant_associated {I : Type*} [Fintype I] [DecidableEq I]
    (L : IntegralLatticeCat R)
    (b c : Module.Basis I R L.obj.carrier) :
    Associated (determinant L b) (determinant L c) := by
  letI := b.invertibleToMatrix c
  have hu : IsUnit (b.toMatrix c).det :=
    (Matrix.isUnit_iff_isUnit_det (b.toMatrix c)).mp
      (isUnit_of_invertible (b.toMatrix c))
  have hmatrix :=
    LinearMap.BilinForm.toMatrix_mul_basis_toMatrix (b := b) c L.obj.bilinMap
  have hdet := congrArg Matrix.det hmatrix
  simp only [Matrix.det_mul, Matrix.det_transpose] at hdet
  simp only [determinant, gramMatrix]
  apply (associated_mul_unit_right
    ((LinearMap.BilinForm.toMatrix b) L.obj.bilinMap).det
    ((b.toMatrix c).det * (b.toMatrix c).det) (hu.mul hu)).trans
  rw [← hdet]
  simpa only [mul_assoc, mul_comm, mul_left_comm] using
    (Associated.refl
      (((LinearMap.BilinForm.toMatrix b) L.obj.bilinMap).det *
        ((b.toMatrix c).det * (b.toMatrix c).det)))

/-- The determinant ideal of a finite free lattice in a selected basis. -/
noncomputable def determinantIdeal {I : Type*} [Fintype I] [DecidableEq I]
    (L : IntegralLatticeCat R)
    (b : Module.Basis I R L.obj.carrier) : Ideal R :=
  Ideal.span {determinant L b}

/-- The determinant ideal does not depend on the selected basis. -/
theorem determinantIdeal_eq {I : Type*} [Fintype I] [DecidableEq I]
    (L : IntegralLatticeCat R)
    (b c : Module.Basis I R L.obj.carrier) :
    determinantIdeal L b = determinantIdeal L c := by
  obtain ⟨u, hu⟩ := determinant_associated L b c
  change Ideal.span {determinant L b} = Ideal.span {determinant L c}
  rw [← hu, Ideal.span_singleton_mul_right_unit u.isUnit]

@[simp]
theorem determinantIdeal_eq_top_iff {I : Type*} [Fintype I]
    [DecidableEq I] (L : IntegralLatticeCat R)
    (b : Module.Basis I R L.obj.carrier) :
    determinantIdeal L b = ⊤ ↔ IsUnit (determinant L b) := by
  exact Ideal.span_singleton_eq_top

/-- Unimodularity does not depend on the selected finite basis. -/
theorem isUnit_determinant_iff {I : Type*} [Fintype I] [DecidableEq I]
    (L : IntegralLatticeCat R)
    (b c : Module.Basis I R L.obj.carrier) :
    IsUnit (determinant L b) ↔ IsUnit (determinant L c) :=
  (determinant_associated L b c).isUnit_iff

/-- The adjoint matrix in the dual basis is the Gram matrix. -/
theorem adjoint_toMatrix_eq_gramMatrix {I : Type*} [Fintype I]
    [DecidableEq I] (L : IntegralLatticeCat R)
    (b : Module.Basis I R L.obj.carrier) :
    LinearMap.toMatrix b b.dualBasis L.obj.adjoint = gramMatrix L b := by
  ext i j
  rw [LinearMap.toMatrix_apply, Module.Basis.dualBasis_repr]
  rw [gramMatrix, LinearMap.BilinForm.toMatrix_apply]
  change L.obj.pairing (b j) (b i) = L.obj.pairing (b i) (b j)
  exact L.property.2 (b j) (b i)

/-- For a finite free lattice, perfectness is equivalent to a unit Gram determinant. -/
theorem isPerfect_iff_isUnit_determinant {I : Type*} [Fintype I]
    [DecidableEq I] (L : IntegralLatticeCat R)
    (b : Module.Basis I R L.obj.carrier) :
    L.obj.IsPerfect ↔ IsUnit (determinant L b) := by
  rw [determinant]
  rw [← adjoint_toMatrix_eq_gramMatrix L b]
  constructor
  · intro h
    exact (LinearEquiv.ofBijective L.obj.adjoint h).isUnit_det b b.dualBasis
  · intro h
    exact (LinearEquiv.ofIsUnitDet
      (f := L.obj.adjoint) (v := b) (v' := b.dualBasis) h).bijective

/-- A finite free lattice is perfect exactly when its determinant ideal is trivial. -/
theorem isPerfect_iff_determinantIdeal_eq_top {I : Type*} [Fintype I]
    [DecidableEq I] (L : IntegralLatticeCat R)
    (b : Module.Basis I R L.obj.carrier) :
    L.obj.IsPerfect ↔ determinantIdeal L b = ⊤ := by
  exact (isPerfect_iff_isUnit_determinant L b).trans
    (determinantIdeal_eq_top_iff L b).symm

/-- The orthogonal direct-sum bilinear map. -/
def orthogonalSumBilinMap (L₁ L₂ : BilinModuleCat R W) :
    LinearMap.BilinMap R (L₁.carrier × L₂.carrier) W :=
  LinearMap.mk₂ R
    (fun x y ↦ L₁.pairing x.1 y.1 + L₂.pairing x.2 y.2)
    (fun _ _ _ ↦ by simp [add_assoc, add_left_comm])
    (fun _ _ _ ↦ by simp)
    (fun _ _ _ ↦ by simp [add_assoc, add_left_comm])
    (fun _ _ _ ↦ by simp)

/-- The orthogonal direct sum of two lattices. -/
def orthogonalSum (L₁ L₂ : LatticeCat R W) : LatticeCat R W := by
  letI : Module.Projective R L₁.obj.carrier := L₁.property.1
  letI : Module.Projective R L₂.obj.carrier := L₂.property.1
  refine ⟨BilinModuleCat.ofBilinMap
    (orthogonalSumBilinMap L₁.obj L₂.obj), ?_, ?_⟩
  · change Module.Projective R (L₁.obj.carrier × L₂.obj.carrier)
    infer_instance
  rintro ⟨x₁, x₂⟩ ⟨y₁, y₂⟩
  change L₁.obj.pairing x₁ y₁ + L₂.obj.pairing x₂ y₂ =
    L₁.obj.pairing y₁ x₁ + L₂.obj.pairing y₂ x₂
  rw [L₁.property.2 x₁ y₁, L₂.property.2 x₂ y₂]

/-- The orthogonal sum of two finite symmetric forms. -/
def finiteFormOrthogonalSum (L₁ L₂ : FiniteFormCat R W) :
    FiniteFormCat R W := by
  refine ⟨BilinModuleCat.ofBilinMap
    (orthogonalSumBilinMap L₁.obj L₂.obj), ?_, ?_⟩
  · letI : Module.Finite R L₁.obj.carrier := L₁.property.1
    letI : Module.Finite R L₂.obj.carrier := L₂.property.1
    change Module.Finite R (L₁.obj.carrier × L₂.obj.carrier)
    infer_instance
  · rintro ⟨x₁, x₂⟩ ⟨y₁, y₂⟩
    change L₁.obj.pairing x₁ y₁ + L₂.obj.pairing x₂ y₂ =
      L₁.obj.pairing y₁ x₁ + L₂.obj.pairing y₂ x₂
    rw [L₁.property.2 x₁ y₁, L₂.property.2 x₂ y₂]

/-- The orthogonal sum of two finite projective lattices. -/
def finiteProjectiveOrthogonalSum
    (L₁ L₂ : FiniteProjectiveLatticeCat R W) :
    FiniteProjectiveLatticeCat R W := by
  refine ⟨orthogonalSum L₁.obj L₂.obj, ?_⟩
  letI : Module.Finite R L₁.obj.obj.carrier := L₁.property
  letI : Module.Finite R L₂.obj.obj.carrier := L₂.property
  change Module.Finite R (L₁.obj.obj.carrier × L₂.obj.obj.carrier)
  infer_instance

/-- The rank of a finite projective orthogonal sum is additive. -/
theorem finiteProjectiveOrthogonalSum_rank [IsDomain R]
    [IsPrincipalIdealRing R]
    (L₁ L₂ : FiniteProjectiveLatticeCat R W) :
    (finiteProjectiveOrthogonalSum L₁ L₂).rank = L₁.rank + L₂.rank := by
  letI : Module.Finite R L₁.obj.obj.carrier := L₁.property
  letI : Module.Finite R L₂.obj.obj.carrier := L₂.property
  letI : Module.Projective R L₁.obj.obj.carrier := L₁.obj.property.1
  letI : Module.Projective R L₂.obj.obj.carrier := L₂.obj.property.1
  letI : Module.Free R L₁.obj.obj.carrier := L₁.carrier_free
  letI : Module.Free R L₂.obj.obj.carrier := L₂.carrier_free
  change Module.finrank R
      (L₁.obj.obj.carrier × L₂.obj.obj.carrier) =
    Module.finrank R L₁.obj.obj.carrier +
      Module.finrank R L₂.obj.obj.carrier
  exact Module.finrank_prod

@[simp]
theorem orthogonalSum_pairing (L₁ L₂ : LatticeCat R W)
    (x y : L₁.obj.carrier × L₂.obj.carrier) :
    (orthogonalSum L₁ L₂).obj.pairing x y =
      L₁.obj.pairing x.1 y.1 + L₂.obj.pairing x.2 y.2 :=
  rfl

/-- The product basis gives a block Gram matrix for an orthogonal sum. -/
theorem gramMatrix_orthogonalSum
    {I J : Type*} [Fintype I] [Fintype J]
    [DecidableEq I] [DecidableEq J]
    (L M : IntegralLatticeCat R)
    (b : Module.Basis I R L.obj.carrier)
    (c : Module.Basis J R M.obj.carrier) :
    gramMatrix (orthogonalSum L M) (b.prod c) =
      Matrix.fromBlocks (gramMatrix L b) 0 0 (gramMatrix M c) := by
  ext i j
  rw [gramMatrix, LinearMap.BilinForm.toMatrix_apply]
  change L.obj.pairing ((b.prod c i).1) ((b.prod c j).1) +
      M.obj.pairing ((b.prod c i).2) ((b.prod c j).2) = _
  cases i <;> cases j <;>
    simp [gramMatrix, LinearMap.BilinForm.toMatrix_apply]

/-- Gram determinants multiply under orthogonal sums. -/
theorem determinant_orthogonalSum
    {I J : Type*} [Fintype I] [Fintype J]
    [DecidableEq I] [DecidableEq J]
    (L M : IntegralLatticeCat R)
    (b : Module.Basis I R L.obj.carrier)
    (c : Module.Basis J R M.obj.carrier) :
    determinant (orthogonalSum L M) (b.prod c) =
      determinant L b * determinant M c := by
  rw [determinant, gramMatrix_orthogonalSum,
    Matrix.det_fromBlocks_zero₂₁]
  rfl

/-- Determinant ideals multiply under orthogonal sums. -/
theorem determinantIdeal_orthogonalSum
    {I J : Type*} [Fintype I] [Fintype J]
    [DecidableEq I] [DecidableEq J]
    (L M : IntegralLatticeCat R)
    (b : Module.Basis I R L.obj.carrier)
    (c : Module.Basis J R M.obj.carrier) :
    determinantIdeal (orthogonalSum L M) (b.prod c) =
      determinantIdeal L b * determinantIdeal M c := by
  rw [determinantIdeal, determinant_orthogonalSum]
  change Ideal.span {determinant L b * determinant M c} =
    Ideal.span {determinant L b} * Ideal.span {determinant M c}
  exact (Ideal.span_singleton_mul_span_singleton _ _).symm

/-- An orthogonal sum of perfect integral lattices is perfect. -/
theorem isPerfect_orthogonalSum (L₁ L₂ : IntegralLatticeCat R)
    (h₁ : L₁.obj.IsPerfect) (h₂ : L₂.obj.IsPerfect) :
    (orthogonalSum L₁ L₂).obj.IsPerfect := by
  let e : (L₁.obj.carrier × L₂.obj.carrier) ≃ₗ[R]
      ((L₁.obj.carrier × L₂.obj.carrier) →ₗ[R] R) :=
    (LinearEquiv.prodCongr
      (LinearEquiv.ofBijective L₁.obj.adjoint h₁)
      (LinearEquiv.ofBijective L₂.obj.adjoint h₂)).trans
        (Module.dualProdDualEquivDual R L₁.obj.carrier L₂.obj.carrier)
  change Function.Bijective (orthogonalSum L₁ L₂).obj.adjoint
  have he : (orthogonalSum L₁ L₂).obj.adjoint = e.toLinearMap := by
    apply LinearMap.ext
    intro x
    apply LinearMap.ext
    intro y
    rfl
  rw [he]
  exact e.bijective

/-- The bilinear map for a finite indexed orthogonal sum. -/
noncomputable def indexedOrthogonalSumBilinMap {I : Type} [Fintype I]
    (L : I → BilinModuleCat R W) :
    LinearMap.BilinMap R ((i : I) → (L i).carrier) W := by
  classical
  exact LinearMap.mk₂ R
    (fun x y ↦ ∑ i, (L i).pairing (x i) (y i))
    (fun _ _ _ ↦ by simp [Finset.sum_add_distrib])
    (fun _ _ _ ↦ by simp [Finset.smul_sum])
    (fun _ _ _ ↦ by simp [Finset.sum_add_distrib])
    (fun _ _ _ ↦ by simp [Finset.smul_sum])

/-- The orthogonal sum of a finite indexed family of lattices. -/
noncomputable def indexedOrthogonalSum {I : Type} [Fintype I]
    (L : I → LatticeCat R W) : LatticeCat R W := by
  letI (i : I) : Module.Projective R (L i).obj.carrier := (L i).property.1
  refine ⟨BilinModuleCat.ofBilinMap
    (indexedOrthogonalSumBilinMap fun i ↦ (L i).obj), ?_, ?_⟩
  · change Module.Projective R ((i : I) → (L i).obj.carrier)
    exact Module.Projective.of_equiv'
      (DFinsupp.linearEquivFunOnFintype (R := R)
        (M := fun i ↦ (L i).obj.carrier))
  · intro x y
    change (∑ i, (L i).obj.pairing (x i) (y i)) =
      ∑ i, (L i).obj.pairing (y i) (x i)
    apply Finset.sum_congr rfl
    intro i _
    exact (L i).property.2 (x i) (y i)

@[simp]
theorem indexedOrthogonalSum_pairing {I : Type} [Fintype I]
    (L : I → LatticeCat R W)
    (x y : (i : I) → (L i).obj.carrier) :
    (indexedOrthogonalSum L).obj.pairing x y =
      ∑ i, (L i).obj.pairing (x i) (y i) :=
  rfl

/-- The orthogonal sum of a finite indexed family of finite symmetric forms. -/
noncomputable def finiteFormIndexedOrthogonalSum {I : Type} [Fintype I]
    (L : I → FiniteFormCat R W) : FiniteFormCat R W := by
  refine ⟨BilinModuleCat.ofBilinMap (indexedOrthogonalSumBilinMap fun i ↦ (L i).obj), ?_, ?_⟩
  · letI (i : I) : Module.Finite R (L i).obj.carrier := (L i).property.1
    change Module.Finite R ((i : I) → (L i).obj.carrier)
    infer_instance
  · intro x y
    change (∑ i, (L i).obj.pairing (x i) (y i)) =
      ∑ i, (L i).obj.pairing (y i) (x i)
    apply Finset.sum_congr rfl
    intro i _
    exact (L i).property.2 (x i) (y i)

@[simp]
theorem finiteFormIndexedOrthogonalSum_pairing {I : Type} [Fintype I]
    (L : I → FiniteFormCat R W)
    (x y : (finiteFormIndexedOrthogonalSum L).obj.carrier) :
    (finiteFormIndexedOrthogonalSum L).obj.pairing x y =
      ∑ i, (L i).obj.pairing (x i) (y i) :=
  rfl

/-- The `n`-fold orthogonal power of a finite symmetric form. -/
noncomputable def finiteFormOrthogonalPower (L : FiniteFormCat R W) (n : ℕ) :
    FiniteFormCat R W :=
  finiteFormIndexedOrthogonalSum (I := Fin n) fun _ ↦ L

@[simp]
theorem finiteFormOrthogonalPower_pairing (L : FiniteFormCat R W) (n : ℕ)
    (x y : (finiteFormOrthogonalPower L n).obj.carrier) :
    (finiteFormOrthogonalPower L n).obj.pairing x y =
      ∑ i, L.obj.pairing (x i) (y i) :=
  rfl

/-- The orthogonal sum of a finite indexed family of finite projective lattices. -/
noncomputable def finiteProjectiveIndexedOrthogonalSum
    {I : Type} [Fintype I] (L : I → FiniteProjectiveLatticeCat R W) :
    FiniteProjectiveLatticeCat R W := by
  refine ⟨indexedOrthogonalSum fun i ↦ (L i).obj, ?_⟩
  letI (i : I) : Module.Finite R (L i).obj.obj.carrier := (L i).property
  change Module.Finite R ((i : I) → (L i).obj.obj.carrier)
  infer_instance

/-- The `n`-fold orthogonal power of a finite projective lattice. -/
noncomputable def finiteProjectiveOrthogonalPower
    (L : FiniteProjectiveLatticeCat R W) (n : ℕ) :
    FiniteProjectiveLatticeCat R W :=
  finiteProjectiveIndexedOrthogonalSum (I := Fin n) fun _ ↦ L

/-- The rank of an orthogonal power is the rank times its exponent. -/
theorem finiteProjectiveOrthogonalPower_rank [IsDomain R]
    [IsPrincipalIdealRing R]
    (L : FiniteProjectiveLatticeCat R W) (n : ℕ) :
    (finiteProjectiveOrthogonalPower L n).rank = n * L.rank := by
  letI : Module.Projective R L.obj.obj.carrier := L.obj.property.1
  letI : Module.Finite R L.obj.obj.carrier := L.property
  letI : Module.Free R L.obj.obj.carrier := L.carrier_free
  change Module.finrank R (Fin n → L.obj.obj.carrier) =
    n * Module.finrank R L.obj.obj.carrier
  rw [Module.finrank_pi_fintype]
  simp

@[simp]
theorem finiteProjectiveOrthogonalPower_pairing
    (L : FiniteProjectiveLatticeCat R W) (n : ℕ)
    (x y : Fin n → L.obj.obj.carrier) :
    (finiteProjectiveOrthogonalPower L n).obj.obj.pairing x y =
      ∑ i, L.obj.obj.pairing (x i) (y i) :=
  rfl

/-- A successor orthogonal power splits off its first summand. -/
noncomputable def finiteProjectiveOrthogonalPowerSuccIso
    (L : FiniteProjectiveLatticeCat R W) (n : ℕ) :
    finiteProjectiveOrthogonalPower L (n + 1) ≅
      finiteProjectiveOrthogonalSum L
        (finiteProjectiveOrthogonalPower L n) := by
  let e : (Fin (n + 1) → L.obj.obj.carrier) ≃ₗ[R]
      L.obj.obj.carrier × (Fin n → L.obj.obj.carrier) :=
    (Fin.consLinearEquiv R fun _ : Fin (n + 1) ↦ L.obj.obj.carrier).symm
  have he (x y : Fin (n + 1) → L.obj.obj.carrier) :
      (finiteProjectiveOrthogonalSum L
        (finiteProjectiveOrthogonalPower L n)).obj.obj.pairing
          (e x) (e y) =
        (finiteProjectiveOrthogonalPower L (n + 1)).obj.obj.pairing x y := by
    change L.obj.obj.pairing (x 0) (y 0) +
        ∑ i : Fin n, L.obj.obj.pairing (x i.succ) (y i.succ) =
      ∑ i : Fin (n + 1), L.obj.obj.pairing (x i) (y i)
    rw [Fin.sum_univ_succ]
  let eBilin :
      (finiteProjectiveOrthogonalPower L (n + 1)).obj.obj ≅
        (finiteProjectiveOrthogonalSum L
          (finiteProjectiveOrthogonalPower L n)).obj.obj := {
    hom := BilinModuleCat.homMk e.toLinearMap he
    inv := BilinModuleCat.homMk e.symm.toLinearMap (fun x y ↦ by
      change (∑ i : Fin (n + 1),
          L.obj.obj.pairing ((e.symm x) i) ((e.symm y) i)) =
        L.obj.obj.pairing x.1 y.1 +
          ∑ i : Fin n, L.obj.obj.pairing (x.2 i) (y.2 i)
      rw [Fin.sum_univ_succ]
      rfl)
    hom_inv_id := by
      apply Quiver.Hom.unop_inj
      apply CategoryOfElements.ext
      apply Quiver.Hom.unop_inj
      apply ModuleCat.hom_ext
      ext x
      change e.symm (e x) = x
      exact e.symm_apply_apply x
    inv_hom_id := by
      apply Quiver.Hom.unop_inj
      apply CategoryOfElements.ext
      apply Quiver.Hom.unop_inj
      apply ModuleCat.hom_ext
      ext x
      change e (e.symm x) = x
      exact e.apply_symm_apply x
  }
  let eLattice := ObjectProperty.isoMk (P := isLattice R W) eBilin
  exact ObjectProperty.isoMk
    (P := isFiniteProjectiveLattice R W) eLattice

/-- A finite indexed orthogonal sum of perfect lattices is perfect. -/
theorem isPerfect_indexedOrthogonalSum {I : Type} [Fintype I]
    (L : I → IntegralLatticeCat R) (hL : ∀ i, (L i).obj.IsPerfect) :
    (indexedOrthogonalSum L).obj.IsPerfect := by
  classical
  let e : ((i : I) → (L i).obj.carrier) ≃ₗ[R]
      (((i : I) → (L i).obj.carrier) →ₗ[R] R) :=
    (LinearEquiv.piCongrRight fun i ↦
      LinearEquiv.ofBijective (L i).obj.adjoint (hL i)).trans
        (LinearMap.lsum R (fun i ↦ (L i).obj.carrier) R)
  change Function.Bijective (indexedOrthogonalSum L).obj.adjoint
  have he : (indexedOrthogonalSum L).obj.adjoint = e.toLinearMap := by
    apply LinearMap.ext
    intro x
    apply LinearMap.ext
    intro y
    change (∑ i, (L i).obj.pairing (x i) (y i)) =
      (LinearMap.lsum R (fun i ↦ (L i).obj.carrier) R
        (fun i ↦ (L i).obj.adjoint (x i))) y
    rw [LinearMap.lsum_apply]
    simp only [LinearMap.sum_apply, LinearMap.coe_comp,
      Function.comp_apply, LinearMap.proj_apply]
    rfl
  rw [he]
  exact e.bijective

/-- The `n`-fold orthogonal power of a lattice. -/
noncomputable def orthogonalPower (L : LatticeCat R W) (n : ℕ) :
    LatticeCat R W :=
  indexedOrthogonalSum (I := Fin n) fun _ ↦ L

@[simp]
theorem orthogonalPower_pairing (L : LatticeCat R W) (n : ℕ)
    (x y : Fin n → L.obj.carrier) :
    (orthogonalPower L n).obj.pairing x y =
      ∑ i, L.obj.pairing (x i) (y i) :=
  rfl

/-- Every finite orthogonal power of a perfect lattice is perfect. -/
theorem isPerfect_orthogonalPower (L : IntegralLatticeCat R) (n : ℕ)
    (hL : L.obj.IsPerfect) : (orthogonalPower L n).obj.IsPerfect :=
  isPerfect_indexedOrthogonalSum (fun _ : Fin n ↦ L) (fun _ ↦ hL)

end LeanCategories.Lattices.Valued
