/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import LeanCategories.Lattices.Valued.Basic
public import Mathlib.LinearAlgebra.Basis.Basic
public import Mathlib.LinearAlgebra.Matrix.BilinearForm
public import Mathlib.LinearAlgebra.Matrix.Determinant.Basic

@[expose] public section

open CategoryTheory
open LeanCategories.Modules.Bilinear.Valued

namespace LeanCategories.Lattices.Valued

universe u

variable {R W : Type u} [CommRing R] [AddCommGroup W] [Module R W]

/-- Scale the form of a lattice without changing its module. -/
def scaleLattice (L : LatticeCat R W) (a : R) : LatticeCat R W := by
  let scaled := LinearMap.mk₂ R
    (fun x y ↦ a • L.obj.pairing x y)
    (fun _ _ _ ↦ by simp [smul_add])
    (fun _ _ _ ↦ by simp [smul_smul, mul_comm])
    (fun _ _ _ ↦ by simp [smul_add])
    (fun _ _ _ ↦ by simp [smul_smul, mul_comm])
  refine ⟨BilinModuleCat.ofBilinMap scaled, L.property.1, ?_⟩
  intro x y
  change a • L.obj.pairing x y = a • L.obj.pairing y x
  rw [L.property.2 x y]

/-- Change a lattice form to its negative. -/
def oppositeLattice (L : LatticeCat R W) : LatticeCat R W :=
  scaleLattice L (-1)

/-- A vector is isotropic when its self-pairing is zero. -/
def IsIsotropic (L : LatticeCat R W) (x : L.obj.carrier) : Prop :=
  L.obj.pairing x x = 0

/-- A vector in an integral lattice is a root of square `1`, `-1`, `2`, or `-2`. -/
def IsRoot (L : IntegralLatticeCat R) (x : L.obj.carrier) : Prop :=
  L.obj.pairing x x = 2 ∨ L.obj.pairing x x = -2 ∨
    L.obj.pairing x x = 1 ∨ L.obj.pairing x x = -1

/-- The ideal generated by all pairings with a fixed vector. -/
def divisibility (L : IntegralLatticeCat R) (x : L.obj.carrier) : Ideal R :=
  LinearMap.range (L.obj.bilinMap x)

/-- The Gram matrix of a lattice in a selected basis. -/
noncomputable def gramMatrix {I : Type*} (L : IntegralLatticeCat R)
    (b : Module.Basis I R L.obj.carrier) : Matrix I I R :=
  Matrix.of fun i j ↦ L.obj.pairing (b i) (b j)

/-- The determinant of a finite Gram matrix. -/
noncomputable def determinant {I : Type*} [Fintype I] [DecidableEq I]
    (L : IntegralLatticeCat R) (b : Module.Basis I R L.obj.carrier) : R :=
  (gramMatrix L b).det

/-- A finite based lattice is unimodular when its Gram determinant is a unit. -/
def IsUnimodular {I : Type*} [Fintype I] [DecidableEq I]
    (L : IntegralLatticeCat R) (b : Module.Basis I R L.obj.carrier) : Prop :=
  IsUnit (determinant L b)

/-- The orthogonal direct-sum bilinear map. -/
def orthogonalSumBilinMap (L₁ L₂ : LatticeCat R W) :
    LinearMap.BilinMap R (L₁.obj.carrier × L₂.obj.carrier) W :=
  LinearMap.mk₂ R
    (fun x y ↦ L₁.obj.pairing x.1 y.1 + L₂.obj.pairing x.2 y.2)
    (fun _ _ _ ↦ by simp [add_assoc, add_left_comm, add_comm])
    (fun _ _ _ ↦ by simp)
    (fun _ _ _ ↦ by simp [add_assoc, add_left_comm, add_comm])
    (fun _ _ _ ↦ by simp)

/-- The orthogonal direct sum of two lattices. -/
def orthogonalSum (L₁ L₂ : LatticeCat R W) : LatticeCat R W := by
  letI : Module.Projective R L₁.obj.carrier := L₁.property.1
  letI : Module.Projective R L₂.obj.carrier := L₂.property.1
  refine ⟨BilinModuleCat.ofBilinMap (orthogonalSumBilinMap L₁ L₂), ?_, ?_⟩
  · change Module.Projective R (L₁.obj.carrier × L₂.obj.carrier)
    infer_instance
  rintro ⟨x₁, x₂⟩ ⟨y₁, y₂⟩
  change L₁.obj.pairing x₁ y₁ + L₂.obj.pairing x₂ y₂ =
    L₁.obj.pairing y₁ x₁ + L₂.obj.pairing y₂ x₂
  rw [L₁.property.2 x₁ y₁, L₂.property.2 x₂ y₂]

@[simp]
theorem orthogonalSum_pairing (L₁ L₂ : LatticeCat R W)
    (x y : L₁.obj.carrier × L₂.obj.carrier) :
    (orthogonalSum L₁ L₂).obj.pairing x y =
      L₁.obj.pairing x.1 y.1 + L₂.obj.pairing x.2 y.2 :=
  rfl

end LeanCategories.Lattices.Valued
