/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import LeanCategories.Lattices.Valued.Completion
public import LeanCategories.Lattices.Valued.IdealDual
public import LeanCategories.Lattices.Valued.MetricDual
public import LeanCategories.Lattices.Valued.ScaleAndEvenness

@[expose] public section

open CategoryTheory

namespace LeanCategories.Lattices.Valued

open IsDedekindDomain

universe u

private instance primeTwoFact : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩

section DyadicPlace

variable {R : Type u} [CommRing R] [IsDedekindDomain R]

/-- A height-one place is dyadic when its residue characteristic is two. -/
def IsDyadic (v : HeightOneSpectrum R) : Prop :=
  (2 : R) ∈ v.asIdeal

omit [IsDedekindDomain R] in
/-- A place is dyadic exactly when two vanishes in its residue ring. -/
theorem isDyadic_iff_two_eq_zero (v : HeightOneSpectrum R) :
    IsDyadic v ↔ (2 : R ⧸ v.asIdeal) = 0 := by
  rw [IsDyadic, ← Ideal.Quotient.eq_zero_iff_mem, map_ofNat]

/-- Over `ℤ`, a height-one place is dyadic exactly when it owns the prime two. -/
theorem isDyadic_iff_eq_two {p : ℕ} (hp : p.Prime) (v : HeightOneSpectrum ℤ)
    (hv : v.asIdeal = Ideal.span {(p : ℤ)}) :
    IsDyadic v ↔ p = 2 := by
  rw [IsDyadic, hv, Ideal.mem_span_singleton]
  constructor
  · intro h
    refine (Nat.prime_dvd_prime_iff_eq hp Nat.prime_two).mp ?_
    exact_mod_cast h
  · rintro rfl
    exact dvd_refl _

end DyadicPlace

/-- Completion of integral lattices over the dyadic integers. -/
noncomputable def completeIntegralAtTwo :
    IntegralLatticeCat ℤ ⥤ IntegralLatticeCat ℤ_[2] :=
  completeIntegralAtPrime 2

/-- Completion of finite integral lattices over the dyadic integers. -/
noncomputable def completeFiniteIntegralAtTwo :
    FiniteProjectiveLatticeCat ℤ ℤ ⥤
      FiniteProjectiveLatticeCat ℤ_[2] ℤ_[2] :=
  completeFiniteIntegralAtPrime 2

/-- Extension of integral lattices to the dyadic field. -/
noncomputable def extendIntegralToTwoAdicField :
    IntegralLatticeCat ℤ ⥤ IntegralLatticeCat ℚ_[2] :=
  extendIntegralToPadicField 2

/-- Extension of finite integral lattices to the dyadic field. -/
noncomputable def extendFiniteIntegralToTwoAdicField :
    FiniteProjectiveLatticeCat ℤ ℤ ⥤
      FiniteProjectiveLatticeCat ℚ_[2] ℚ_[2] :=
  extendFiniteIntegralToPadicField 2

section LatticeType

variable (R : Type u) [CommRing R] [IsDomain R]

/-- A unimodular lattice has type II when its norms lie in the ideal generated by two. -/
def IsTypeII (L : IntegralLatticeCat R) : Prop :=
  IsUnimodular R L ∧ IsIEven L (Ideal.span {(2 : R)})

/-- A unimodular lattice has type I when it is not of type II. -/
def IsTypeI (L : IntegralLatticeCat R) : Prop :=
  IsUnimodular R L ∧ ¬IsIEven L (Ideal.span {(2 : R)})

/-- A unimodular lattice has exactly one of the two types. -/
theorem isTypeI_or_isTypeII (L : IntegralLatticeCat R) (h : IsUnimodular R L) :
    IsTypeI R L ∨ IsTypeII R L := by
  by_cases he : IsIEven L (Ideal.span {(2 : R)})
  · exact Or.inr ⟨h, he⟩
  · exact Or.inl ⟨h, he⟩

end LatticeType

end LeanCategories.Lattices.Valued
