/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import LeanCategories.Lattices.Valued.Involution
public import Mathlib.CategoryTheory.Action.Basic
public import Mathlib.GroupTheory.Subgroup.Centralizer
public import Mathlib.RepresentationTheory.Coinvariants
public import Mathlib.RepresentationTheory.Invariants

/-!
# Equivariant formed lattices

A `G`-lattice is a `G`-object in the lattice category. The carrier representation,
invariants, coinvariants, centralizer, and normalizer come from this one action.
-/

@[expose] public section

noncomputable section

open CategoryTheory
open LeanCategories.Modules.Bilinear.Valued

namespace LeanCategories.Lattices.Valued

universe u

variable (R G : Type u) [CommRing R] [Group G]

/-- Finite projective `G`-lattices as `G`-objects in the lattice category. -/
abbrev EquivariantLatticeCat := Action (FiniteProjectiveLatticeCat R R) G

namespace EquivariantLatticeCat

/-- The carrier representation of an equivariant lattice. -/
def carrierRepresentation (L : EquivariantLatticeCat R G) :
    Representation R G L.V.obj.obj.carrier where
  toFun g := BilinModuleCat.underlyingMap (L.ρ g).hom.hom
  map_one' := by
    ext x
    change BilinModuleCat.underlyingMap (L.ρ 1).hom.hom x = x
    rw [L.ρ.map_one]
    rfl
  map_mul' g h := by
    ext x
    change BilinModuleCat.underlyingMap (L.ρ (g * h)).hom.hom x =
      BilinModuleCat.underlyingMap (L.ρ g).hom.hom
        (BilinModuleCat.underlyingMap (L.ρ h).hom.hom x)
    rw [L.ρ.map_mul]
    rfl

/-- The invariant carrier of an equivariant lattice. -/
abbrev invariants (L : EquivariantLatticeCat R G) :=
  (carrierRepresentation R G L).invariants

/-- The coinvariant carrier of an equivariant lattice. -/
abbrev Coinvariants (L : EquivariantLatticeCat R G) :=
  (carrierRepresentation R G L).Coinvariants

/-- The formed-module isomorphism supplied by one element of the group action. -/
def formedIso (L : EquivariantLatticeCat R G) (g : G) :
    L.V.obj.obj ≅ L.V.obj.obj :=
  (ObjectProperty.ι (isLattice R R)).mapIso <|
    (ObjectProperty.ι (isFiniteProjectiveLattice R R)).mapIso (L.ρAut g)

/-- The group action as a homomorphism into the lattice orthogonal group. -/
def orthogonalRepresentation (L : EquivariantLatticeCat R G) :
    G →* OrthogonalGroup L.V.obj where
  toFun g :=
    ⟨BilinModuleCat.linearEquivOfIso (formedIso R G L g),
      BilinModuleCat.linearEquivOfIso_pairing (formedIso R G L g)⟩
  map_one' := by
    ext x
    change BilinModuleCat.underlyingMap (L.ρ 1).hom.hom x = x
    rw [L.ρ.map_one]
    rfl
  map_mul' g h := by
    ext x
    change BilinModuleCat.underlyingMap (L.ρ (g * h)).hom.hom x =
      BilinModuleCat.underlyingMap (L.ρ g).hom.hom
        (BilinModuleCat.underlyingMap (L.ρ h).hom.hom x)
    rw [L.ρ.map_mul]
    rfl

/-- The subgroup of the orthogonal group generated by the given `G`-action. -/
def actionImage (L : EquivariantLatticeCat R G) :
    Subgroup (OrthogonalGroup L.V.obj) :=
  (orthogonalRepresentation R G L).range

/-- The centralizer of the `G`-action in the lattice orthogonal group. -/
def orthogonalCentralizer (L : EquivariantLatticeCat R G) :
    Subgroup (OrthogonalGroup L.V.obj) :=
  Subgroup.centralizer (actionImage R G L)

/-- The normalizer of the `G`-action in the lattice orthogonal group. -/
def orthogonalNormalizer (L : EquivariantLatticeCat R G) :
    Subgroup (OrthogonalGroup L.V.obj) :=
  Subgroup.normalizer (actionImage R G L)

/-- An element of order at most two in a group action gives the existing involution structure. -/
def involutionOfElement (L : EquivariantLatticeCat R G) (g : G)
    (hg : g * g = 1) : Involution L.V.obj where
  element := orthogonalRepresentation R G L g
  involutive := by
    rw [← (orthogonalRepresentation R G L).map_mul, hg,
      (orthogonalRepresentation R G L).map_one]

end EquivariantLatticeCat

end LeanCategories.Lattices.Valued
