/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import LeanCategories.Lattices.Valued.Constructions
public import LeanCategories.Lattices.Valued.DeterminantLine
public import Mathlib.LinearAlgebra.ExteriorPower.Basis

/-!
# Fitting ideals of discriminant modules

The discriminant module of an integral lattice is the cokernel of the adjoint map `L → L♯`.
That map is a square presentation of the cokernel, so the zeroth Fitting ideal of the
discriminant module is the ideal generated by the top minors of the adjoint. Without a basis
the top minor is the determinant of the adjoint, that is the induced map
`determinantLine L → determinantDualLine L`. Its image is a submodule of a line, not an ideal,
so we pair it against all linear functionals on that line.

Mathlib has no Fitting ideal for modules, so the definition here follows the standard
presentation-by-minors account: Eisenbud, *Commutative Algebra with a View Toward Algebraic
Geometry*, section 20.2, and Stacks Project tag 07Z6.
-/

@[expose] public section

open CategoryTheory
open scoped Matrix TensorProduct

namespace LeanCategories.Lattices.Valued

universe u

variable {R : Type u} [CommRing R] [IsDomain R]

namespace FiniteProjectiveLatticeCat

/-- The zeroth Fitting ideal of the discriminant module of a lattice. It is generated by the
values of the linear functionals on the dual determinant line at the image of the determinant
of the adjoint map. -/
noncomputable def fittingDiscriminantIdeal (L : FiniteProjectiveLatticeCat R R) : Ideal R :=
  Ideal.span {r : R | ∃ (φ : Module.Dual R L.determinantDualLine)
    (x : L.determinantLine), φ (L.determinantAdjoint.hom x) = r}

/-- Forget the finite-projective property on an isomorphism of lattices. -/
private noncomputable def fittingLatticeIso
    {L M : FiniteProjectiveLatticeCat R R} (e : L ≅ M) : L.obj ≅ M.obj :=
  (ObjectProperty.ι (isFiniteProjectiveLattice R R)).mapIso e

omit [IsDomain R] in
/-- The carrier and contragredient maps commute with the adjoint maps. -/
private theorem fitting_adjoint_naturality
    {L M : FiniteProjectiveLatticeCat R R} (e : L ≅ M) :
    ModuleCat.ofHom L.obj.obj.adjoint ≫
        (discriminantValueDualEquiv (fittingLatticeIso e)).toModuleIso.hom =
      ((finiteProjectiveForget R R).mapIso e).hom ≫
        ModuleCat.ofHom M.obj.obj.adjoint := by
  apply ModuleCat.hom_ext
  apply LinearMap.ext
  intro x
  exact discriminantValueDualEquiv_adjoint (fittingLatticeIso e) x

/-- One half of the invariance of the Fitting ideal under lattice isomorphism. -/
private theorem fittingDiscriminantIdeal_le_of_iso
    {L M : FiniteProjectiveLatticeCat R R} (e : L ≅ M) :
    L.fittingDiscriminantIdeal ≤ M.fittingDiscriminantIdeal := by
  unfold fittingDiscriminantIdeal determinantAdjoint determinantDualLine determinantLine
  have hr : M.genericRank = L.genericRank := by
    unfold genericRank
    exact (congrFun (Module.rankAtStalk_eq_of_equiv
      ((finiteProjectiveForget R R).mapIso e).toLinearEquiv) ⊥).symm
  rw [hr]
  let F := ModuleCat.exteriorPower.functor R L.genericRank
  let carrierE := F.mapIso ((finiteProjectiveForget R R).mapIso e)
  let dualE := F.mapIso
    (discriminantValueDualEquiv (fittingLatticeIso e)).toModuleIso
  have hsquare :
      F.map (ModuleCat.ofHom L.obj.obj.adjoint) ≫ dualE.hom =
        carrierE.hom ≫ F.map (ModuleCat.ofHom M.obj.obj.adjoint) := by
    change F.map (ModuleCat.ofHom L.obj.obj.adjoint) ≫
        F.map (discriminantValueDualEquiv (fittingLatticeIso e)).toModuleIso.hom =
      F.map ((finiteProjectiveForget R R).mapIso e).hom ≫
        F.map (ModuleCat.ofHom M.obj.obj.adjoint)
    rw [← F.map_comp, ← F.map_comp]
    exact congrArg F.map (fitting_adjoint_naturality e)
  rw [Ideal.span_le]
  rintro r ⟨φ, x, rfl⟩
  refine Ideal.subset_span ⟨φ ∘ₗ dualE.toLinearEquiv.symm.toLinearMap,
    carrierE.toLinearEquiv x, ?_⟩
  simp only [LinearMap.comp_apply]
  refine congrArg φ ?_
  exact dualE.toLinearEquiv.symm_apply_eq.mpr
    (ConcreteCategory.congr_hom hsquare x).symm

/-- The Fitting ideal of the discriminant module is invariant under lattice isomorphism. -/
theorem fittingDiscriminantIdeal_eq_of_iso
    {L M : FiniteProjectiveLatticeCat R R} (e : L ≅ M) :
    L.fittingDiscriminantIdeal = M.fittingDiscriminantIdeal :=
  le_antisymm (fittingDiscriminantIdeal_le_of_iso e)
    (fittingDiscriminantIdeal_le_of_iso e.symm)

omit [IsDomain R] in
/-- In an invertible module a functional value moves between its two arguments. This is the
rank-one identity behind the comparison of Fitting and annihilator ideals. -/
private theorem smul_dual_comm {Q : Type u} [AddCommGroup Q] [Module R Q]
    [Module.Invertible R Q] (φ : Module.Dual R Q) (a b : Q) :
    φ a • b = φ b • a := by
  have h : ((TensorProduct.lid R Q).toLinearMap ∘ₗ φ.rTensor Q) (a ⊗ₜ[R] b) =
      ((TensorProduct.lid R Q).toLinearMap ∘ₗ φ.rTensor Q) (b ⊗ₜ[R] a) := by
    rw [Module.Invertible.tmul_comm]
  simpa using h

/-- When the dual determinant line is invertible, the zeroth Fitting ideal of the discriminant
module is the annihilator of the determinant-line cokernel. -/
theorem fittingDiscriminantIdeal_eq_intrinsic (L : FiniteProjectiveLatticeCat R R)
    [Module.Invertible R L.determinantDualLine] :
    L.fittingDiscriminantIdeal = L.intrinsicDiscriminantIdeal := by
  apply le_antisymm
  · rw [fittingDiscriminantIdeal, Ideal.span_le]
    rintro r ⟨φ, x, rfl⟩
    rw [SetLike.mem_coe, intrinsicDiscriminantIdeal, Module.mem_annihilator]
    intro m
    induction m using Submodule.Quotient.induction_on with
    | H y =>
      rw [← Submodule.Quotient.mk_smul, Submodule.Quotient.mk_eq_zero]
      rw [smul_dual_comm φ (L.determinantAdjoint.hom x) y]
      exact ⟨φ y • x, by rw [map_smul]⟩
  · intro r hr
    rw [intrinsicDiscriminantIdeal, Module.mem_annihilator] at hr
    have hmem : ∀ y : L.determinantDualLine,
        r • y ∈ LinearMap.range L.determinantAdjoint.hom := by
      intro y
      have := hr (Submodule.Quotient.mk y)
      rwa [← Submodule.Quotient.mk_smul, Submodule.Quotient.mk_eq_zero] at this
    have key : ∀ t : Module.Dual R L.determinantDualLine ⊗[R] L.determinantDualLine,
        r * contractLeft R L.determinantDualLine t ∈ L.fittingDiscriminantIdeal := by
      intro t
      induction t using TensorProduct.induction_on with
      | zero => simp
      | tmul φ y =>
        obtain ⟨x, hx⟩ := hmem y
        refine Ideal.subset_span ⟨φ, x, ?_⟩
        rw [hx, contractLeft_apply, map_smul, smul_eq_mul, mul_comm]
      | add s t hs ht => rw [map_add, mul_add]; exact Ideal.add_mem _ hs ht
    obtain ⟨u, hu⟩ := (Module.Invertible.bijective (R := R)
      (M := (L.determinantDualLine : Type u))).surjective 1
    simpa [hu] using key u

omit [IsDomain R] in
/-- The top exterior power of a map between free modules of the same finite rank scales the top
wedge of a source basis by the determinant of the matrix of the map. -/
private theorem map_ιMulti_family_top {I : Type u} [Fintype I] [LinearOrder I]
    {M N : Type u} [AddCommGroup M] [Module R M] [AddCommGroup N] [Module R N]
    (b : Module.Basis I R M) (c : Module.Basis I R N) (f : M →ₗ[R] N)
    (s : Set.powersetCard I (Fintype.card I)) :
    exteriorPower.map (Fintype.card I) f
        (exteriorPower.ιMulti_family R (Fintype.card I) b s) =
      (LinearMap.toMatrix b c f).det •
        exteriorPower.ιMulti_family R (Fintype.card I) c s := by
  classical
  have huniq : ∀ t : Set.powersetCard I (Fintype.card I), t = s := fun t =>
    Subtype.ext (((Finset.card_eq_iff_eq_univ _).mp t.prop).trans
      ((Finset.card_eq_iff_eq_univ _).mp s.prop).symm)
  have hbij : Function.Bijective
      ((Set.powersetCard.ofFinEmbEquiv.symm s : Fin (Fintype.card I) ↪o I) :
        Fin (Fintype.card I) → I) :=
    (Fintype.bijective_iff_injective_and_card _).mpr
      ⟨(Set.powersetCard.ofFinEmbEquiv.symm s).injective, by simp⟩
  refine (Module.Basis.exteriorPower (n := Fintype.card I) c).repr.injective ?_
  ext t
  rw [huniq t, map_smul, Finsupp.smul_apply, smul_eq_mul,
    exteriorPower.basis_repr_self, mul_one, exteriorPower.basis_repr_apply,
    exteriorPower.ιMulti_family, exteriorPower.map_apply_ιMulti,
    exteriorPower.ιMultiDual_apply_ιMulti]
  have hmat : (Matrix.of fun i j =>
      c.coord (Set.powersetCard.ofFinEmbEquiv.symm s j)
        ((f ∘ b ∘ Set.powersetCard.ofFinEmbEquiv.symm s) i)) =
      ((LinearMap.toMatrix b c f).submatrix (Equiv.ofBijective _ hbij)
        (Equiv.ofBijective _ hbij))ᵀ := by
    ext i j
    simp [LinearMap.toMatrix_apply, Module.Basis.coord_apply]
  rw [hmat, Matrix.det_transpose, Matrix.det_submatrix_equiv_self]

/-- For a lattice with a finite basis, the zeroth Fitting ideal of the discriminant module is
generated by the Gram determinant of that basis. -/
theorem fittingDiscriminantIdeal_eq_determinantIdeal {I : Type u} [Fintype I] [LinearOrder I]
    (L : FiniteProjectiveLatticeCat R R) (b : Module.Basis I R L.obj.obj.carrier) :
    L.fittingDiscriminantIdeal = determinantIdeal L.obj b := by
  classical
  letI : Module.Free R L.obj.obj.carrier := Module.Free.of_basis b
  letI : Module.Finite R L.obj.obj.carrier := L.property
  have hrank : L.genericRank = Fintype.card I := by
    simp [genericRank, localRank, Module.finrank_eq_card_basis b]
  set n := Fintype.card I with hn
  set sTop : Set.powersetCard I n :=
    ⟨Finset.univ, by simp [Set.powersetCard, hn]⟩ with hsTop
  have huniq : ∀ t : Set.powersetCard I n, t = sTop := fun t =>
    Subtype.ext (((Finset.card_eq_iff_eq_univ _).mp t.prop).trans
      ((Finset.card_eq_iff_eq_univ _).mp sTop.prop).symm)
  letI : Unique (Set.powersetCard I n) := ⟨⟨sTop⟩, huniq⟩
  set v := exteriorPower.ιMulti_family R n (b : I → L.obj.obj.carrier) sTop with hv
  set w := exteriorPower.ιMulti_family R n
    (b.dualBasis : I → Module.Dual R L.obj.obj.carrier) sTop with hw
  have key : exteriorPower.map n L.obj.obj.adjoint v = determinant L.obj b • w := by
    rw [hv, hw, map_ιMulti_family_top b b.dualBasis L.obj.obj.adjoint sTop,
      adjoint_toMatrix_eq_gramMatrix L.obj b]
    rfl
  have hspan : ∀ x : ⋀[R]^n L.obj.obj.carrier, ∃ a : R, x = a • v := by
    intro x
    have hx : x ∈ Submodule.span R
        (Set.range (Module.Basis.exteriorPower (n := n) b)) := by
      rw [(Module.Basis.exteriorPower (n := n) b).span_eq]
      trivial
    rw [Set.range_unique, exteriorPower.basis_apply, Submodule.mem_span_singleton] at hx
    obtain ⟨a, ha⟩ := hx
    exact ⟨a, ha.symm⟩
  have hcoord : (Module.Basis.exteriorPower (n := n) b.dualBasis).coord sTop w = 1 := by
    rw [Module.Basis.coord_apply, hw, exteriorPower.basis_repr_self]
  unfold fittingDiscriminantIdeal determinantAdjoint determinantDualLine determinantLine
  rw [hrank, determinantIdeal]
  apply le_antisymm
  · rw [Ideal.span_le]
    rintro r ⟨φ, x, rfl⟩
    obtain ⟨a, rfl⟩ := hspan x
    let ψ : (⋀[R]^n (Module.Dual R L.obj.obj.carrier)) →ₗ[R] R := φ
    refine Ideal.mem_span_singleton.mpr ⟨a * ψ w, ?_⟩
    change ψ (exteriorPower.map n L.obj.obj.adjoint (a • v)) = _
    rw [map_smul, key, map_smul, map_smul, smul_eq_mul, smul_eq_mul]
    ring
  · rw [Ideal.span_le, Set.singleton_subset_iff]
    let ψ : (⋀[R]^n (Module.Dual R L.obj.obj.carrier)) →ₗ[R] R :=
      (Module.Basis.exteriorPower (n := n) b.dualBasis).coord sTop
    have hψ : ψ w = 1 := hcoord
    refine Ideal.subset_span ⟨ψ, v, ?_⟩
    change ψ (exteriorPower.map n L.obj.obj.adjoint v) = _
    rw [key, map_smul, hψ, smul_eq_mul, mul_one]

end FiniteProjectiveLatticeCat

end LeanCategories.Lattices.Valued
