/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import LeanCategories.Lattices.Valued.JordanLayer
public import Mathlib.LinearAlgebra.Isomorphisms
public import Mathlib.LinearAlgebra.Quotient.Pi

@[expose] public section

open CategoryTheory
open LeanCategories.Modules.Bilinear.Valued
open scoped Pointwise

namespace LeanCategories.Lattices.Valued

universe u

variable {R : Type u} [CommRing R]

section PiReduction

variable {ι : Type} [Fintype ι] [DecidableEq ι]
variable {M : ι → Type u} [∀ i, AddCommGroup (M i)] [∀ i, Module R (M i)]

omit [Fintype ι] [DecidableEq ι] in
/-- Scaling a product of modules scales each factor. -/
theorem smul_top_pi (a : R) :
    a • (⊤ : Submodule R ((i : ι) → M i)) =
      Submodule.pi Set.univ fun i ↦ a • (⊤ : Submodule R (M i)) := by
  refine Submodule.ext fun x ↦ ⟨fun hx ↦ Submodule.mem_pi.mpr fun i _ ↦ ?_, fun hx ↦ ?_⟩
  · obtain ⟨y, -, rfl⟩ := (Submodule.mem_smul_pointwise_iff_exists _ _ _).mp hx
    exact (Submodule.mem_smul_pointwise_iff_exists _ _ _).mpr ⟨y i, Submodule.mem_top, rfl⟩
  · choose y _ hy using fun i ↦ (Submodule.mem_smul_pointwise_iff_exists _ _ _).mp
      (Submodule.mem_pi.mp hx i (Set.mem_univ i))
    exact (Submodule.mem_smul_pointwise_iff_exists _ _ _).mpr
      ⟨y, Submodule.mem_top, funext hy⟩

/-- Reducing a product of modules by a ring element reduces each factor.

The quotient of a product by a product of submodules is the product of the quotients, and
the multiples of a ring element form such a product. -/
noncomputable def quotSMulTopPiEquiv (a : R) :
    QuotSMulTop a ((i : ι) → M i) ≃ₗ[R] (i : ι) → QuotSMulTop a (M i) :=
  (Submodule.quotEquivOfEq _ _ (smul_top_pi a)).trans (Submodule.quotientPi _)

end PiReduction

section ResidueDimension

variable (a : R)

/-- The residue ring acts on a reduced module through the ring. -/
instance instIsScalarTowerQuotSMulTop (M : Type u) [AddCommGroup M] [Module R M] :
    IsScalarTower R (R ⧸ Ideal.span {a}) (QuotSMulTop a M) :=
  IsScalarTower.of_algebraMap_smul fun _ _ ↦ rfl

/-- Isomorphic modules over the residue ring have equal residue dimension.

The isomorphism is only linear over the ring, but the residue ring is a quotient of it. -/
theorem finrank_residue_eq_of_linearEquiv {A B : Type u} [AddCommGroup A] [Module R A]
    [Module (R ⧸ Ideal.span {a}) A] [IsScalarTower R (R ⧸ Ideal.span {a}) A]
    [AddCommGroup B] [Module R B] [Module (R ⧸ Ideal.span {a}) B]
    [IsScalarTower R (R ⧸ Ideal.span {a}) B] (e : A ≃ₗ[R] B) :
    Module.finrank (R ⧸ Ideal.span {a}) A = Module.finrank (R ⧸ Ideal.span {a}) B :=
  (LinearEquiv.extendScalarsOfSurjective Ideal.Quotient.mk_surjective e).finrank_eq

/-- Reduction by a ring element has an isomorphism-invariant residue dimension. -/
theorem finrank_quotSMulTop_congr {A B : Type u} [AddCommGroup A] [Module R A]
    [AddCommGroup B] [Module R B] (e : A ≃ₗ[R] B) :
    Module.finrank (R ⧸ Ideal.span {a}) (QuotSMulTop a A) =
      Module.finrank (R ⧸ Ideal.span {a}) (QuotSMulTop a B) :=
  finrank_residue_eq_of_linearEquiv a (QuotSMulTop.congr a e)

end ResidueDimension

section ResidueField

variable [IsDomain R] [IsDiscreteValuationRing R]

/-- The ideal generated by a uniformizer is maximal. -/
theorem isMaximal_span_singleton {π : R} (hπ : Irreducible π) :
    (Ideal.span {π}).IsMaximal := by
  rw [← (IsDiscreteValuationRing.irreducible_iff_uniformizer π).mp hπ]
  exact IsLocalRing.maximalIdeal.isMaximal R

/-- Reducing a free module by a uniformizer power and then by the uniformizer.

A nonzero power leaves the residue reduction of the module, of dimension the rank. The
zero power leaves nothing. -/
theorem finrank_quotSMulTop_quotient_pow {π : R} (hπ : Irreducible π) (M : Type u)
    [AddCommGroup M] [Module R M] [Module.Free R M] (c : ℕ) :
    Module.finrank (R ⧸ Ideal.span {π})
        (QuotSMulTop π (M ⧸ (π ^ c) • (⊤ : Submodule R M))) =
      if c = 0 then 0 else Module.finrank R M := by
  rcases Nat.eq_zero_or_pos c with rfl | hc
  · haveI := nontrivial_quotient_span_singleton hπ
    rw [if_pos rfl, pow_zero, one_smul]
    exact Module.finrank_zero_of_subsingleton
  · obtain ⟨d, rfl⟩ : ∃ d, c = d + 1 := ⟨c - 1, by omega⟩
    rw [if_neg (Nat.succ_ne_zero d)]
    have hle : (π ^ (d + 1)) • (⊤ : Submodule R M) ≤ π • (⊤ : Submodule R M) := by
      intro x hx
      obtain ⟨y, -, rfl⟩ := (Submodule.mem_smul_pointwise_iff_exists _ _ _).mp hx
      exact (Submodule.mem_smul_pointwise_iff_exists _ _ _).mpr
        ⟨π ^ d • y, Submodule.mem_top, by rw [smul_smul, ← pow_succ']⟩
    have hmap : Submodule.map ((π ^ (d + 1)) • (⊤ : Submodule R M)).mkQ (π • ⊤)
        = π • (⊤ : Submodule R (M ⧸ (π ^ (d + 1)) • (⊤ : Submodule R M))) := by
      rw [Submodule.map_pointwise_smul, Submodule.map_top, Submodule.range_mkQ]
    have e : QuotSMulTop π (M ⧸ (π ^ (d + 1)) • (⊤ : Submodule R M)) ≃ₗ[R] QuotSMulTop π M :=
      (Submodule.quotEquivOfEq _ _ hmap.symm).trans
        (Submodule.quotientQuotientEquivQuotient _ _ hle)
    rw [finrank_residue_eq_of_linearEquiv π e, finrank_quotSMulTop hπ M]

end ResidueField

section LayerPower

variable [IsDomain R] [IsDiscreteValuationRing R]

omit [IsDiscreteValuationRing R] in
/-- The uniformizer multiples of a modular lattice pair one matching power deeper. -/
theorem smul_top_le_layerSubmodule (L : IntegralLatticeCat R) (π : R) (e j : ℕ)
    (hmod : IsIModular R L (Ideal.span {π ^ e})) :
    (π ^ j) • (⊤ : Submodule R L.obj.carrier) ≤
      layerSubmodule L (Ideal.span {π ^ (e + j)}) := by
  rw [← Submodule.ideal_span_singleton_smul]
  refine Submodule.smul_le.mpr fun r hr m _ ↦ (mem_layerSubmodule_iff _ _ _).mpr fun y ↦ ?_
  rw [BilinModuleCat.pairing_smul_left, smul_eq_mul, Ideal.mem_span_singleton, pow_add,
    mul_comm (π ^ e)]
  exact mul_dvd_mul (Ideal.mem_span_singleton.mp hr)
    (Ideal.mem_span_singleton.mp (scaleIdeal_le_of_isIModular L _ hmod
      (pairing_mem_scaleIdeal L m y)))

/-- The layer of a `π ^ e`-modular lattice at `π ^ (e + j)` is the `π ^ j` multiple.

This is the filtration of a modular lattice: each further power of the uniformizer in the
pairing costs exactly one power of the uniformizer in the vector. -/
theorem layerSubmodule_add_of_isIModular (L : IntegralLatticeCat R) (π : R)
    (hπ : Irreducible π) (e : ℕ) (hmod : IsIModular R L (Ideal.span {π ^ e})) (j : ℕ) :
    layerSubmodule L (Ideal.span {π ^ (e + j)}) =
      (π ^ j) • (⊤ : Submodule R L.obj.carrier) := by
  induction j with
  | zero =>
    rw [add_zero, pow_zero, one_smul]
    exact layerSubmodule_eq_top_of_scaleIdeal_le L _ (scaleIdeal_le_of_isIModular L _ hmod)
  | succ j ih =>
    refine le_antisymm (fun x hx ↦ ?_) (smul_top_le_layerSubmodule L π e (j + 1) hmod)
    have hx1 : x ∈ layerSubmodule L (Ideal.span {π ^ (e + 1)}) :=
      (mem_layerSubmodule_iff _ _ _).mpr fun y ↦
        Ideal.span_singleton_le_span_singleton.mpr (pow_dvd_pow π (by omega))
          ((mem_layerSubmodule_iff _ _ _).mp hx y)
    obtain ⟨w, rfl⟩ := exists_smul_of_mem_layerSubmodule L π hπ e hmod hx1
    have hw : w ∈ layerSubmodule L (Ideal.span {π ^ (e + j)}) := by
      refine (mem_layerSubmodule_iff _ _ _).mpr fun y ↦ ?_
      have h := (mem_layerSubmodule_iff _ _ _).mp hx y
      rw [BilinModuleCat.pairing_smul_left, smul_eq_mul, Ideal.mem_span_singleton] at h
      obtain ⟨c, hc⟩ := h
      refine Ideal.mem_span_singleton.mpr ⟨c, mul_left_cancel₀ hπ.ne_zero ?_⟩
      rw [hc, show e + (j + 1) = 1 + (e + j) by omega, pow_add, pow_one, mul_assoc]
    rw [ih] at hw
    obtain ⟨v, -, hv⟩ := (Submodule.mem_smul_pointwise_iff_exists _ _ _).mp hw
    refine (Submodule.mem_smul_pointwise_iff_exists _ _ _).mpr ⟨v, Submodule.mem_top, ?_⟩
    rw [← hv, smul_smul, ← pow_succ']

/-- The layer of a `π ^ e`-modular lattice at any uniformizer power.

Below the modularity exponent the whole lattice pairs into the ideal; above it, only the
matching uniformizer multiples do. -/
theorem layerSubmodule_pow_of_isIModular (L : IntegralLatticeCat R) (π : R)
    (hπ : Irreducible π) (e : ℕ) (hmod : IsIModular R L (Ideal.span {π ^ e})) (k : ℕ) :
    layerSubmodule L (Ideal.span {π ^ k}) =
      (π ^ (k - e)) • (⊤ : Submodule R L.obj.carrier) := by
  rcases le_or_gt k e with hke | hke
  · rw [Nat.sub_eq_zero_of_le hke, pow_zero, one_smul]
    refine layerSubmodule_eq_top_of_scaleIdeal_le L _
      ((scaleIdeal_le_of_isIModular L _ hmod).trans ?_)
    exact Ideal.span_singleton_le_span_singleton.mpr (pow_dvd_pow π hke)
  · have h := layerSubmodule_add_of_isIModular L π hπ e hmod (k - e)
    rwa [show e + (k - e) = k by omega] at h

end LayerPower

section JordanFiltration

variable [IsDomain R] [IsDiscreteValuationRing R]
variable {L : FiniteProjectiveLatticeCat R R} {π : R} {n : ℕ}

/-- The residue dimension of the lattice modulo its layer at `π ^ k` and the uniformizer.

This counts the generators of the quotient of the lattice by its layer, so it is the total
rank of the Jordan components of exponent below `k`. -/
noncomputable def layerJump (L : FiniteProjectiveLatticeCat R R) (π : R) (k : ℕ) : ℕ :=
  Module.finrank (R ⧸ Ideal.span {π})
    (QuotSMulTop π (L.obj.obj.carrier ⧸ layerSubmodule L.obj (Ideal.span {π ^ k})))

namespace JordanDecomposition

/-- A Jordan decomposition can be restated for any other uniformizer.

Uniformizers of a discrete valuation ring are associated, so they generate the same
powers and record the same modularity. -/
def changeUniformizer (J : JordanDecomposition L π n) {ϖ : R} (hϖ : Irreducible ϖ) :
    JordanDecomposition L ϖ n where
  uniformizer_isIrreducible := hϖ
  component := J.component
  exponent := J.exponent
  component_isModular i := by
    have h : Ideal.span {ϖ ^ J.exponent i} = Ideal.span {π ^ J.exponent i} :=
      Ideal.span_singleton_eq_span_singleton.mpr
        (Associated.pow_pow (IsDiscreteValuationRing.associated_of_irreducible R hϖ
          J.uniformizer_isIrreducible))
    rw [h]
    exact J.component_isModular i
  component_nontrivial := J.component_nontrivial
  exponent_strictMono := J.exponent_strictMono
  decomposition := J.decomposition

@[simp]
theorem changeUniformizer_exponent (J : JordanDecomposition L π n) {ϖ : R}
    (hϖ : Irreducible ϖ) : (J.changeUniformizer hϖ).exponent = J.exponent := rfl

@[simp]
theorem changeUniformizer_component (J : JordanDecomposition L π n) {ϖ : R}
    (hϖ : Irreducible ϖ) : (J.changeUniformizer hϖ).component = J.component := rfl

@[simp]
theorem changeUniformizer_invariants (J : JordanDecomposition L π n) {ϖ : R}
    (hϖ : Irreducible ϖ) : (J.changeUniformizer hϖ).invariants = J.invariants := rfl

/-- The layer of a decomposed lattice is the product of the layers of its components. -/
theorem layerSubmodule_decomposition (J : JordanDecomposition L π n) (k : ℕ) :
    layerSubmodule (finiteProjectiveIndexedOrthogonalSum J.component).obj
        (Ideal.span {π ^ k}) =
      Submodule.pi Set.univ fun i ↦ (π ^ (k - J.exponent i)) •
        (⊤ : Submodule R (J.component i).obj.obj.carrier) := by
  rw [layerSubmodule_finiteProjectiveIndexedOrthogonalSum]
  exact congrArg (Submodule.pi Set.univ) (funext fun i ↦
    layerSubmodule_pow_of_isIModular _ π J.uniformizer_isIrreducible _
      (J.component_isModular i) k)

/-- The layer jump counts the ranks of the components of exponent below the cut.

This is the successive-quotient computation: a component of exponent `e` contributes its
whole rank once `k` passes `e`, and nothing before. -/
theorem layerJump_eq (J : JordanDecomposition L π n) (k : ℕ) :
    layerJump L π k = ∑ i, if J.exponent i < k then (J.component i).rank else 0 := by
  classical
  haveI := isMaximal_span_singleton J.uniformizer_isIrreducible
  letI : Field (R ⧸ Ideal.span {π}) := Ideal.Quotient.field _
  letI (i : Fin n) : Module.Free R (J.component i).obj.obj.carrier :=
    (J.component i).carrier_free
  letI (i : Fin n) : Module.Finite R (J.component i).obj.obj.carrier := (J.component i).property
  set p : (i : Fin n) → Submodule R (J.component i).obj.obj.carrier := fun i ↦
    (π ^ (k - J.exponent i)) • (⊤ : Submodule R (J.component i).obj.obj.carrier) with hp
  have e1 : (((i : Fin n) → (J.component i).obj.obj.carrier) ⧸ Submodule.pi Set.univ p) ≃ₗ[R]
      (L.obj.obj.carrier ⧸ layerSubmodule L.obj (Ideal.span {π ^ k})) :=
    (Submodule.quotEquivOfEq _ _ (J.layerSubmodule_decomposition k).symm).trans
      (Submodule.Quotient.equiv _ _ (finiteProjectiveLatticeLinearEquiv J.decomposition)
        (layerSubmodule_map_of_iso J.decomposition _))
  have e2 : QuotSMulTop π (((i : Fin n) → (J.component i).obj.obj.carrier) ⧸
        Submodule.pi Set.univ p) ≃ₗ[R]
      ((i : Fin n) → QuotSMulTop π ((J.component i).obj.obj.carrier ⧸ p i)) :=
    (QuotSMulTop.congr π (Submodule.quotientPi p)).trans (quotSMulTopPiEquiv π)
  haveI (i : Fin n) : Module.Finite (R ⧸ Ideal.span {π})
      (QuotSMulTop π ((J.component i).obj.obj.carrier ⧸ p i)) :=
    Module.Finite.of_restrictScalars_finite R _ _
  haveI : IsScalarTower R (R ⧸ Ideal.span {π})
      ((i : Fin n) → QuotSMulTop π ((J.component i).obj.obj.carrier ⧸ p i)) :=
    IsScalarTower.of_algebraMap_smul fun _ _ ↦ funext fun _ ↦ rfl
  have hjump : layerJump L π k =
      ∑ i, Module.finrank (R ⧸ Ideal.span {π})
        (QuotSMulTop π ((J.component i).obj.obj.carrier ⧸ p i)) := by
    rw [layerJump, ← finrank_quotSMulTop_congr π e1,
      finrank_residue_eq_of_linearEquiv π e2, Module.finrank_pi_fintype]
  rw [hjump]
  refine Finset.sum_congr rfl fun i _ ↦ ?_
  rw [hp, finrank_quotSMulTop_quotient_pow J.uniformizer_isIrreducible]
  by_cases hlt : J.exponent i < k
  · rw [if_neg (by omega), if_pos hlt]
    rfl
  · rw [if_pos (by omega), if_neg hlt]

end JordanDecomposition

end JordanFiltration

section Combinatorics

variable [IsDomain R] [IsDiscreteValuationRing R]
variable {L : FiniteProjectiveLatticeCat R R} {π : R} {n : ℕ}

namespace JordanDecomposition

/-- The rank carried by the components of a given exponent. -/
noncomputable def jump (J : JordanDecomposition L π n) (v : ℕ) : ℕ :=
  ∑ i, if J.exponent i = v then (J.component i).rank else 0

/-- Each Jordan component has positive rank, since it is nonzero. -/
theorem rank_pos (J : JordanDecomposition L π n) (i : Fin n) : 0 < (J.component i).rank := by
  letI := J.component_nontrivial i
  letI : Module.Finite R (J.component i).obj.obj.carrier := (J.component i).property
  letI : Module.Free R (J.component i).obj.obj.carrier := (J.component i).carrier_free
  exact Module.finrank_pos

/-- The jump at the exponent of a component is the rank of that component. -/
theorem jump_exponent (J : JordanDecomposition L π n) (i : Fin n) :
    J.jump (J.exponent i) = (J.component i).rank := by
  refine (Finset.sum_eq_single_of_mem i (Finset.mem_univ i) fun j _ hj ↦ ?_).trans (if_pos rfl)
  exact if_neg fun h ↦ hj (J.exponent_strictMono.injective h)

/-- A nonzero jump comes from a component of that exponent. -/
theorem exists_exponent_of_jump_ne_zero (J : JordanDecomposition L π n) {v : ℕ}
    (h : J.jump v ≠ 0) : ∃ i, J.exponent i = v := by
  by_contra hcon
  exact h (Finset.sum_eq_zero fun i _ ↦ if_neg fun hi ↦ hcon ⟨i, hi⟩)

/-- Passing one exponent adds the rank carried at that exponent. -/
theorem sum_rank_lt_succ (J : JordanDecomposition L π n) (k : ℕ) :
    (∑ i, if J.exponent i < k + 1 then (J.component i).rank else 0) =
      (∑ i, if J.exponent i < k then (J.component i).rank else 0) + J.jump k := by
  rw [jump, ← Finset.sum_add_distrib]
  refine Finset.sum_congr rfl fun i _ ↦ ?_
  split_ifs <;> omega

/-- The exponent-rank pairs of a Jordan decomposition are distinct. -/
theorem invariants_nodup (J : JordanDecomposition L π n) : J.invariants.Nodup :=
  Finset.univ.nodup.map fun _ _ h ↦ J.exponent_strictMono.injective (congrArg Prod.fst h)

/-- A pair belongs to the invariants when some component realises it. -/
theorem mem_invariants_iff (J : JordanDecomposition L π n) (v r : ℕ) :
    (v, r) ∈ J.invariants ↔ ∃ i, J.exponent i = v ∧ (J.component i).rank = r := by
  simp [invariants, Prod.ext_iff]

end JordanDecomposition

/-- The multiset of exponent-rank pairs is an invariant of the lattice.

Two Jordan decompositions of the same lattice, with possibly different uniformizers and
different numbers of components, record the same invariants. The layer jumps of the
lattice determine the rank carried at each exponent, and each exponent occurs once. -/
theorem invariants_eq_of_jordanDecomposition {ϖ : R} {m : ℕ}
    (J : JordanDecomposition L π n) (K : JordanDecomposition L ϖ m) :
    J.invariants = K.invariants := by
  set K' := K.changeUniformizer J.uniformizer_isIrreducible with hK'
  have hjump : ∀ v, J.jump v = K'.jump v := by
    have hF : ∀ k, (∑ i, if J.exponent i < k then (J.component i).rank else 0) =
        ∑ j, if K'.exponent j < k then (K'.component j).rank else 0 := fun k ↦ by
      rw [← J.layerJump_eq k, K'.layerJump_eq k]
    intro v
    have h1 := hF v
    have h2 := hF (v + 1)
    rw [J.sum_rank_lt_succ v, K'.sum_rank_lt_succ v] at h2
    omega
  rw [← K.changeUniformizer_invariants J.uniformizer_isIrreducible, ← hK']
  refine (Multiset.Nodup.ext J.invariants_nodup K'.invariants_nodup).mpr fun ⟨v, r⟩ ↦ ?_
  constructor
  · intro hmem
    obtain ⟨i, hv, hr⟩ := (J.mem_invariants_iff v r).mp hmem
    have hr0 : K'.jump v ≠ 0 := by
      rw [← hjump v, ← hv, J.jump_exponent i, hr]
      exact fun h ↦ absurd (h ▸ hr ▸ J.rank_pos i) (lt_irrefl 0)
    obtain ⟨j, hj⟩ := K'.exists_exponent_of_jump_ne_zero hr0
    refine (K'.mem_invariants_iff v r).mpr ⟨j, hj, ?_⟩
    rw [← K'.jump_exponent j, hj, ← hjump v, ← hv, J.jump_exponent i, hr]
  · intro hmem
    obtain ⟨j, hv, hr⟩ := (K'.mem_invariants_iff v r).mp hmem
    have hr0 : J.jump v ≠ 0 := by
      rw [hjump v, ← hv, K'.jump_exponent j, hr]
      exact fun h ↦ absurd (h ▸ hr ▸ K'.rank_pos j) (lt_irrefl 0)
    obtain ⟨i, hi⟩ := J.exists_exponent_of_jump_ne_zero hr0
    refine (J.mem_invariants_iff v r).mpr ⟨i, hi, ?_⟩
    rw [← J.jump_exponent i, hi, hjump v, ← hv, K'.jump_exponent j, hr]

end Combinatorics

end LeanCategories.Lattices.Valued
