/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import LeanCategories.Lattices.Valued.IdealDual

@[expose] public section

open CategoryTheory
open LeanCategories.Modules.Bilinear.Valued

namespace LeanCategories.Lattices.Valued

universe u

variable (R : Type u) [CommRing R] [IsDomain R]

section RankOne

variable (L : IntegralLatticeCat R) (b : Module.Basis (Fin 1) R L.obj.carrier)

omit [IsDomain R] in
/-- Membership in the metric fractional-`I`-dual, for an arbitrary rational vector. -/
theorem mem_fractionalIdealDual_iff (I : FractionalRIdeal R) (x : RationalSpan R L) :
    x ∈ fractionalIdealDual R L I ↔
      ∀ y : L.obj.carrier, rationalizedForm R L x (toRationalSpan R L y) ∈ I := by
  rw [fractionalIdealDual, LinearMap.mem_ker, LinearMap.ext_iff]
  refine forall_congr' fun y ↦ ?_
  change fractionalIdealValueProjection R I
    (rationalizedForm R L x (toRationalSpan R L y)) = 0 ↔ _
  rw [fractionalIdealValueProjection, Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero]
  exact FractionalIdeal.mem_coe

omit [IsDomain R] in
/-- The basis vector generates the carrier of a rank-one lattice. -/
theorem exists_smul_basis (y : L.obj.carrier) : ∃ r : R, y = r • b 0 := by
  refine ⟨b.repr y 0, ?_⟩
  conv_lhs => rw [← b.sum_repr y]
  simp

omit [IsDomain R] in
/-- Every rational vector of a rank-one lattice is a scalar multiple of the basis vector. -/
theorem exists_tmul_basis (x : RationalSpan R L) :
    ∃ c : FractionRing R, x = c ⊗ₜ[R] b 0 := by
  induction x using TensorProduct.induction_on with
  | zero => exact ⟨0, (TensorProduct.zero_tmul _ _).symm⟩
  | tmul a y =>
    obtain ⟨r, rfl⟩ := exists_smul_basis R L b y
    exact ⟨r • a, (TensorProduct.smul_tmul r a (b 0)).symm⟩
  | add x y hx hy =>
    obtain ⟨c, rfl⟩ := hx
    obtain ⟨d, rfl⟩ := hy
    exact ⟨c + d, (TensorProduct.add_tmul c d (b 0)).symm⟩

omit [IsDomain R] in
/-- Coefficients of rational vectors of a rank-one lattice are unique. -/
theorem tmul_basis_left_injective {c d : FractionRing R}
    (h : c ⊗ₜ[R] b 0 = d ⊗ₜ[R] b 0) : c = d := by
  have hrepr := congrArg
    (fun x ↦ (b.baseChange (FractionRing R)).repr x 0) h
  simpa using hrepr

omit [IsDomain R] in
/-- The integral image of a rank-one lattice is the set of integral multiples of `v`. -/
theorem tmul_mem_integralImage_iff (c : FractionRing R) :
    c ⊗ₜ[R] b 0 ∈ integralImage R L ↔
      ∃ r : R, c = algebraMap R (FractionRing R) r := by
  constructor
  · rintro ⟨y, hy⟩
    obtain ⟨r, rfl⟩ := exists_smul_basis R L b y
    refine ⟨r, tmul_basis_left_injective R L b ?_⟩
    rw [← hy]
    change (1 : FractionRing R) ⊗ₜ[R] (r • b 0) = _
    rw [← TensorProduct.smul_tmul, Algebra.smul_def, mul_one]
  · rintro ⟨r, rfl⟩
    refine ⟨r • b 0, ?_⟩
    change (1 : FractionRing R) ⊗ₜ[R] (r • b 0) = _
    rw [← TensorProduct.smul_tmul, Algebra.smul_def, mul_one]

omit [IsDomain R] in
/-- Membership in the metric `I`-dual of a rank-one lattice is a single divisibility.

The vector `c • v` of the rational span lies in the `I`-dual exactly when `c * b(v,v)`
lies in `I`. -/
theorem mem_idealDual_rankOne_iff (I : Ideal R) (c : FractionRing R) :
    c ⊗ₜ[R] b 0 ∈ idealDual R L I ↔
      c * algebraMap R (FractionRing R) (L.obj.pairing (b 0) (b 0)) ∈
        integralFractionalIdeal R I := by
  rw [idealDual, mem_fractionalIdealDual_iff]
  constructor
  · intro h
    have hb := h (b 0)
    change rationalizedForm R L (c ⊗ₜ[R] b 0)
      ((1 : FractionRing R) ⊗ₜ[R] b 0) ∈ _ at hb
    rwa [rationalizedForm_tmul, mul_one] at hb
  · intro h y
    obtain ⟨r, rfl⟩ := exists_smul_basis R L b y
    obtain ⟨i, hi, hie⟩ := (FractionalIdeal.mem_coeIdeal _).mp h
    change rationalizedForm R L (c ⊗ₜ[R] b 0)
      ((1 : FractionRing R) ⊗ₜ[R] (r • b 0)) ∈ _
    rw [← TensorProduct.smul_tmul, Algebra.smul_def, mul_one, rationalizedForm_tmul]
    refine (FractionalIdeal.mem_coeIdeal _).mpr ⟨r * i, Ideal.mul_mem_left _ r hi, ?_⟩
    rw [map_mul, hie]
    ring

/-- A rank-one lattice is `I`-modular exactly when `I` is generated by `b(v,v)`. -/
theorem isIModular_rankOne_iff (I : Ideal R)
    (hne : L.obj.pairing (b 0) (b 0) ≠ 0) :
    IsIModular R L I ↔ I = Ideal.span {L.obj.pairing (b 0) (b 0)} := by
  have hinj := FaithfulSMul.algebraMap_injective R (FractionRing R)
  have hbne : algebraMap R (FractionRing R) (L.obj.pairing (b 0) (b 0)) ≠ 0 := fun h0 ↦
    hne (hinj (by rw [h0, map_zero]))
  have key : IsIModular R L I ↔ ∀ c : FractionRing R,
      (c * algebraMap R (FractionRing R) (L.obj.pairing (b 0) (b 0)) ∈
        integralFractionalIdeal R I ↔ ∃ r : R, c = algebraMap R (FractionRing R) r) := by
    constructor
    · intro h c
      have h' : fractionalIdealDual R L (integralFractionalIdeal R I) = integralImage R L := h
      rw [← mem_idealDual_rankOne_iff, ← tmul_mem_integralImage_iff, idealDual, h']
    · intro h
      change fractionalIdealDual R L (integralFractionalIdeal R I) = integralImage R L
      refine Submodule.ext fun x ↦ ?_
      obtain ⟨c, rfl⟩ := exists_tmul_basis R L b x
      rw [tmul_mem_integralImage_iff]
      exact (mem_idealDual_rankOne_iff R L b I c).trans (h c)
  rw [key]
  constructor
  · intro h
    refine le_antisymm (fun i hi ↦ ?_) ?_
    · have hdiv : algebraMap R (FractionRing R) i /
          algebraMap R (FractionRing R) (L.obj.pairing (b 0) (b 0)) *
          algebraMap R (FractionRing R) (L.obj.pairing (b 0) (b 0)) =
          algebraMap R (FractionRing R) i := div_mul_cancel₀ _ hbne
      obtain ⟨r, hr⟩ := (h _).mp (by
        rw [hdiv]
        exact FractionalIdeal.mem_coeIdeal_of_mem _ hi)
      refine Ideal.mem_span_singleton.mpr ⟨r, hinj ?_⟩
      rw [map_mul, ← hr, mul_comm, hdiv]
    · rw [Ideal.span_le, Set.singleton_subset_iff]
      have hmem := (h 1).mpr ⟨1, by rw [map_one]⟩
      rw [one_mul] at hmem
      obtain ⟨i, hi, hie⟩ := (FractionalIdeal.mem_coeIdeal _).mp hmem
      exact hinj hie ▸ hi
  · rintro rfl c
    constructor
    · intro hc
      obtain ⟨i, hi, hie⟩ := (FractionalIdeal.mem_coeIdeal _).mp hc
      obtain ⟨r, rfl⟩ := Ideal.mem_span_singleton.mp hi
      refine ⟨r, mul_right_cancel₀ hbne ?_⟩
      rw [← hie, map_mul]
      ring
    · rintro ⟨r, rfl⟩
      refine (FractionalIdeal.mem_coeIdeal _).mpr
        ⟨r * L.obj.pairing (b 0) (b 0), Ideal.mem_span_singleton.mpr ⟨r, by ring⟩, ?_⟩
      rw [map_mul]

/-- A rank-one lattice is modular for the ideal generated by its self-pairing. -/
theorem isIModular_span_singleton (hne : L.obj.pairing (b 0) (b 0) ≠ 0) :
    IsIModular R L (Ideal.span {L.obj.pairing (b 0) (b 0)}) :=
  (isIModular_rankOne_iff R L b _ hne).mpr rfl

/-- A rank-one lattice with self-pairing `u * π ^ e`, `u` a unit, is `π ^ e`-modular.

This is the modularity condition satisfied by a Jordan component over a discrete
valuation ring with uniformizer `π`. -/
theorem isIModular_span_singleton_pow (π : R) (u : Rˣ) (e : ℕ) (hπ : π ≠ 0)
    (hvv : L.obj.pairing (b 0) (b 0) = u * π ^ e) :
    IsIModular R L (Ideal.span {π ^ e}) := by
  refine (isIModular_rankOne_iff R L b _ ?_).mpr ?_
  · rw [hvv]
    exact mul_ne_zero u.ne_zero (pow_ne_zero e hπ)
  · rw [hvv, Ideal.span_singleton_mul_left_unit u.isUnit]

end RankOne

end LeanCategories.Lattices.Valued
