/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import LeanCategories.Lattices.Valued.ClassFiniteness

/-!
# Reduction theory for positive definite integral lattices

Finiteness of the class set of a genus needs a reduced basis: a basis whose Gram entries are
bounded by an explicit function of the rank and the determinant. This file supplies the two
ingredients that the reduction induction consumes, and the target of the induction.

The target is `finite_boundedGramMatrices`: integer matrices with all entries bounded by `M` form
a finite set. Once every isometry class of a fixed rank and determinant carries a basis with Gram
entries bounded by one `M`, the classes are finitely many.

The induction step splits off a shortest vector `x` and projects onto its orthogonal complement.
`exists_isMinimalVector` produces `x`: values of nonzero vectors are positive integers, so they
have a least element. `eq_one_or_neg_one_of_isMinimalVector` shows `x` is primitive, which is what
lets `x` start a basis.

The projection `y ↦ y - (b(x,y) / b(x,x)) • x` leaves the lattice: it lands in `L ⊗ ℚ`.
`scaledProjection` clears that denominator. It sends `y` to `b(x,x) • y - b(x,y) • x`, which stays
in `L`, is `ℤ`-linear, and is orthogonal to `x`. So every denominator of the true projection
divides `b(x,x)`, and `b(x,x)` is bounded by the Hermite bound of `ClassFiniteness`.

The two quantitative outputs are `pairing_scaledProjection_self` and `one_le_schurComplement`.
The first computes the value of the cleared projection as `b(x,x)` times the Schur complement
`b(x,x) * b(y,y) - b(x,y) ^ 2`. The second says that Schur complement is at least one whenever
the projection is nonzero: the projected lattice, rescaled by `b(x,x)`, is again integral and
positive definite. `exists_sub_smul_two_mul_abs_pairing_le` is the size reduction that follows:
a lattice vector can be moved by a multiple of `x` until its pairing against `x` is at most
`b(x,x) / 2` in absolute value.

## What is not here

`exists_reduced_basis` and `genus_finite` are not proved. The remaining gap is the rank induction,
which needs three constructions this file does not build.

* A primitive vector starts a basis. `eq_one_or_neg_one_of_isMinimalVector` gives primitivity of
  the shortest vector, but turning it into a basis of `L` that begins with `x` needs the Smith
  normal form of the submodule generated by `x` inside `L`.
* The image of `scaledProjection` must become an object of `FiniteProjectiveLatticeCat ℤ ℤ`, with
  the form restricted from `L`. This file proves that image is integral and positive definite
  pointwise; it does not package it as a lattice object of rank one less.
* The determinant of that object must be computed. It is `b(x,x) ^ (2 * n - 3)` times the
  determinant of `L`, by the Schur complement determinant identity for a block matrix. The
  induction hypothesis therefore has to carry a determinant bound rather than a fixed
  determinant, and none of that bookkeeping is present.
-/

@[expose] public section

noncomputable section

open LeanCategories.Modules.Bilinear.Valued

namespace LeanCategories.Lattices.Valued

/-- **The target of reduction theory.** Integer matrices with all entries bounded by `M` form a
finite set. -/
theorem finite_boundedGramMatrices (ι : Type*) [Finite ι] (M : ℤ) :
    {G : Matrix ι ι ℤ | ∀ i j, |G i j| ≤ M}.Finite := by
  have hpi : {G : Matrix ι ι ℤ | ∀ i j, |G i j| ≤ M} =
      Set.univ.pi fun _ : ι ↦ Set.univ.pi fun _ : ι ↦ Set.Icc (-M) M := by
    ext G
    constructor
    · intro hG i _ j _
      exact abs_le.mp (hG i j)
    · intro hG i j
      exact abs_le.mpr (hG i (Set.mem_univ i) j (Set.mem_univ j))
  rw [hpi]
  exact Set.Finite.pi fun _ ↦ Set.Finite.pi fun _ ↦ Set.finite_Icc _ _

/-- An integer can be moved by a multiple of a positive integer `m` until it is at most `m / 2` in
absolute value. This is the size reduction step, before it meets any lattice. -/
theorem exists_two_mul_abs_sub_mul_le {c m : ℤ} (hm : 0 < m) :
    ∃ k : ℤ, 2 * |c - k * m| ≤ m := by
  have hm' : (0 : ℚ) < (m : ℚ) := by exact_mod_cast hm
  refine ⟨round ((c : ℚ) / (m : ℚ)), ?_⟩
  have hround : |(c : ℚ) / (m : ℚ) - round ((c : ℚ) / (m : ℚ))| ≤ 1 / 2 :=
    abs_sub_round _
  have hfactor : (c : ℚ) - (round ((c : ℚ) / (m : ℚ)) : ℚ) * (m : ℚ) =
      (m : ℚ) * ((c : ℚ) / (m : ℚ) - round ((c : ℚ) / (m : ℚ))) := by
    field_simp
  have hrat : 2 * |(c : ℚ) - (round ((c : ℚ) / (m : ℚ)) : ℚ) * (m : ℚ)| ≤ (m : ℚ) := by
    rw [hfactor, abs_mul, abs_of_pos hm']
    nlinarith [abs_nonneg ((c : ℚ) / (m : ℚ) - round ((c : ℚ) / (m : ℚ)))]
  exact_mod_cast hrat

namespace FiniteProjectiveLatticeCat

variable (L : FiniteProjectiveLatticeCat ℤ ℤ)

section Pairing

/-- The pairing negates on the right. -/
theorem pairing_neg_right (x y : L.obj.obj.carrier) :
    L.obj.obj.pairing x (-y) = -L.obj.obj.pairing x y := by
  have h : L.obj.obj.pairing x (-y) + L.obj.obj.pairing x y = 0 := by
    rw [← BilinModuleCat.pairing_add_right, neg_add_cancel,
      BilinModuleCat.pairing_zero_right]
  linarith

/-- The pairing negates on the left. -/
theorem pairing_neg_left (x y : L.obj.obj.carrier) :
    L.obj.obj.pairing (-x) y = -L.obj.obj.pairing x y := by
  have h : L.obj.obj.pairing (-x) y + L.obj.obj.pairing x y = 0 := by
    rw [← BilinModuleCat.pairing_add_left, neg_add_cancel, BilinModuleCat.pairing_zero_left]
  linarith

/-- The pairing is additive on the right for differences. -/
theorem pairing_sub_right (x y z : L.obj.obj.carrier) :
    L.obj.obj.pairing x (y - z) = L.obj.obj.pairing x y - L.obj.obj.pairing x z := by
  rw [sub_eq_add_neg, BilinModuleCat.pairing_add_right, L.pairing_neg_right, sub_eq_add_neg]

/-- The pairing is additive on the left for differences. -/
theorem pairing_sub_left (x y z : L.obj.obj.carrier) :
    L.obj.obj.pairing (x - y) z = L.obj.obj.pairing x z - L.obj.obj.pairing y z := by
  rw [sub_eq_add_neg, BilinModuleCat.pairing_add_left, L.pairing_neg_left, sub_eq_add_neg]

/-- The pairing against `y - k • x`, expanded. -/
theorem pairing_sub_smul_right (x y : L.obj.obj.carrier) (k : ℤ) :
    L.obj.obj.pairing x (y - k • x) =
      L.obj.obj.pairing x y - k * L.obj.obj.pairing x x := by
  simp [L.pairing_sub_right]

/-- Every vector of a positive definite lattice has a nonnegative value. -/
theorem pairing_self_nonneg (hL : IsPositiveDefiniteLattice L) (x : L.obj.obj.carrier) :
    0 ≤ L.obj.obj.pairing x x := by
  rcases eq_or_ne x 0 with rfl | hx
  · simp
  · exact (L.pairing_self_pos hL hx).le

end Pairing

section MinimalVector

/-- A nonzero lattice vector of least value. -/
def IsMinimalVector (x : L.obj.obj.carrier) : Prop :=
  x ≠ 0 ∧ ∀ y : L.obj.obj.carrier, y ≠ 0 → L.obj.obj.pairing x x ≤ L.obj.obj.pairing y y

/-- **A positive definite lattice of positive rank has a shortest vector.** The values of nonzero
vectors are positive integers, so they have a least element. -/
theorem exists_isMinimalVector (hL : IsPositiveDefiniteLattice L) (hrank : 0 < L.rank) :
    ∃ x : L.obj.obj.carrier, L.IsMinimalVector x := by
  classical
  letI : Module.Finite ℤ L.obj.obj.carrier := L.property
  haveI : Nontrivial L.obj.obj.carrier := Module.nontrivial_of_finrank_pos (R := ℤ) hrank
  obtain ⟨x₀, hx₀⟩ := exists_ne (0 : L.obj.obj.carrier)
  obtain ⟨n, ⟨y, hy0, hyn⟩, hleast⟩ :=
    Int.exists_least_of_bdd
      (P := fun n : ℤ ↦ ∃ z : L.obj.obj.carrier, z ≠ 0 ∧ L.obj.obj.pairing z z = n)
      ⟨0, by rintro z ⟨w, hw, rfl⟩; exact (L.pairing_self_pos hL hw).le⟩
      ⟨_, x₀, hx₀, rfl⟩
  exact ⟨y, hy0, fun z hz ↦ by rw [hyn]; exact hleast _ ⟨z, hz, rfl⟩⟩

/-- **A shortest vector is primitive.** Writing it as a proper multiple would produce a shorter
nonzero vector. -/
theorem eq_one_or_neg_one_of_isMinimalVector (hL : IsPositiveDefiniteLattice L)
    {x w : L.obj.obj.carrier} {k : ℤ} (hx : L.IsMinimalVector x) (hxk : x = k • w) :
    k = 1 ∨ k = -1 := by
  obtain ⟨hx0, hmin⟩ := hx
  have hw0 : w ≠ 0 := by
    rintro rfl
    exact hx0 (by rw [hxk, zsmul_zero])
  have hk0 : k ≠ 0 := by
    rintro rfl
    exact hx0 (by simp [hxk])
  have hwpos : 0 < L.obj.obj.pairing w w := L.pairing_self_pos hL hw0
  have hval : L.obj.obj.pairing x x = k ^ 2 * L.obj.obj.pairing w w := by
    rw [hxk]
    simp only [BilinModuleCat.pairing_zsmul_left, BilinModuleCat.pairing_zsmul_right,
      zsmul_eq_mul, Int.cast_id]
    ring
  have hle : k ^ 2 * L.obj.obj.pairing w w ≤ L.obj.obj.pairing w w := hval ▸ hmin w hw0
  have hksq : k ^ 2 ≤ 1 := by nlinarith
  rcases lt_trichotomy k 0 with h | h | h
  · right; nlinarith
  · exact absurd h hk0
  · left; nlinarith

end MinimalVector

section Projection

/-- **The orthogonal projection, cleared of denominators.** The true projection onto the
orthogonal complement of `x` sends `y` to `y - (b(x,y) / b(x,x)) • x`, which lies in `L ⊗ ℚ` and
not in `L`. Multiplying by `b(x,x)` returns it to `L`, so every denominator divides `b(x,x)`. -/
def scaledProjection (x : L.obj.obj.carrier) :
    L.obj.obj.carrier →ₗ[ℤ] L.obj.obj.carrier where
  toFun y := L.obj.obj.pairing x x • y - L.obj.obj.pairing x y • x
  map_add' y z := by
    simp only [BilinModuleCat.pairing_add_right, ← Int.cast_smul_eq_zsmul ℤ, Int.cast_id]
    module
  map_smul' r y := by
    simp only [RingHom.id_apply, BilinModuleCat.pairing_smul_right, smul_eq_mul,
      ← Int.cast_smul_eq_zsmul ℤ, Int.cast_id]
    module

@[simp]
theorem scaledProjection_apply (x y : L.obj.obj.carrier) :
    L.scaledProjection x y = L.obj.obj.pairing x x • y - L.obj.obj.pairing x y • x :=
  rfl

/-- **The denominator bound.** Scaling `y` by `b(x,x)` splits it inside `L` into a multiple of `x`
and a vector orthogonal to `x`. -/
theorem smul_eq_add_scaledProjection (x y : L.obj.obj.carrier) :
    L.obj.obj.pairing x x • y = L.obj.obj.pairing x y • x + L.scaledProjection x y := by
  rw [scaledProjection_apply]
  abel

/-- The cleared projection is orthogonal to `x`. -/
-- not a simp lemma: `scaledProjection_apply` rewrites the left-hand side first
theorem pairing_scaledProjection_left (x y : L.obj.obj.carrier) :
    L.obj.obj.pairing x (L.scaledProjection x y) = 0 := by
  simp only [scaledProjection_apply, L.pairing_sub_right,
    BilinModuleCat.pairing_zsmul_right, zsmul_eq_mul, Int.cast_id]
  ring

/-- The cleared projection vanishes exactly on the rational line through `x`. -/
theorem scaledProjection_eq_zero_iff (x y : L.obj.obj.carrier) :
    L.scaledProjection x y = 0 ↔
      L.obj.obj.pairing x x • y = L.obj.obj.pairing x y • x := by
  rw [scaledProjection_apply, sub_eq_zero]

/-- **The value of the cleared projection.** It is `b(x,x)` times the Schur complement
`b(x,x) * b(y,y) - b(x,y) ^ 2`, so the true projection has value the Schur complement divided by
`b(x,x)`. -/
theorem pairing_scaledProjection_self (x y : L.obj.obj.carrier) :
    L.obj.obj.pairing (L.scaledProjection x y) (L.scaledProjection x y) =
      L.obj.obj.pairing x x *
        (L.obj.obj.pairing x x * L.obj.obj.pairing y y - L.obj.obj.pairing x y ^ 2) := by
  have hsymm : L.obj.obj.pairing y x = L.obj.obj.pairing x y := L.obj.property.2 y x
  simp only [scaledProjection_apply, L.pairing_sub_left, L.pairing_sub_right,
    BilinModuleCat.pairing_zsmul_left, BilinModuleCat.pairing_zsmul_right, zsmul_eq_mul,
    Int.cast_id, hsymm]
  ring

/-- **Cauchy-Schwarz over the integers.** A positive definite pairing satisfies
`b(x,y) ^ 2 ≤ b(x,x) * b(y,y)`. -/
theorem pairing_sq_le (hL : IsPositiveDefiniteLattice L) (x y : L.obj.obj.carrier) :
    L.obj.obj.pairing x y ^ 2 ≤ L.obj.obj.pairing x x * L.obj.obj.pairing y y := by
  rcases eq_or_ne x 0 with rfl | hx
  · simp
  have hm : 0 < L.obj.obj.pairing x x := L.pairing_self_pos hL hx
  have hnn : 0 ≤ L.obj.obj.pairing x x *
      (L.obj.obj.pairing x x * L.obj.obj.pairing y y - L.obj.obj.pairing x y ^ 2) := by
    rw [← L.pairing_scaledProjection_self x y]
    exact L.pairing_self_nonneg hL _
  nlinarith

/-- **The projected lattice is integral after rescaling.** When the cleared projection of `y` is
nonzero, the Schur complement is at least one. The true projection of `y` has value the Schur
complement divided by `b(x,x)`, so the projected lattice has minimum at least `1 / b(x,x)`: its
denominators are controlled by the Hermite bound on `b(x,x)`. -/
theorem one_le_schurComplement (hL : IsPositiveDefiniteLattice L) {x y : L.obj.obj.carrier}
    (h : L.scaledProjection x y ≠ 0) :
    1 ≤ L.obj.obj.pairing x x * L.obj.obj.pairing y y - L.obj.obj.pairing x y ^ 2 := by
  have hx : x ≠ 0 := by
    rintro rfl
    exact h (by simp)
  have hm : 0 < L.obj.obj.pairing x x := L.pairing_self_pos hL hx
  have hpos : 0 < L.obj.obj.pairing x x *
      (L.obj.obj.pairing x x * L.obj.obj.pairing y y - L.obj.obj.pairing x y ^ 2) := by
    rw [← L.pairing_scaledProjection_self x y]
    exact L.pairing_self_pos hL h
  nlinarith

/-- **Size reduction.** A lattice vector can be moved by a multiple of a nonzero `x` until its
pairing against `x` is at most `b(x,x) / 2` in absolute value. -/
theorem exists_sub_smul_two_mul_abs_pairing_le (hL : IsPositiveDefiniteLattice L)
    {x : L.obj.obj.carrier} (hx : x ≠ 0) (y : L.obj.obj.carrier) :
    ∃ k : ℤ, 2 * |L.obj.obj.pairing x (y - k • x)| ≤ L.obj.obj.pairing x x := by
  obtain ⟨k, hk⟩ := exists_two_mul_abs_sub_mul_le
    (c := L.obj.obj.pairing x y) (L.pairing_self_pos hL hx)
  exact ⟨k, by rw [L.pairing_sub_smul_right x y k]; exact hk⟩

end Projection

end FiniteProjectiveLatticeCat

end LeanCategories.Lattices.Valued
