/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import LeanCategories.Lattices.Valued.OrthogonalSplitting
public import LeanCategories.Lattices.Valued.ReflectionTransitivity
public import LeanCategories.Lattices.Valued.RestrictForm
public import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas
public import Mathlib.LinearAlgebra.Projection

/-!
# Reflections generate the orthogonal group

The orthogonal group of a nondegenerate finite symmetric form over a field of characteristic
other than two is generated by reflections in nonsingular vectors.

The proof is induction on the rank. An anisotropic vector `v` splits the carrier into its line
and the orthogonal complement `W`. An isometry `g` moves `v` to a vector of the same value, so
a product of reflections returns it to `v`. The corrected isometry preserves `W`, and the
inductive hypothesis writes its restriction as a product of reflections of `W`. Extension by
the identity on the line carries each reflection of `W` to a reflection of the whole form.

Reference: Lam, *Introduction to Quadratic Forms over Fields*, Chapter I, §5.
-/

@[expose] public section

open CategoryTheory
open LeanCategories.Modules.Bilinear.Valued

namespace LeanCategories.Lattices.Valued

universe u

variable {K : Type u} [Field K] [Invertible (2 : K)]

omit [Invertible (2 : K)] in
/-- A vector of the line is orthogonal to a vector of the complement. -/
theorem pairing_line_complement (L : FiniteFormCat K K) (v : L.obj.carrier)
    (a : (K ∙ v)) (w : anisotropicComplement L v) :
    L.obj.pairing (a : L.obj.carrier) (w : L.obj.carrier) = 0 := by
  obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp a.2
  rw [show (a : L.obj.carrier) = c • v from hc.symm, BilinModuleCat.pairing_smul_left,
    (mem_anisotropicComplement_iff L v w).mp w.2, smul_zero]

omit [Invertible (2 : K)] in
/-- A vector of the complement is orthogonal to a vector of the line. -/
theorem pairing_complement_line (L : FiniteFormCat K K) (v : L.obj.carrier)
    (w : anisotropicComplement L v) (a : (K ∙ v)) :
    L.obj.pairing (w : L.obj.carrier) (a : L.obj.carrier) = 0 := by
  rw [L.property.2, pairing_line_complement]

omit [Invertible (2 : K)] in
/-- The pairing of two split vectors has no cross terms. -/
theorem pairing_add_of_split (L : FiniteFormCat K K) (v : L.obj.carrier)
    (a c : (K ∙ v)) (b d : anisotropicComplement L v) :
    L.obj.pairing ((a : L.obj.carrier) + b) ((c : L.obj.carrier) + d) =
      L.obj.pairing (a : L.obj.carrier) (c : L.obj.carrier) +
        L.obj.pairing (b : L.obj.carrier) (d : L.obj.carrier) := by
  rw [BilinModuleCat.pairing_add_left, BilinModuleCat.pairing_add_right,
    BilinModuleCat.pairing_add_right, pairing_line_complement L v a d,
    pairing_complement_line L v b c]
  ring

omit [Invertible (2 : K)] in
/-- An isometry fixing `v` fixes the whole line of `v`. -/
theorem apply_line_eq (L : FiniteFormCat K K) (v : L.obj.carrier)
    (g : BilinModuleCat.OrthogonalGroup L.obj) (hg : g.1 v = v) (a : (K ∙ v)) :
    g.1 (a : L.obj.carrier) = (a : L.obj.carrier) := by
  obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp a.2
  rw [show (a : L.obj.carrier) = c • v from hc.symm, map_smul, hg]

omit [Invertible (2 : K)] in
/-- The carrier of a restricted form is the submodule itself.

This transports an automorphism across that identification, so that later steps work with a
single set of module instances. -/
def ofRestrictCarrier (L : FiniteFormCat K K) (P : Submodule K L.obj.carrier)
    (f : (restrictForm L P).obj.carrier ≃ₗ[K] (restrictForm L P).obj.carrier) : P ≃ₗ[K] P :=
  f

/-- The line of a nonsingular vector and its orthogonal complement split the carrier. -/
noncomputable def splitEquiv (L : FiniteFormCat K K) (v : L.obj.carrier)
    (hv : L.obj.pairing v v ≠ 0) :
    ((K ∙ v) × anisotropicComplement L v) ≃ₗ[K] L.obj.carrier :=
  Submodule.prodEquivOfIsCompl _ _ (isCompl_span_anisotropicComplement L v hv)

omit [Invertible (2 : K)] in
/-- The two components of a split vector add up to the vector. -/
@[simp]
theorem splitEquiv_symm_add (L : FiniteFormCat K K) (v : L.obj.carrier)
    (hv : L.obj.pairing v v ≠ 0) (x : L.obj.carrier) :
    (((splitEquiv L v hv).symm x).1 : L.obj.carrier) +
      (((splitEquiv L v hv).symm x).2 : L.obj.carrier) = x :=
  (splitEquiv L v hv).apply_symm_apply x

/-- Extend an automorphism of the complement by the identity on the line. -/
noncomputable def extendComplementEquiv (L : FiniteFormCat K K) (v : L.obj.carrier)
    (hv : L.obj.pairing v v ≠ 0)
    (f : (anisotropicComplement L v) ≃ₗ[K] (anisotropicComplement L v)) :
    L.obj.carrier ≃ₗ[K] L.obj.carrier :=
  ((splitEquiv L v hv).symm.trans
    ((LinearEquiv.refl K (K ∙ v)).prodCongr f)).trans (splitEquiv L v hv)

omit [Invertible (2 : K)] in
/-- The extension keeps the line component and moves the complement component. -/
theorem extendComplementEquiv_apply (L : FiniteFormCat K K) (v : L.obj.carrier)
    (hv : L.obj.pairing v v ≠ 0)
    (f : (anisotropicComplement L v) ≃ₗ[K] (anisotropicComplement L v))
    (x : L.obj.carrier) :
    extendComplementEquiv L v hv f x =
      (((splitEquiv L v hv).symm x).1 : L.obj.carrier) +
        ((f ((splitEquiv L v hv).symm x).2 : anisotropicComplement L v) : L.obj.carrier) :=
  rfl

omit [Invertible (2 : K)] in
/-- The extension of the identity is the identity. -/
theorem extendComplementEquiv_one (L : FiniteFormCat K K) (v : L.obj.carrier)
    (hv : L.obj.pairing v v ≠ 0) :
    extendComplementEquiv L v hv (LinearEquiv.refl K (anisotropicComplement L v)) =
      LinearEquiv.refl K L.obj.carrier := by
  refine LinearEquiv.ext fun x ↦ ?_
  rw [extendComplementEquiv_apply]
  exact splitEquiv_symm_add L v hv x

omit [Invertible (2 : K)] in
/-- The extension turns composition into composition. -/
theorem extendComplementEquiv_trans (L : FiniteFormCat K K) (v : L.obj.carrier)
    (hv : L.obj.pairing v v ≠ 0)
    (f g : (anisotropicComplement L v) ≃ₗ[K] (anisotropicComplement L v)) :
    extendComplementEquiv L v hv (g.trans f) =
      (extendComplementEquiv L v hv g).trans (extendComplementEquiv L v hv f) := by
  refine LinearEquiv.ext fun x ↦ ?_
  have hsymm : (splitEquiv L v hv).symm (extendComplementEquiv L v hv g x) =
      ((LinearEquiv.refl K (K ∙ v)).prodCongr g) ((splitEquiv L v hv).symm x) :=
    (splitEquiv L v hv).symm_apply_apply _
  change extendComplementEquiv L v hv (g.trans f) x =
    extendComplementEquiv L v hv f (extendComplementEquiv L v hv g x)
  rw [extendComplementEquiv_apply, extendComplementEquiv_apply, hsymm]
  rfl

omit [Invertible (2 : K)] in
/-- The extension of an isometry of the complement is an isometry. -/
theorem extendComplementEquiv_isometry (L : FiniteFormCat K K) (v : L.obj.carrier)
    (hv : L.obj.pairing v v ≠ 0)
    (f : (anisotropicComplement L v) ≃ₗ[K] (anisotropicComplement L v))
    (hf : ∀ b d : anisotropicComplement L v,
      L.obj.pairing (f b : L.obj.carrier) (f d : L.obj.carrier) =
        L.obj.pairing (b : L.obj.carrier) (d : L.obj.carrier))
    (x y : L.obj.carrier) :
    L.obj.pairing (extendComplementEquiv L v hv f x) (extendComplementEquiv L v hv f y) =
      L.obj.pairing x y := by
  rw [extendComplementEquiv_apply, extendComplementEquiv_apply, pairing_add_of_split, hf,
    ← pairing_add_of_split, splitEquiv_symm_add, splitEquiv_symm_add]

/-- Extension by the identity on the line, as a homomorphism of orthogonal groups. -/
noncomputable def extendOrthogonal (L : FiniteFormCat K K) (v : L.obj.carrier)
    (hv : L.obj.pairing v v ≠ 0) :
    BilinModuleCat.OrthogonalGroup (restrictForm L (anisotropicComplement L v)).obj →*
      BilinModuleCat.OrthogonalGroup L.obj where
  toFun f := ⟨extendComplementEquiv L v hv (ofRestrictCarrier L _ f.1),
    extendComplementEquiv_isometry L v hv _ f.property⟩
  map_one' := Subtype.ext (extendComplementEquiv_one L v hv)
  map_mul' f g :=
    Subtype.ext (extendComplementEquiv_trans L v hv
      (ofRestrictCarrier L _ f.1) (ofRestrictCarrier L _ g.1))

omit [Invertible (2 : K)] in
/-- The extension is the extension of the underlying automorphism. -/
theorem extendOrthogonal_apply (L : FiniteFormCat K K) (v : L.obj.carrier)
    (hv : L.obj.pairing v v ≠ 0)
    (f : BilinModuleCat.OrthogonalGroup (restrictForm L (anisotropicComplement L v)).obj)
    (x : L.obj.carrier) :
    (extendOrthogonal L v hv f).1 x =
      extendComplementEquiv L v hv (ofRestrictCarrier L _ f.1) x :=
  rfl

omit [Invertible (2 : K)] in
/-- A reflection of the restricted form acts by the ambient reflection formula. -/
theorem coe_ofRestrictCarrier_reflection (L : FiniteFormCat K K) (v : L.obj.carrier)
    (w : anisotropicComplement L v)
    (hw : L.obj.pairing (w : L.obj.carrier) (w : L.obj.carrier) ≠ 0)
    (b : anisotropicComplement L v) :
    ((ofRestrictCarrier L (anisotropicComplement L v)
        (finiteFormReflectionElement (restrictForm L (anisotropicComplement L v)) w hw).1 b :
      L.obj.carrier)) =
      (b : L.obj.carrier) -
        (2 * (L.obj.pairing (w : L.obj.carrier) (w : L.obj.carrier))⁻¹ *
          L.obj.pairing (w : L.obj.carrier) (b : L.obj.carrier)) • (w : L.obj.carrier) :=
  rfl

omit [Invertible (2 : K)] in
/-- The extension of a reflection of the complement is a reflection. -/
theorem extendOrthogonal_reflection (L : FiniteFormCat K K) (v : L.obj.carrier)
    (hv : L.obj.pairing v v ≠ 0) (w : anisotropicComplement L v)
    (hw : L.obj.pairing (w : L.obj.carrier) (w : L.obj.carrier) ≠ 0) :
    extendOrthogonal L v hv
        (finiteFormReflectionElement (restrictForm L (anisotropicComplement L v)) w hw) =
      finiteFormReflectionElement L (w : L.obj.carrier) hw := by
  refine Subtype.ext (LinearEquiv.ext fun x ↦ ?_)
  change extendComplementEquiv L v hv
      (ofRestrictCarrier L (anisotropicComplement L v)
        (finiteFormReflectionElement (restrictForm L (anisotropicComplement L v)) w hw).1) x =
    finiteFormReflection L (w : L.obj.carrier) hw x
  rw [extendComplementEquiv_apply, coe_ofRestrictCarrier_reflection, finiteFormReflection_apply]
  simp only [reflectionFunctional, LinearMap.smul_apply, BilinModuleCat.bilinMap_apply,
    smul_eq_mul]
  set a := ((splitEquiv L v hv).symm x).1
  set b := ((splitEquiv L v hv).symm x).2
  have hx : (a : L.obj.carrier) + (b : L.obj.carrier) = x := splitEquiv_symm_add L v hv x
  rw [← hx, BilinModuleCat.pairing_add_right, pairing_complement_line L v w a, zero_add]
  module

omit [Invertible (2 : K)] in
/-- An isometry fixing `v` maps the complement of `v` onto itself. -/
theorem map_anisotropicComplement_eq (L : FiniteFormCat K K) (v : L.obj.carrier)
    (g : BilinModuleCat.OrthogonalGroup L.obj) (hg : g.1 v = v) :
    (anisotropicComplement L v).map g.1.toLinearMap = anisotropicComplement L v := by
  refine le_antisymm (map_anisotropicComplement_le L v g hg) fun y hy ↦
    Submodule.mem_map.mpr ⟨g.1.symm y, ?_, by simp⟩
  rw [mem_anisotropicComplement_iff] at hy ⊢
  rw [← g.property v (g.1.symm y), hg, LinearEquiv.apply_symm_apply]
  exact hy

omit [Invertible (2 : K)] in
/-- Restrict an isometry fixing `v` to the orthogonal complement of `v`. -/
noncomputable def restrictOrthogonal (L : FiniteFormCat K K) (v : L.obj.carrier)
    (g : BilinModuleCat.OrthogonalGroup L.obj) (hg : g.1 v = v) :
    BilinModuleCat.OrthogonalGroup (restrictForm L (anisotropicComplement L v)).obj :=
  ⟨(g.1.submoduleMap (anisotropicComplement L v)).trans
      (LinearEquiv.ofEq _ _ (map_anisotropicComplement_eq L v g hg)),
    fun _ _ ↦ g.property _ _⟩

omit [Invertible (2 : K)] in
/-- The restricted isometry acts by the ambient isometry. -/
theorem coe_ofRestrictCarrier_restrictOrthogonal (L : FiniteFormCat K K) (v : L.obj.carrier)
    (g : BilinModuleCat.OrthogonalGroup L.obj) (hg : g.1 v = v)
    (b : anisotropicComplement L v) :
    ((ofRestrictCarrier L (anisotropicComplement L v) (restrictOrthogonal L v g hg).1 b :
      L.obj.carrier)) = g.1 (b : L.obj.carrier) :=
  rfl

omit [Invertible (2 : K)] in
/-- Extending a restricted isometry recovers the isometry. -/
theorem extendOrthogonal_restrictOrthogonal (L : FiniteFormCat K K) (v : L.obj.carrier)
    (hv : L.obj.pairing v v ≠ 0) (g : BilinModuleCat.OrthogonalGroup L.obj) (hg : g.1 v = v) :
    extendOrthogonal L v hv (restrictOrthogonal L v g hg) = g := by
  refine Subtype.ext (LinearEquiv.ext fun x ↦ ?_)
  rw [extendOrthogonal_apply, extendComplementEquiv_apply,
    coe_ofRestrictCarrier_restrictOrthogonal]
  set a := ((splitEquiv L v hv).symm x).1
  set b := ((splitEquiv L v hv).symm x).2
  have hx : (a : L.obj.carrier) + (b : L.obj.carrier) = x := splitEquiv_symm_add L v hv x
  rw [← hx, map_add, apply_line_eq L v g hg]

omit [Invertible (2 : K)] in
/-- The restriction of a nondegenerate form to the complement of a nonsingular vector is
nondegenerate. -/
theorem isLeftNondegenerate_restrictForm (L : FiniteFormCat K K)
    (hL : L.obj.IsLeftNondegenerate) (v : L.obj.carrier) (hv : L.obj.pairing v v ≠ 0) :
    (restrictForm L (anisotropicComplement L v)).obj.IsLeftNondegenerate := by
  rw [BilinModuleCat.IsLeftNondegenerate, Submodule.eq_bot_iff]
  rintro (b : anisotropicComplement L v) hb
  have hb' : ∀ d : anisotropicComplement L v,
      L.obj.pairing (b : L.obj.carrier) (d : L.obj.carrier) = 0 := fun d ↦
    LinearMap.congr_fun (LinearMap.mem_ker.mp hb) d
  have hzero : ∀ x : L.obj.carrier, L.obj.pairing (b : L.obj.carrier) x = 0 := by
    intro x
    rw [← splitEquiv_symm_add L v hv x, BilinModuleCat.pairing_add_right,
      pairing_complement_line L v b _, hb', add_zero]
  have hmem : (b : L.obj.carrier) ∈ LinearMap.ker L.obj.adjoint :=
    LinearMap.mem_ker.mpr (LinearMap.ext hzero)
  rw [hL] at hmem
  exact Submodule.coe_eq_zero.mp (by simpa using hmem)

/-- Reflections generate the orthogonal group, by induction on the rank. -/
theorem reflectionsGenerate_of_finrank_eq :
    ∀ (n : ℕ) (L : FiniteFormCat K K), Module.finrank K L.obj.carrier = n →
      L.obj.IsLeftNondegenerate → ReflectionsGenerate L := by
  intro n
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    intro L hn hL
    haveI : Module.Finite K L.obj.carrier := L.property.1
    rw [ReflectionsGenerate, Subgroup.eq_top_iff']
    intro g
    by_cases hsub : Subsingleton L.obj.carrier
    · have hone : g = 1 := Subtype.ext (LinearEquiv.ext fun x ↦ Subsingleton.elim _ _)
      exact hone ▸ Subgroup.one_mem _
    · haveI : Nontrivial L.obj.carrier := not_subsingleton_iff_nontrivial.mp hsub
      obtain ⟨x, hx⟩ := exists_ne (0 : L.obj.carrier)
      obtain ⟨v, hv⟩ := exists_pairing_self_ne_zero L hL hx
      have hv0 : v ≠ 0 := by
        rintro rfl
        exact hv (by simp)
      have hrank : Module.finrank K (K ∙ v) +
          Module.finrank K (anisotropicComplement L v) = n := by
        rw [← hn]
        exact Submodule.finrank_add_eq_of_isCompl (isCompl_span_anisotropicComplement L v hv)
      rw [finrank_span_singleton hv0] at hrank
      have hgen := ih (Module.finrank K (anisotropicComplement L v)) (by omega)
        (restrictForm L (anisotropicComplement L v)) rfl
        (isLeftNondegenerate_restrictForm L hL v hv)
      have hgv : L.obj.pairing (g.1 v) (g.1 v) ≠ 0 := by
        rw [g.property]
        exact hv
      obtain ⟨h, hhmem, hhv⟩ :=
        exists_mem_closure_reflections_apply_eq L (g.1 v) v hgv (g.property v v)
      have hfix : (h * g).1 v = v := hhv
      have himg : (extendOrthogonal L v hv) ''
          finiteFormReflections (restrictForm L (anisotropicComplement L v)) ⊆
          finiteFormReflections L := by
        rintro _ ⟨_, ⟨(w : anisotropicComplement L v), hw, rfl⟩, rfl⟩
        exact ⟨(w : L.obj.carrier), hw, extendOrthogonal_reflection L v hv w hw⟩
      have hmem : h * g ∈ Subgroup.closure (finiteFormReflections L) := by
        have hres : restrictOrthogonal L v (h * g) hfix ∈
            Subgroup.closure
              (finiteFormReflections (restrictForm L (anisotropicComplement L v))) := by
          rw [hgen]
          trivial
        have hmap := Subgroup.mem_map_of_mem (extendOrthogonal L v hv) hres
        rw [MonoidHom.map_closure, extendOrthogonal_restrictOrthogonal] at hmap
        exact Subgroup.closure_mono himg hmap
      have hsplit : g = h⁻¹ * (h * g) := by group
      exact hsplit ▸ Subgroup.mul_mem _ (Subgroup.inv_mem _ hhmem) hmem

/-- Reflections generate the orthogonal group of a nondegenerate finite symmetric form. -/
theorem reflectionsGenerate (L : FiniteFormCat K K) (hL : L.obj.IsLeftNondegenerate) :
    ReflectionsGenerate L :=
  reflectionsGenerate_of_finrank_eq _ L rfl hL

end LeanCategories.Lattices.Valued
