/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import LeanCategories.Lattices.Valued.Spinor

/-!
# Transitivity of the reflection group on vectors of equal value

Two vectors of the same nonzero self-pairing lie in one orbit of the group generated by
reflections. This is the vector case of Witt's extension theorem, and the inductive step of
the theorem that reflections generate the orthogonal group of a finite symmetric form.

Reference: Lam, *Introduction to Quadratic Forms over Fields*, Chapter I, §2.
-/

@[expose] public section

open CategoryTheory
open LeanCategories.Modules.Bilinear.Valued

namespace LeanCategories.Lattices.Valued

universe u

variable {K : Type u} [Field K] [Invertible (2 : K)]

omit [Invertible (2 : K)] in
/-- The pairing expands over a difference in the left argument. -/
theorem pairing_sub_left (L : FiniteFormCat K K) (x y z : L.obj.carrier) :
    L.obj.pairing (x - y) z = L.obj.pairing x z - L.obj.pairing y z := by
  change L.obj.bilinMap (x - y) z = L.obj.bilinMap x z - L.obj.bilinMap y z
  rw [map_sub, LinearMap.sub_apply]

omit [Invertible (2 : K)] in
/-- The pairing expands over a difference in the right argument. -/
theorem pairing_sub_right (L : FiniteFormCat K K) (x y z : L.obj.carrier) :
    L.obj.pairing x (y - z) = L.obj.pairing x y - L.obj.pairing x z := by
  change L.obj.bilinMap x (y - z) = L.obj.bilinMap x y - L.obj.bilinMap x z
  rw [map_sub]

omit [Invertible (2 : K)] in
/-- The self-pairing of the difference of two vectors of equal value. -/
theorem pairing_sub_self (L : FiniteFormCat K K) (u v : L.obj.carrier)
    (huv : L.obj.pairing u u = L.obj.pairing v v) :
    L.obj.pairing (u - v) (u - v) =
      2 * L.obj.pairing u u - 2 * L.obj.pairing u v := by
  rw [pairing_sub_left, pairing_sub_right, pairing_sub_right, L.property.2 v u,
    ← huv]
  ring

omit [Invertible (2 : K)] in
/-- The self-pairing of the sum of two vectors of equal value. -/
theorem pairing_add_self (L : FiniteFormCat K K) (u v : L.obj.carrier)
    (huv : L.obj.pairing u u = L.obj.pairing v v) :
    L.obj.pairing (u + v) (u + v) =
      2 * L.obj.pairing u u + 2 * L.obj.pairing u v := by
  rw [BilinModuleCat.pairing_add_left, BilinModuleCat.pairing_add_right,
    BilinModuleCat.pairing_add_right, L.property.2 v u, ← huv]
  ring

omit [Invertible (2 : K)] in
/-- Reflection subtracts the reflecting vector when the reflection coefficient is one. -/
theorem finiteFormReflection_apply_of_two_mul_pairing_eq (L : FiniteFormCat K K)
    (w x : L.obj.carrier) (hw : L.obj.pairing w w ≠ 0)
    (h : 2 * L.obj.pairing w x = L.obj.pairing w w) :
    finiteFormReflection L w hw x = x - w := by
  have hcoeff : reflectionFunctional L w hw x = 1 := by
    simp only [reflectionFunctional, LinearMap.smul_apply,
      BilinModuleCat.bilinMap_apply, smul_eq_mul]
    field_simp
    exact h
  rw [finiteFormReflection_apply, hcoeff, one_smul]

omit [Invertible (2 : K)] in
/-- Reflection in a vector negates that vector. -/
theorem finiteFormReflection_apply_self (L : FiniteFormCat K K)
    (w : L.obj.carrier) (hw : L.obj.pairing w w ≠ 0) :
    finiteFormReflection L w hw w = -w := by
  rw [finiteFormReflection_apply, reflectionFunctional_apply_self]
  module

omit [Invertible (2 : K)] in
/-- Every reflection lies in the subgroup generated by reflections. -/
theorem finiteFormReflectionElement_mem_closure (L : FiniteFormCat K K)
    (w : L.obj.carrier) (hw : L.obj.pairing w w ≠ 0) :
    finiteFormReflectionElement L w hw ∈
      Subgroup.closure (finiteFormReflections L) :=
  Subgroup.subset_closure ⟨w, hw, rfl⟩

/-- Two vectors of the same nonzero value lie in one orbit of the reflection group.

This is the vector case of Witt's extension theorem: reflect in `u - v`, or in `u + v`
followed by `v` when the first reflection is unavailable. -/
theorem exists_mem_closure_reflections_apply_eq (L : FiniteFormCat K K)
    (u v : L.obj.carrier) (hu : L.obj.pairing u u ≠ 0)
    (huv : L.obj.pairing u u = L.obj.pairing v v) :
    ∃ g ∈ Subgroup.closure (finiteFormReflections L),
      BilinModuleCat.OrthogonalGroup.actOnVector g u = v := by
  have hv : L.obj.pairing v v ≠ 0 := huv ▸ hu
  have hsub := pairing_sub_self L u v huv
  have hadd := pairing_add_self L u v huv
  by_cases hd : L.obj.pairing (u - v) (u - v) = 0
  · have h2 : (2 : K) ≠ 0 := Invertible.ne_zero 2
    have huv' : L.obj.pairing u v = L.obj.pairing u u := by
      have hz : (2 : K) * (L.obj.pairing u u - L.obj.pairing u v) = 0 := by
        linear_combination hsub.symm.trans hd
      exact (sub_eq_zero.mp ((mul_eq_zero.mp hz).resolve_left h2)).symm
    have hne : L.obj.pairing (u + v) (u + v) ≠ 0 := by
      rw [hadd, huv']
      intro hzero
      have hz : (2 : K) * 2 * L.obj.pairing u u = 0 := by
        linear_combination hzero
      exact hu ((mul_eq_zero.mp hz).resolve_left (mul_ne_zero h2 h2))
    refine ⟨finiteFormReflectionElement L v hv *
      finiteFormReflectionElement L (u + v) hne,
      Subgroup.mul_mem _ (finiteFormReflectionElement_mem_closure L v hv)
        (finiteFormReflectionElement_mem_closure L (u + v) hne), ?_⟩
    have hfirst : finiteFormReflection L (u + v) hne u = -v := by
      rw [finiteFormReflection_apply_of_two_mul_pairing_eq L (u + v) u hne ?_]
      · abel
      · rw [hadd, BilinModuleCat.pairing_add_left, L.property.2 v u, huv']
        ring
    change finiteFormReflection L v hv (finiteFormReflection L (u + v) hne u) = v
    rw [hfirst, map_neg, finiteFormReflection_apply_self, neg_neg]
  · refine ⟨finiteFormReflectionElement L (u - v) hd,
      finiteFormReflectionElement_mem_closure L (u - v) hd, ?_⟩
    change finiteFormReflection L (u - v) hd u = v
    rw [finiteFormReflection_apply_of_two_mul_pairing_eq L (u - v) u hd ?_]
    · abel
    · rw [hsub, pairing_sub_left, L.property.2 v u]
      ring

end LeanCategories.Lattices.Valued
