/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import LeanCategories.Lattices.Valued.Arithmetic
public import LeanCategories.Lattices.Valued.OrthogonalGroup
public import Mathlib.LinearAlgebra.Dual.Lemmas
public import Mathlib.LinearAlgebra.RootSystem.OfBilinear
public import Mathlib.LinearAlgebra.RootSystem.RootPositive
public import Mathlib.LinearAlgebra.RootSystem.WeylGroup

@[expose] public section

open LeanCategories.Modules.Bilinear.Valued

namespace LeanCategories.Lattices.Valued

universe u

variable {R : Type u} [CommRing R] [IsDomain R]
  [IsPrincipalIdealRing R]

/-- Reflective vectors of a finite projective integral lattice. -/
abbrev ReflectiveRoot (L : FiniteProjectiveLatticeCat R R) :=
  {x : L.obj.obj.carrier | LinearMap.IsReflective L.obj.obj.bilinMap x}

/-- The Mathlib root pairing formed by all reflective lattice vectors. -/
noncomputable def reflectiveRootPairing
    (L : FiniteProjectiveLatticeCat R R)
    (hL : L.obj.obj.IsNondegenerate) (h2 : IsRegular (2 : R)) :
    RootPairing (ReflectiveRoot L) R L.obj.obj.carrier
      (Module.Dual R L.obj.obj.carrier) := by
  letI : Module.Projective R L.obj.obj.carrier := L.obj.property.1
  letI : Module.Finite R L.obj.obj.carrier := L.property
  letI : Module.Free R L.obj.obj.carrier := L.carrier_free
  letI : Module.IsReflexive R L.obj.obj.carrier := inferInstance
  have hinjective : Function.Injective L.obj.obj.adjoint :=
    (L.obj.obj.isNondegenerate_iff_adjoint_injective_of_isSymmetric
      L.obj.property.2).mp hL
  have hseparating : L.obj.obj.bilinMap.SeparatingLeft := by
    intro x hx
    apply hinjective
    apply LinearMap.ext
    intro y
    simpa using hx y
  have hnondegenerate : L.obj.obj.bilinMap.Nondegenerate :=
    LinearMap.BilinForm.Nondegenerate.ofSeparatingLeft hseparating
  have hsymmetric : LinearMap.IsSymm L.obj.obj.bilinMap :=
    ⟨fun x y ↦ by simpa using L.obj.property.2 x y⟩
  exact RootPairing.ofBilinear L.obj.obj.bilinMap
    hnondegenerate hsymmetric h2

/-- The lattice form as an invariant form for its reflective root pairing. -/
noncomputable def reflectiveRootInvariantForm
    (L : FiniteProjectiveLatticeCat R R)
    (hL : L.obj.obj.IsNondegenerate) (h2 : IsRegular (2 : R)) :
    (reflectiveRootPairing L hL h2).InvariantForm := by
  let hsymmetric : LinearMap.IsSymm L.obj.obj.bilinMap :=
    ⟨fun x y ↦ by simpa using L.obj.property.2 x y⟩
  refine
    { form := L.obj.obj.bilinMap
      symm := hsymmetric
      ne_zero := fun i ↦ i.property.regular.ne_zero
      isOrthogonal_reflection := fun i ↦
        i.property.isOrthogonal_reflection L.obj.obj.bilinMap hsymmetric }

/-- The Weyl group generated by all reflective lattice vectors. -/
noncomputable abbrev ReflectiveWeylGroup
    (L : FiniteProjectiveLatticeCat R R)
    (hL : L.obj.obj.IsNondegenerate) (h2 : IsRegular (2 : R)) :=
  (reflectiveRootPairing L hL h2).weylGroup

/-- Every reflective Weyl-group element preserves the lattice form. -/
theorem reflectiveWeyl_preserves_pairing
    (L : FiniteProjectiveLatticeCat R R)
    (hL : L.obj.obj.IsNondegenerate) (h2 : IsRegular (2 : R))
    (g : ReflectiveWeylGroup L hL h2) (x y : L.obj.obj.carrier) :
    L.obj.obj.pairing (g • x) (g • y) = L.obj.obj.pairing x y := by
  exact RootPairing.InvariantForm.apply_weylGroup_smul
    (reflectiveRootPairing L hL h2)
    (B := reflectiveRootInvariantForm L hL h2) g x y

/-- The reflective Weyl group acts through the lattice orthogonal group. -/
noncomputable def reflectiveWeylOrthogonalHom
    (L : FiniteProjectiveLatticeCat R R)
    (hL : L.obj.obj.IsNondegenerate) (h2 : IsRegular (2 : R)) :
    ReflectiveWeylGroup L hL h2 →* OrthogonalGroup L.obj := by
  let P := reflectiveRootPairing L hL h2
  apply MonoidHom.codRestrict
    ((RootPairing.Equiv.weightHom P).restrict P.weylGroup)
    (OrthogonalGroup L.obj)
  intro g x y
  have h := reflectiveWeyl_preserves_pairing L hL h2 g x y
  change L.obj.obj.pairing (g.1.toHom.weightMap x)
    (g.1.toHom.weightMap y) = L.obj.obj.pairing x y at h
  exact h

@[simp]
theorem reflectiveWeylOrthogonalHom_apply
    (L : FiniteProjectiveLatticeCat R R)
    (hL : L.obj.obj.IsNondegenerate) (h2 : IsRegular (2 : R))
    (g : ReflectiveWeylGroup L hL h2) (x : L.obj.obj.carrier) :
    (reflectiveWeylOrthogonalHom L hL h2 g).1 x = g • x :=
  by
    simp only [reflectiveWeylOrthogonalHom,
      MonoidHom.codRestrict_apply, MonoidHom.restrict_apply]
    rfl

/-- The reflection subgroup of `O(L)` generated by reflective roots. -/
noncomputable def reflectiveWeylSubgroup
    (L : FiniteProjectiveLatticeCat R R)
    (hL : L.obj.obj.IsNondegenerate) (h2 : IsRegular (2 : R)) :
    Subgroup (OrthogonalGroup L.obj) :=
  MonoidHom.range (reflectiveWeylOrthogonalHom L hL h2)

end LeanCategories.Lattices.Valued
