/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import LeanCategories.Lattices.Valued.BaseChange

@[expose] public section

open CategoryTheory
open CategoryTheory.Limits
open Opposite
open LeanCategories.Modules.Bilinear.Valued

namespace LeanCategories.Lattices.Valued

universe u

variable (R : Type u) [CommRing R]
variable (W : Type u) [AddCommGroup W] [Module R W]

section Evenness

variable {R}

/-- The quadratic map `x ↦ b(x,x)` associated to an integral lattice. -/
def quadraticMap (L : IntegralLatticeCat R) :
    QuadraticForm R L.obj.carrier :=
  LinearMap.BilinMap.toQuadraticMap L.obj.bilinMap

/-- The scale ideal generated by all pairings. -/
def scaleModule (L : IntegralLatticeCat R) : Ideal R :=
  LinearMap.range L.obj.form

/-- The value ideal generated by the diagonal values `b(x,x)`. -/
def valueModule (L : IntegralLatticeCat R) : Ideal R :=
  Ideal.span (Set.range (quadraticMap L))

/-- The quotient in the defining exact sequence for the scale ideal. -/
abbrev ScaleCokernel (L : IntegralLatticeCat R) := R ⧸ scaleModule L

/-- The quotient in the defining exact sequence for the value ideal. -/
abbrev ValueCokernel (L : IntegralLatticeCat R) := R ⧸ valueModule L

def scaleInclusion (L : IntegralLatticeCat R) : scaleModule L →ₗ[R] R :=
  (scaleModule L).subtype

def scaleProjection (L : IntegralLatticeCat R) : R →ₗ[R] ScaleCokernel L :=
  Submodule.mkQ (scaleModule L)

def valueInclusion (L : IntegralLatticeCat R) : valueModule L →ₗ[R] R :=
  (valueModule L).subtype

def valueProjection (L : IntegralLatticeCat R) : R →ₗ[R] ValueCokernel L :=
  Submodule.mkQ (valueModule L)

/-- Restrict the codomain of a quadratic map to a submodule containing all values. -/
def quadraticMapCodRestrict {M N : Type u} [AddCommGroup M] [Module R M]
    [AddCommGroup N] [Module R N] (Q : QuadraticMap R M N)
    (P : Submodule R N) (hQ : ∀ x, Q x ∈ P) : QuadraticMap R M P where
  toFun x := ⟨Q x, hQ x⟩
  toFun_smul r x := by
    apply Subtype.ext
    exact Q.map_smul r x
  exists_companion' := by
    let B : LinearMap.BilinMap R M P := LinearMap.mk₂ R
      (fun x y ↦ ⟨QuadraticMap.polar Q x y,
        P.sub_mem (P.sub_mem (hQ (x + y)) (hQ x)) (hQ y)⟩)
      (fun x y z ↦ by
        apply Subtype.ext
        exact QuadraticMap.polar_add_left Q x y z)
      (fun r x y ↦ by
        apply Subtype.ext
        exact QuadraticMap.polar_smul_left Q r x y)
      (fun x y z ↦ by
        apply Subtype.ext
        exact QuadraticMap.polar_add_right Q x y z)
      (fun r x y ↦ by
        apply Subtype.ext
        exact QuadraticMap.polar_smul_right Q r x y)
    refine ⟨B, ?_⟩
    intro x y
    apply Subtype.ext
    exact QuadraticMap.map_add Q x y

theorem exact_scaleModule (L : IntegralLatticeCat R) :
    Function.Exact (scaleInclusion L) (scaleProjection L) :=
  LinearMap.exact_subtype_mkQ (scaleModule L)

theorem exact_valueModule (L : IntegralLatticeCat R) :
    Function.Exact (valueInclusion L) (valueProjection L) :=
  LinearMap.exact_subtype_mkQ (valueModule L)

theorem scaleInclusion_injective (L : IntegralLatticeCat R) :
    Function.Injective (scaleInclusion L) :=
  Subtype.val_injective

theorem scaleProjection_surjective (L : IntegralLatticeCat R) :
    Function.Surjective (scaleProjection L) :=
  Submodule.mkQ_surjective _

theorem valueInclusion_injective (L : IntegralLatticeCat R) :
    Function.Injective (valueInclusion L) :=
  Subtype.val_injective

theorem valueProjection_surjective (L : IntegralLatticeCat R) :
    Function.Surjective (valueProjection L) :=
  Submodule.mkQ_surjective _

/-- Quadratic `I`-evenness is a lift of `x ↦ b(x,x)` through `I ↪ R`. -/
def IsQuadraticallyEven (L : IntegralLatticeCat R) (I : Ideal R) : Prop :=
  ∃ qI : QuadraticMap R L.obj.carrier I,
    I.subtype.compQuadraticMap qI = quadraticMap L

/-- Bilinear `I`-evenness is a lift of the tensor form through `I ↪ R`. -/
def IsBilinearlyEven (L : IntegralLatticeCat R) (I : Ideal R) : Prop :=
  ∃ bI : TensorProduct R L.obj.carrier L.obj.carrier →ₗ[R] I,
    I.subtype ∘ₗ bI = L.obj.form

theorem isBilinearlyEven_iff_pairing_mem (L : IntegralLatticeCat R)
    (I : Ideal R) :
    IsBilinearlyEven L I ↔ ∀ x y, L.obj.pairing x y ∈ I := by
  constructor
  · rintro ⟨bI, hbI⟩ x y
    have hxy := LinearMap.congr_fun hbI (x ⊗ₜ[R] y)
    change I.subtype (bI (x ⊗ₜ[R] y)) = L.obj.pairing x y at hxy
    rw [← hxy]
    exact (bI (x ⊗ₜ[R] y)).property
  · intro h
    let bI : TensorProduct R L.obj.carrier L.obj.carrier →ₗ[R] I :=
      LinearMap.codRestrict I L.obj.form (by
        intro z
        induction z using TensorProduct.induction_on with
        | zero => simp
        | tmul x y => exact h x y
        | add x y hx hy => simpa using I.add_mem hx hy)
    refine ⟨bI, ?_⟩
    ext z
    rfl

theorem isQuadraticallyEven_iff_value_mem
    (L : IntegralLatticeCat R) (I : Ideal R) :
    IsQuadraticallyEven L I ↔ ∀ x, quadraticMap L x ∈ I := by
  constructor
  · rintro ⟨qI, hqI⟩ x
    have hx := QuadraticMap.congr_fun hqI x
    change I.subtype (qI x) = quadraticMap L x at hx
    rw [← hx]
    exact (qI x).property
  · intro h
    refine ⟨quadraticMapCodRestrict (quadraticMap L) I h, ?_⟩
    ext x
    rfl

theorem isQuadraticallyEven_of_isBilinearlyEven
    (L : IntegralLatticeCat R) (I : Ideal R)
    (hL : IsBilinearlyEven L I) : IsQuadraticallyEven L I := by
  rcases hL with ⟨bI, hbI⟩
  let bI' : LinearMap.BilinMap R L.obj.carrier I :=
    (TensorProduct.lift.equiv (.id R) L.obj.carrier L.obj.carrier I).symm bI
  refine ⟨LinearMap.BilinMap.toQuadraticMap bI', ?_⟩
  ext x
  simp only [LinearMap.compQuadraticMap_apply,
    LinearMap.BilinMap.toQuadraticMap_apply]
  change I.subtype (bI (x ⊗ₜ[R] x)) = L.obj.form (x ⊗ₜ[R] x)
  exact LinearMap.congr_fun hbI (x ⊗ₜ[R] x)

theorem isBilinearlyEven_of_isQuadraticallyEven_of_invertible_two
    [Invertible (2 : R)] (L : IntegralLatticeCat R) (I : Ideal R)
    (hL : IsQuadraticallyEven L I) : IsBilinearlyEven L I := by
  rw [isBilinearlyEven_iff_pairing_mem]
  rw [isQuadraticallyEven_iff_value_mem] at hL
  intro x y
  have hPolar : QuadraticMap.polar (quadraticMap L) x y ∈ I :=
    I.sub_mem (I.sub_mem (hL (x + y)) (hL x)) (hL y)
  have hPolarEq :
      QuadraticMap.polar (quadraticMap L) x y =
        (2 : R) • L.obj.pairing x y := by
    rw [quadraticMap, LinearMap.BilinMap.polar_toQuadraticMap]
    change L.obj.pairing x y + L.obj.pairing y x =
      (2 : R) • L.obj.pairing x y
    rw [← L.property.2.2 x y]
    rw [two_smul R]
  rw [hPolarEq] at hPolar
  have hScaled := I.smul_mem (⅟(2 : R)) hPolar
  simpa [smul_smul, invOf_mul_self] using hScaled

theorem isQuadraticallyEven_top (L : IntegralLatticeCat R) :
    IsQuadraticallyEven L (⊤ : Ideal R) := by
  refine ⟨Submodule.topEquiv.symm.toLinearMap.compQuadraticMap
    (quadraticMap L), ?_⟩
  ext x
  rfl

theorem isBilinearlyEven_top (L : IntegralLatticeCat R) :
    IsBilinearlyEven L (⊤ : Ideal R) := by
  refine ⟨Submodule.topEquiv.symm.toLinearMap ∘ₗ L.obj.form, ?_⟩
  ext x
  rfl

theorem isQuadraticallyEven_of_eq_top (L : IntegralLatticeCat R)
    (I : Ideal R) (hI : I = ⊤) : IsQuadraticallyEven L I := by
  subst I
  exact isQuadraticallyEven_top L

theorem isBilinearlyEven_of_eq_top (L : IntegralLatticeCat R)
    (I : Ideal R) (hI : I = ⊤) : IsBilinearlyEven L I := by
  subst I
  exact isBilinearlyEven_top L

theorem isQuadraticallyEven_span_singleton_of_isUnit
    (L : IntegralLatticeCat R) (a : R) (ha : IsUnit a) :
    IsQuadraticallyEven L (Ideal.span {a}) :=
  isQuadraticallyEven_of_eq_top L _
    (Ideal.span_singleton_eq_top.mpr ha)

theorem isBilinearlyEven_span_singleton_of_isUnit
    (L : IntegralLatticeCat R) (a : R) (ha : IsUnit a) :
    IsBilinearlyEven L (Ideal.span {a}) :=
  isBilinearlyEven_of_eq_top L _
    (Ideal.span_singleton_eq_top.mpr ha)

/-- Classical evenness is quadratic `2R`-evenness. -/
abbrev IsEven (L : IntegralLatticeCat R) : Prop :=
  IsQuadraticallyEven L (Ideal.span {(2 : R)})

section BaseChangeEvenness

variable (S : Type u) [CommRing S] [Algebra R S]

@[simp]
theorem baseChangeIntegral_pairing_tmul (L : IntegralLatticeCat R)
    (a b : S) (x y : L.obj.carrier) :
    ((baseChangeIntegral R S).obj L).obj.pairing
        (a ⊗ₜ[R] x) (b ⊗ₜ[R] y) =
      (a * b) * algebraMap R S (L.obj.pairing x y) := by
  change (TensorProduct.AlgebraTensorModule.rid R S S)
      ((a * b) ⊗ₜ[R] L.obj.pairing x y) = _
  simp [Algebra.smul_def, mul_comm]

theorem baseChangeIntegral_pairing_zero_left (L : IntegralLatticeCat R)
    (y : TensorProduct R S L.obj.carrier) :
    ((baseChangeIntegral R S).obj L).obj.pairing 0 y = 0 :=
  BilinModuleCat.pairing_zero_left ((baseChangeIntegral R S).obj L).obj y

theorem baseChangeIntegral_pairing_zero_right (L : IntegralLatticeCat R)
    (x : TensorProduct R S L.obj.carrier) :
    ((baseChangeIntegral R S).obj L).obj.pairing x 0 = 0 :=
  BilinModuleCat.pairing_zero_right ((baseChangeIntegral R S).obj L).obj x

@[simp]
theorem baseChangeIntegral_pairing_add_left (L : IntegralLatticeCat R)
    (x y z : TensorProduct R S L.obj.carrier) :
    ((baseChangeIntegral R S).obj L).obj.pairing (x + y) z =
      ((baseChangeIntegral R S).obj L).obj.pairing x z +
        ((baseChangeIntegral R S).obj L).obj.pairing y z :=
  BilinModuleCat.pairing_add_left ((baseChangeIntegral R S).obj L).obj x y z

@[simp]
theorem baseChangeIntegral_pairing_add_right (L : IntegralLatticeCat R)
    (x y z : TensorProduct R S L.obj.carrier) :
    ((baseChangeIntegral R S).obj L).obj.pairing x (y + z) =
      ((baseChangeIntegral R S).obj L).obj.pairing x y +
        ((baseChangeIntegral R S).obj L).obj.pairing x z :=
  BilinModuleCat.pairing_add_right ((baseChangeIntegral R S).obj L).obj x y z

theorem baseChangeIntegral_quadraticMap_add (L : IntegralLatticeCat R)
    (x y : TensorProduct R S L.obj.carrier) :
    quadraticMap ((baseChangeIntegral R S).obj L) (x + y) =
      quadraticMap ((baseChangeIntegral R S).obj L) x +
        quadraticMap ((baseChangeIntegral R S).obj L) y +
          (((baseChangeIntegral R S).obj L).obj.pairing x y +
            ((baseChangeIntegral R S).obj L).obj.pairing y x) := by
  change ((baseChangeIntegral R S).obj L).obj.pairing (x + y) (x + y) = _
  rw [baseChangeIntegral_pairing_add_left (R := R) S L,
    baseChangeIntegral_pairing_add_right (R := R) S L,
    baseChangeIntegral_pairing_add_right (R := R) S L]
  simp only [quadraticMap, LinearMap.BilinMap.toQuadraticMap_apply,
    BilinModuleCat.bilinMap_apply]
  abel

theorem symmetrized_pairing_mem_of_isQuadraticallyEven
    (L : IntegralLatticeCat R) (I : Ideal R)
    (hL : IsQuadraticallyEven L I) (x y : L.obj.carrier) :
    L.obj.pairing x y + L.obj.pairing y x ∈ I := by
  rw [isQuadraticallyEven_iff_value_mem] at hL
  have h := I.sub_mem (I.sub_mem (hL (x + y)) (hL x)) (hL y)
  change QuadraticMap.polar (quadraticMap L) x y ∈ I at h
  rw [quadraticMap, LinearMap.BilinMap.polar_toQuadraticMap] at h
  exact h

theorem baseChangeIntegral_symmetrized_pairing_mem
    (L : IntegralLatticeCat R) (I : Ideal R)
    (hL : IsQuadraticallyEven L I)
    (x y : TensorProduct R S L.obj.carrier) :
    ((baseChangeIntegral R S).obj L).obj.pairing x y +
      ((baseChangeIntegral R S).obj L).obj.pairing y x ∈
        Ideal.map (algebraMap R S) I := by
  induction x using TensorProduct.induction_on with
  | zero =>
    have hEq :
        ((baseChangeIntegral R S).obj L).obj.pairing 0 y +
          ((baseChangeIntegral R S).obj L).obj.pairing y 0 = 0 := by
      rw [baseChangeIntegral_pairing_zero_left (R := R) S L y,
        baseChangeIntegral_pairing_zero_right (R := R) S L y, zero_add]
    exact hEq.symm ▸ (Ideal.map (algebraMap R S) I).zero_mem
  | tmul a x =>
    induction y using TensorProduct.induction_on with
    | zero =>
      have hEq :
          ((baseChangeIntegral R S).obj L).obj.pairing (a ⊗ₜ[R] x) 0 +
            ((baseChangeIntegral R S).obj L).obj.pairing 0 (a ⊗ₜ[R] x) = 0 := by
        rw [baseChangeIntegral_pairing_zero_right (R := R) S L (a ⊗ₜ[R] x),
          baseChangeIntegral_pairing_zero_left (R := R) S L (a ⊗ₜ[R] x),
          zero_add]
      exact hEq.symm ▸ (Ideal.map (algebraMap R S) I).zero_mem
    | tmul b y =>
      have hxy := symmetrized_pairing_mem_of_isQuadraticallyEven L I hL x y
      have hMap : algebraMap R S
          (L.obj.pairing x y + L.obj.pairing y x) ∈
          Ideal.map (algebraMap R S) I :=
        Ideal.mem_map_of_mem (algebraMap R S) hxy
      have hMul := (Ideal.map (algebraMap R S) I).smul_mem (a * b) hMap
      simpa [baseChangeIntegral_pairing_tmul, map_add, Algebra.smul_def,
        mul_add, mul_comm, mul_left_comm, mul_assoc] using hMul
    | add y₁ y₂ hy₁ hy₂ =>
      rw [baseChangeIntegral_pairing_add_right,
        baseChangeIntegral_pairing_add_left]
      convert (Ideal.map (algebraMap R S) I).add_mem hy₁ hy₂ using 1
      all_goals abel
  | add x₁ x₂ hx₁ hx₂ =>
    rw [baseChangeIntegral_pairing_add_left,
      baseChangeIntegral_pairing_add_right]
    convert (Ideal.map (algebraMap R S) I).add_mem hx₁ hx₂ using 1
    all_goals abel

theorem baseChangeIntegral_isQuadraticallyEven
    (L : IntegralLatticeCat R) (I : Ideal R)
    (hL : IsQuadraticallyEven L I) :
    IsQuadraticallyEven ((baseChangeIntegral R S).obj L)
      (Ideal.map (algebraMap R S) I) := by
  rw [isQuadraticallyEven_iff_value_mem]
  intro x
  change TensorProduct R S L.obj.carrier at x
  induction x using TensorProduct.induction_on with
  | zero =>
    change 0 ∈ Ideal.map (algebraMap R S) I
    exact (Ideal.map (algebraMap R S) I).zero_mem
  | tmul a x =>
    change ((baseChangeIntegral R S).obj L).obj.pairing
      (a ⊗ₜ[R] x) (a ⊗ₜ[R] x) ∈ Ideal.map (algebraMap R S) I
    rw [baseChangeIntegral_pairing_tmul]
    rw [isQuadraticallyEven_iff_value_mem] at hL
    have hx := hL x
    change L.obj.pairing x x ∈ I at hx
    have hMap : algebraMap R S (L.obj.pairing x x) ∈
        Ideal.map (algebraMap R S) I :=
      Ideal.mem_map_of_mem (algebraMap R S) hx
    simpa [Algebra.smul_def] using
      (Ideal.map (algebraMap R S) I).smul_mem (a * a) hMap
  | add x y hx hy =>
    have hSym := baseChangeIntegral_symmetrized_pairing_mem S L I hL x y
    rw [baseChangeIntegral_quadraticMap_add (R := R) S L x y]
    exact (Ideal.map (algebraMap R S) I).add_mem
      ((Ideal.map (algebraMap R S) I).add_mem hx hy) hSym

theorem baseChangeIntegral_isBilinearlyEven
    (L : IntegralLatticeCat R) (I : Ideal R)
    (hL : IsBilinearlyEven L I) :
    IsBilinearlyEven ((baseChangeIntegral R S).obj L)
      (Ideal.map (algebraMap R S) I) := by
  rw [isBilinearlyEven_iff_pairing_mem] at hL ⊢
  intro x y
  change TensorProduct R S L.obj.carrier at x y
  induction x using TensorProduct.induction_on with
  | zero =>
    exact (baseChangeIntegral_pairing_zero_left (R := R) S L y).symm ▸
      (Ideal.map (algebraMap R S) I).zero_mem
  | tmul a x =>
    induction y using TensorProduct.induction_on with
    | zero =>
      exact (baseChangeIntegral_pairing_zero_right (R := R) S L
        (a ⊗ₜ[R] x)).symm ▸ (Ideal.map (algebraMap R S) I).zero_mem
    | tmul b y =>
      have hxy : algebraMap R S (L.obj.pairing x y) ∈
          Ideal.map (algebraMap R S) I :=
        Ideal.mem_map_of_mem (algebraMap R S) (hL x y)
      simpa [baseChangeIntegral_pairing_tmul, Algebra.smul_def] using
        (Ideal.map (algebraMap R S) I).smul_mem (a * b) hxy
    | add y₁ y₂ hy₁ hy₂ =>
      rw [baseChangeIntegral_pairing_add_right]
      exact (Ideal.map (algebraMap R S) I).add_mem hy₁ hy₂
  | add x₁ x₂ hx₁ hx₂ =>
    rw [baseChangeIntegral_pairing_add_left]
    exact (Ideal.map (algebraMap R S) I).add_mem hx₁ hx₂

end BaseChangeEvenness

end Evenness

end LeanCategories.Lattices.Valued

