/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import LeanCategories.Lattices.Valued.Arithmetic
public import LeanCategories.Lattices.Valued.Constructions
public import LeanCategories.Lattices.Valued.ScaleAndEvenness
public import LeanCategories.Lattices.Valued.Signature
public import Mathlib.LinearAlgebra.Basis.Prod
public import Mathlib.LinearAlgebra.Matrix.Notation

@[expose] public section

open LeanCategories.Modules.Bilinear.Valued

namespace LeanCategories.Lattices.Valued

/-- The Gram matrix of the rank-zero lattice. -/
def rankZeroGramMatrix : Matrix (Fin 0) (Fin 0) ℤ := 0

theorem rankZeroGramMatrix_isSymm : rankZeroGramMatrix.IsSymm :=
  Matrix.IsSymm.ext fun i ↦ Fin.elim0 i

/-- The unique integral lattice of rank zero. -/
def rankZeroLattice : IntegralLatticeCat ℤ := by
  refine ⟨BilinModuleCat.ofBilinMap
    (Matrix.toBilin' rankZeroGramMatrix), ?_, ?_⟩
  · change Module.Projective ℤ (Fin 0 → ℤ)
    infer_instance
  · intro x y
    exact (Matrix.isSymm_toBilin'_iff_isSymm.mpr
      rankZeroGramMatrix_isSymm).eq x y

/-- The rank-zero lattice is finite projective. -/
def rankZeroFiniteLattice : FiniteProjectiveLatticeCat ℤ ℤ := by
  refine ⟨rankZeroLattice, ?_⟩
  change Module.Finite ℤ (Fin 0 → ℤ)
  infer_instance

/-- The standard empty basis has the rank-zero Gram matrix. -/
theorem rankZeroLattice_gramMatrix :
    gramMatrix rankZeroLattice (Pi.basisFun ℤ (Fin 0)) =
      rankZeroGramMatrix :=
  LinearMap.BilinForm.toMatrix'_toBilin' rankZeroGramMatrix

/-- The rank-zero lattice is unimodular. -/
theorem rankZeroLattice_isUnimodular : IsUnimodular rankZeroLattice := by
  rw [isUnimodular_iff_isUnit_determinant rankZeroLattice
    (Pi.basisFun ℤ (Fin 0))]
  simp [determinant, rankZeroLattice_gramMatrix, rankZeroGramMatrix]

/-- The Gram matrix of the rank-one lattice with square `a`. -/
def rankOneGramMatrix (a : ℤ) : Matrix (Fin 1) (Fin 1) ℤ := !![a]

/-- The rank-one integral lattice generated by a vector of square `a`. -/
def rankOneLattice (a : ℤ) : IntegralLatticeCat ℤ := by
  refine ⟨BilinModuleCat.ofBilinMap
    (Matrix.toBilin' (rankOneGramMatrix a)), ?_, ?_⟩
  · change Module.Projective ℤ (Fin 1 → ℤ)
    infer_instance
  · intro x y
    exact (Matrix.isSymm_toBilin'_iff_isSymm.mpr
      (Matrix.IsSymm.ext fun i j ↦ by
        fin_cases i
        fin_cases j
        rfl)).eq x y

/-- Every standard rank-one lattice is finite projective. -/
def rankOneFiniteLattice (a : ℤ) : FiniteProjectiveLatticeCat ℤ ℤ := by
  refine ⟨rankOneLattice a, ?_⟩
  change Module.Finite ℤ (Fin 1 → ℤ)
  infer_instance

/-- The standard basis has the selected rank-one Gram matrix. -/
theorem rankOneLattice_gramMatrix (a : ℤ) :
    gramMatrix (rankOneLattice a) (Pi.basisFun ℤ (Fin 1)) =
      rankOneGramMatrix a :=
  LinearMap.BilinForm.toMatrix'_toBilin' (rankOneGramMatrix a)

/-- The determinant of a rank-one lattice is its selected square. -/
@[simp]
theorem rankOneLattice_determinant (a : ℤ) :
    determinant (rankOneLattice a) (Pi.basisFun ℤ (Fin 1)) = a := by
  rw [determinant, rankOneLattice_gramMatrix]
  simp [rankOneGramMatrix]

/-- A rank-one lattice is unimodular exactly when its square is a unit. -/
theorem rankOneLattice_isUnimodular_iff (a : ℤ) :
    IsUnimodular (rankOneLattice a) ↔ IsUnit a := by
  rw [isUnimodular_iff_isUnit_determinant
    (rankOneLattice a) (Pi.basisFun ℤ (Fin 1))]
  simp

/-- The integral lattice represented by a symmetric integer matrix. -/
def latticeOfGramMatrix {n : ℕ} (A : Matrix (Fin n) (Fin n) ℤ)
    (hA : A.IsSymm) : IntegralLatticeCat ℤ := by
  refine ⟨BilinModuleCat.ofBilinMap (Matrix.toBilin' A), ?_, ?_⟩
  · change Module.Projective ℤ (Fin n → ℤ)
    infer_instance
  · intro x y
    exact (Matrix.isSymm_toBilin'_iff_isSymm.mpr hA).eq x y

/-- A symmetric integer Gram matrix gives a finite projective lattice. -/
def finiteLatticeOfGramMatrix {n : ℕ}
    (A : Matrix (Fin n) (Fin n) ℤ) (hA : A.IsSymm) :
    FiniteProjectiveLatticeCat ℤ ℤ := by
  refine ⟨latticeOfGramMatrix A hA, ?_⟩
  change Module.Finite ℤ (Fin n → ℤ)
  infer_instance

/-- The standard basis recovers the selected symmetric Gram matrix. -/
theorem latticeOfGramMatrix_gramMatrix {n : ℕ}
    (A : Matrix (Fin n) (Fin n) ℤ) (hA : A.IsSymm) :
    gramMatrix (latticeOfGramMatrix A hA) (Pi.basisFun ℤ (Fin n)) = A :=
  LinearMap.BilinForm.toMatrix'_toBilin' A

/-- An even diagonal gives an even matrix lattice. -/
theorem latticeOfGramMatrix_isEven {n : ℕ}
    (A : Matrix (Fin n) (Fin n) ℤ) (hA : A.IsSymm)
    (hDiag : ∀ i, A i i ∈ Ideal.span {(2 : ℤ)}) :
    IsEven (latticeOfGramMatrix A hA) := by
  apply isEven_of_basis (latticeOfGramMatrix A hA)
    (Pi.basisFun ℤ (Fin n))
  intro i
  change Matrix.toBilin' A
    ((Pi.basisFun ℤ (Fin n)) i) ((Pi.basisFun ℤ (Fin n)) i) ∈ _
  simpa only [Pi.basisFun_apply, Matrix.toBilin'_single] using hDiag i

/-- The standard coordinate roots `eᵢ - eᵢ₊₁` for type `A`. -/
def aRootVector (n : ℕ) (i : Fin n) (k : Fin (n + 1)) : ℤ :=
  if k.val = i.val then 1 else if k.val = i.val + 1 then -1 else 0

/-- The negative inner-product matrix of the standard type-`A` roots. -/
def aRootGramMatrix (n : ℕ) : Matrix (Fin n) (Fin n) ℤ :=
  fun i j ↦ -∑ k, aRootVector n i k * aRootVector n j k

theorem aRootGramMatrix_isSymm (n : ℕ) :
    (aRootGramMatrix n).IsSymm :=
  Matrix.IsSymm.ext fun i j ↦ by
    simp only [aRootGramMatrix]
    congr 1
    apply Finset.sum_congr rfl
    intro k _
    ring

/-- The negative-definite root lattice of type `A` and rank `n`. -/
def aRootLattice (n : ℕ) : IntegralLatticeCat ℤ :=
  latticeOfGramMatrix (aRootGramMatrix n) (aRootGramMatrix_isSymm n)

/-- The finite projective negative type-`A` root lattice. -/
def aRootFiniteLattice (n : ℕ) : FiniteProjectiveLatticeCat ℤ ℤ :=
  finiteLatticeOfGramMatrix
    (aRootGramMatrix n) (aRootGramMatrix_isSymm n)

/-- The standard type-`A` basis has the root inner-product matrix. -/
theorem aRootLattice_gramMatrix (n : ℕ) :
    gramMatrix (aRootLattice n) (Pi.basisFun ℤ (Fin n)) =
      aRootGramMatrix n :=
  latticeOfGramMatrix_gramMatrix _ _

/-- The standard coordinate roots for type `D` in rank at least four. -/
def dRootVector (n : ℕ) (_hn : 4 ≤ n) (i k : Fin n) : ℤ :=
  if i.val + 1 < n then
    if k.val = i.val then 1 else if k.val = i.val + 1 then -1 else 0
  else if k.val + 2 = n ∨ k.val + 1 = n then 1 else 0

/-- The negative inner-product matrix of the standard type-`D` roots. -/
def dRootGramMatrix (n : ℕ) (hn : 4 ≤ n) : Matrix (Fin n) (Fin n) ℤ :=
  fun i j ↦ -∑ k, dRootVector n hn i k * dRootVector n hn j k

theorem dRootGramMatrix_isSymm (n : ℕ) (hn : 4 ≤ n) :
    (dRootGramMatrix n hn).IsSymm :=
  Matrix.IsSymm.ext fun i j ↦ by
    simp only [dRootGramMatrix]
    congr 1
    apply Finset.sum_congr rfl
    intro k _
    ring

/-- The negative-definite root lattice of type `D` and rank `n`. -/
def dRootLattice (n : ℕ) (hn : 4 ≤ n) : IntegralLatticeCat ℤ :=
  latticeOfGramMatrix
    (dRootGramMatrix n hn) (dRootGramMatrix_isSymm n hn)

/-- The finite projective negative type-`D` root lattice. -/
def dRootFiniteLattice (n : ℕ) (hn : 4 ≤ n) :
    FiniteProjectiveLatticeCat ℤ ℤ :=
  finiteLatticeOfGramMatrix
    (dRootGramMatrix n hn) (dRootGramMatrix_isSymm n hn)

/-- The standard type-`D` basis has the root inner-product matrix. -/
theorem dRootLattice_gramMatrix (n : ℕ) (hn : 4 ≤ n) :
    gramMatrix (dRootLattice n hn) (Pi.basisFun ℤ (Fin n)) =
      dRootGramMatrix n hn :=
  latticeOfGramMatrix_gramMatrix _ _

/-- Twice the coordinates of a standard simple-root basis for `E₈`. -/
def e8RootNumerator : Fin 8 → Fin 8 → ℤ := ![
  ![ 1, -1, -1, -1, -1, -1, -1,  1],
  ![ 2,  2,  0,  0,  0,  0,  0,  0],
  ![-2,  2,  0,  0,  0,  0,  0,  0],
  ![ 0, -2,  2,  0,  0,  0,  0,  0],
  ![ 0,  0, -2,  2,  0,  0,  0,  0],
  ![ 0,  0,  0, -2,  2,  0,  0,  0],
  ![ 0,  0,  0,  0, -2,  2,  0,  0],
  ![ 0,  0,  0,  0,  0, -2,  2,  0]]

/-- The inner products of the doubled roots are exactly divisible by four. -/
theorem e8RootDot_exists (i j : Fin 8) :
    ∃ z : ℤ, ∑ k, e8RootNumerator i k * e8RootNumerator j k = 4 * z := by
  fin_cases i <;> fin_cases j <;>
    norm_num [e8RootNumerator, Fin.sum_univ_succ]
  all_goals first
    | exact ⟨2, by decide⟩
    | exact ⟨-1, by decide⟩

/-- The exact integral inner product of two standard `E₈` roots. -/
noncomputable def e8RootInnerProduct (i j : Fin 8) : ℤ :=
  Classical.choose (e8RootDot_exists i j)

theorem e8RootInnerProduct_spec (i j : Fin 8) :
    ∑ k, e8RootNumerator i k * e8RootNumerator j k =
      4 * e8RootInnerProduct i j :=
  Classical.choose_spec (e8RootDot_exists i j)

theorem e8RootInnerProduct_comm (i j : Fin 8) :
    e8RootInnerProduct i j = e8RootInnerProduct j i := by
  apply mul_left_cancel₀ (show (4 : ℤ) ≠ 0 by norm_num)
  rw [← e8RootInnerProduct_spec i j, ← e8RootInnerProduct_spec j i]
  apply Finset.sum_congr rfl
  intro k _
  ring

/-- The negative `E₈` Gram matrix derived from the standard roots above. -/
noncomputable def e8GramMatrix : Matrix (Fin 8) (Fin 8) ℤ :=
  fun i j ↦ -e8RootInnerProduct i j

theorem e8GramMatrix_isSymm : e8GramMatrix.IsSymm :=
  Matrix.IsSymm.ext fun i j ↦ by
    simp only [e8GramMatrix]
    rw [e8RootInnerProduct_comm]

/-- The root construction gives the standard negative `E₈` matrix. -/
theorem e8GramMatrix_eq : e8GramMatrix = ![
    ![-2,  0,  1,  0,  0,  0,  0,  0],
    ![ 0, -2,  0,  1,  0,  0,  0,  0],
    ![ 1,  0, -2,  1,  0,  0,  0,  0],
    ![ 0,  1,  1, -2,  1,  0,  0,  0],
    ![ 0,  0,  0,  1, -2,  1,  0,  0],
    ![ 0,  0,  0,  0,  1, -2,  1,  0],
    ![ 0,  0,  0,  0,  0,  1, -2,  1],
    ![ 0,  0,  0,  0,  0,  0,  1, -2]] := by
  ext i j
  have h := e8RootInnerProduct_spec i j
  fin_cases i <;> fin_cases j <;>
    norm_num [e8GramMatrix, e8RootNumerator, Fin.sum_univ_succ] at h ⊢ <;>
    omega

/-- Twice the coordinates of the first six roots in the selected `E₈` presentation. -/
def e6RootNumerator (i : Fin 6) : Fin 8 → ℤ :=
  e8RootNumerator (Fin.castLE (by omega) i)

/-- The exact inner product of two roots in the selected `E₆` presentation. -/
noncomputable def e6RootInnerProduct (i j : Fin 6) : ℤ :=
  e8RootInnerProduct
    (Fin.castLE (by omega) i) (Fin.castLE (by omega) j)

theorem e6RootInnerProduct_spec (i j : Fin 6) :
    ∑ k, e6RootNumerator i k * e6RootNumerator j k =
      4 * e6RootInnerProduct i j :=
  e8RootInnerProduct_spec
    (Fin.castLE (by omega) i) (Fin.castLE (by omega) j)

theorem e6RootInnerProduct_comm (i j : Fin 6) :
    e6RootInnerProduct i j = e6RootInnerProduct j i :=
  e8RootInnerProduct_comm
    (Fin.castLE (by omega) i) (Fin.castLE (by omega) j)

/-- The negative `E₆` Gram matrix derived from the selected roots. -/
noncomputable def e6GramMatrix : Matrix (Fin 6) (Fin 6) ℤ :=
  fun i j ↦ -e6RootInnerProduct i j

theorem e6GramMatrix_isSymm : e6GramMatrix.IsSymm :=
  Matrix.IsSymm.ext fun i j ↦ by
    simp only [e6GramMatrix]
    rw [e6RootInnerProduct_comm]

/-- The selected roots give the standard negative `E₆` matrix. -/
theorem e6GramMatrix_eq : e6GramMatrix = ![
    ![-2,  0,  1,  0,  0,  0],
    ![ 0, -2,  0,  1,  0,  0],
    ![ 1,  0, -2,  1,  0,  0],
    ![ 0,  1,  1, -2,  1,  0],
    ![ 0,  0,  0,  1, -2,  1],
    ![ 0,  0,  0,  0,  1, -2]] := by
  ext i j
  change e8GramMatrix
    (Fin.castLE (by omega) i) (Fin.castLE (by omega) j) = _
  rw [e8GramMatrix_eq]
  fin_cases i <;> fin_cases j <;> norm_num [Fin.castLE]

/-- The negative-definite root lattice of type `E₆`. -/
noncomputable def e6Lattice : IntegralLatticeCat ℤ :=
  latticeOfGramMatrix e6GramMatrix e6GramMatrix_isSymm

/-- The finite projective negative type-`E₆` root lattice. -/
noncomputable def e6FiniteLattice : FiniteProjectiveLatticeCat ℤ ℤ :=
  finiteLatticeOfGramMatrix e6GramMatrix e6GramMatrix_isSymm

/-- The simple-root basis has the selected negative `E₆` Gram matrix. -/
theorem e6Lattice_gramMatrix :
    gramMatrix e6Lattice (Pi.basisFun ℤ (Fin 6)) = e6GramMatrix :=
  latticeOfGramMatrix_gramMatrix _ _

/-- The determinant of the selected negative `E₆` matrix is three. -/
theorem e6GramMatrix_det : e6GramMatrix.det = 3 := by
  rw [e6GramMatrix_eq]
  set_option maxRecDepth 10000 in decide

/-- The standard basis computes the determinant of the negative `E₆` lattice. -/
theorem e6Lattice_determinant :
    determinant e6Lattice (Pi.basisFun ℤ (Fin 6)) = 3 := by
  rw [determinant, e6Lattice_gramMatrix, e6GramMatrix_det]

/-- The negative `E₆` lattice is even. -/
theorem e6Lattice_isEven : IsEven e6Lattice := by
  apply latticeOfGramMatrix_isEven e6GramMatrix e6GramMatrix_isSymm
  intro i
  rw [Ideal.mem_span_singleton, e6GramMatrix_eq]
  refine ⟨-1, ?_⟩
  fin_cases i <;> norm_num

/-- Twice the coordinates of the first seven roots in the selected `E₈` presentation. -/
def e7RootNumerator (i : Fin 7) : Fin 8 → ℤ :=
  e8RootNumerator (Fin.castLE (by omega) i)

/-- The exact inner product of two roots in the selected `E₇` presentation. -/
noncomputable def e7RootInnerProduct (i j : Fin 7) : ℤ :=
  e8RootInnerProduct
    (Fin.castLE (by omega) i) (Fin.castLE (by omega) j)

theorem e7RootInnerProduct_spec (i j : Fin 7) :
    ∑ k, e7RootNumerator i k * e7RootNumerator j k =
      4 * e7RootInnerProduct i j :=
  e8RootInnerProduct_spec
    (Fin.castLE (by omega) i) (Fin.castLE (by omega) j)

theorem e7RootInnerProduct_comm (i j : Fin 7) :
    e7RootInnerProduct i j = e7RootInnerProduct j i :=
  e8RootInnerProduct_comm
    (Fin.castLE (by omega) i) (Fin.castLE (by omega) j)

/-- The negative `E₇` Gram matrix derived from the selected roots. -/
noncomputable def e7GramMatrix : Matrix (Fin 7) (Fin 7) ℤ :=
  fun i j ↦ -e7RootInnerProduct i j

theorem e7GramMatrix_isSymm : e7GramMatrix.IsSymm :=
  Matrix.IsSymm.ext fun i j ↦ by
    simp only [e7GramMatrix]
    rw [e7RootInnerProduct_comm]

/-- The selected roots give the standard negative `E₇` matrix. -/
theorem e7GramMatrix_eq : e7GramMatrix = ![
    ![-2,  0,  1,  0,  0,  0,  0],
    ![ 0, -2,  0,  1,  0,  0,  0],
    ![ 1,  0, -2,  1,  0,  0,  0],
    ![ 0,  1,  1, -2,  1,  0,  0],
    ![ 0,  0,  0,  1, -2,  1,  0],
    ![ 0,  0,  0,  0,  1, -2,  1],
    ![ 0,  0,  0,  0,  0,  1, -2]] := by
  ext i j
  change e8GramMatrix
    (Fin.castLE (by omega) i) (Fin.castLE (by omega) j) = _
  rw [e8GramMatrix_eq]
  fin_cases i <;> fin_cases j <;> norm_num [Fin.castLE]

/-- The negative-definite root lattice of type `E₇`. -/
noncomputable def e7Lattice : IntegralLatticeCat ℤ :=
  latticeOfGramMatrix e7GramMatrix e7GramMatrix_isSymm

/-- The finite projective negative type-`E₇` root lattice. -/
noncomputable def e7FiniteLattice : FiniteProjectiveLatticeCat ℤ ℤ :=
  finiteLatticeOfGramMatrix e7GramMatrix e7GramMatrix_isSymm

/-- The simple-root basis has the selected negative `E₇` Gram matrix. -/
theorem e7Lattice_gramMatrix :
    gramMatrix e7Lattice (Pi.basisFun ℤ (Fin 7)) = e7GramMatrix :=
  latticeOfGramMatrix_gramMatrix _ _

/-- The negative `E₇` lattice is even. -/
theorem e7Lattice_isEven : IsEven e7Lattice := by
  apply latticeOfGramMatrix_isEven e7GramMatrix e7GramMatrix_isSymm
  intro i
  rw [Ideal.mem_span_singleton, e7GramMatrix_eq]
  refine ⟨-1, ?_⟩
  fin_cases i <;> norm_num

/-- The negative definite `E₈` root lattice in its simple-root basis. -/
noncomputable def e8Lattice : IntegralLatticeCat ℤ := by
  refine ⟨BilinModuleCat.ofBilinMap (Matrix.toBilin' e8GramMatrix), ?_, ?_⟩
  · change Module.Projective ℤ (Fin 8 → ℤ)
    infer_instance
  · intro x y
    exact (Matrix.isSymm_toBilin'_iff_isSymm.mpr
      e8GramMatrix_isSymm).eq x y

/-- The negative `E₈` lattice as a finite projective lattice. -/
noncomputable def e8FiniteLattice : FiniteProjectiveLatticeCat ℤ ℤ := by
  refine ⟨e8Lattice, ?_⟩
  change Module.Finite ℤ (Fin 8 → ℤ)
  infer_instance

@[simp]
theorem e8Lattice_pairing (x y : e8Lattice.obj.carrier) :
    e8Lattice.obj.pairing x y = Matrix.toBilin' e8GramMatrix x y :=
  rfl

/-- The simple-root basis has the standard `E₈` Gram matrix. -/
theorem e8Lattice_gramMatrix :
    gramMatrix e8Lattice (Pi.basisFun ℤ (Fin 8)) = e8GramMatrix := by
  exact LinearMap.BilinForm.toMatrix'_toBilin' e8GramMatrix

/-- An integral inverse for the negative `E₈` Gram matrix. -/
def e8GramMatrixInverse : Matrix (Fin 8) (Fin 8) ℤ := ![
  ![ -4,  -5,  -7, -10,  -8,  -6, -4, -2],
  ![ -5,  -8, -10, -15, -12,  -9, -6, -3],
  ![ -7, -10, -14, -20, -16, -12, -8, -4],
  ![-10, -15, -20, -30, -24, -18, -12, -6],
  ![ -8, -12, -16, -24, -20, -15, -10, -5],
  ![ -6,  -9, -12, -18, -15, -12,  -8, -4],
  ![ -4,  -6,  -8, -12, -10,  -8,  -6, -3],
  ![ -2,  -3,  -4,  -6,  -5,  -4,  -3, -2]]

/-- The displayed integral matrix is a right inverse. -/
theorem e8GramMatrix_mul_inverse :
    e8GramMatrix * e8GramMatrixInverse = 1 := by
  rw [e8GramMatrix_eq]
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [e8GramMatrixInverse, Matrix.mul_apply, Fin.sum_univ_succ]

/-- The negative `E₈` Gram determinant is a unit. -/
theorem e8GramMatrix_isUnit_det : IsUnit e8GramMatrix.det :=
  Matrix.isUnit_det_of_right_inverse e8GramMatrix_mul_inverse

/-- The negative `E₈` lattice is unimodular. -/
theorem e8Lattice_isUnimodular : IsUnimodular e8Lattice := by
  rw [isUnimodular_iff_isUnit_determinant e8Lattice (Pi.basisFun ℤ (Fin 8))]
  simpa [determinant, e8Lattice_gramMatrix] using e8GramMatrix_isUnit_det

/-- The negative `E₈` lattice is even. -/
theorem e8Lattice_isEven : IsEven e8Lattice := by
  apply isEven_of_basis e8Lattice (Pi.basisFun ℤ (Fin 8))
  intro i
  rw [Ideal.mem_span_singleton]
  refine ⟨-1, ?_⟩
  change Matrix.toBilin' e8GramMatrix
    ((Pi.basisFun ℤ (Fin 8)) i) ((Pi.basisFun ℤ (Fin 8)) i) = 2 * -1
  simp only [Pi.basisFun_apply, Matrix.toBilin'_single]
  rw [e8GramMatrix_eq]
  fin_cases i <;> norm_num

/-- The Gram matrix of the integral hyperbolic plane. -/
def hyperbolicPlaneGramMatrix : Matrix (Fin 2) (Fin 2) ℤ := !![0, 1; 1, 0]

theorem hyperbolicPlaneGramMatrix_isSymm : hyperbolicPlaneGramMatrix.IsSymm := by
  ext i j
  fin_cases i <;> fin_cases j <;> norm_num [hyperbolicPlaneGramMatrix]

/-- The integral hyperbolic plane `U`. -/
def hyperbolicPlane : IntegralLatticeCat ℤ := by
  refine ⟨BilinModuleCat.ofBilinMap
    (Matrix.toBilin' hyperbolicPlaneGramMatrix), ?_, ?_⟩
  · change Module.Projective ℤ (Fin 2 → ℤ)
    infer_instance
  · intro x y
    exact (Matrix.isSymm_toBilin'_iff_isSymm.mpr
      hyperbolicPlaneGramMatrix_isSymm).eq x y

/-- The hyperbolic plane as a finite projective lattice. -/
def hyperbolicPlaneFiniteLattice : FiniteProjectiveLatticeCat ℤ ℤ := by
  refine ⟨hyperbolicPlane, ?_⟩
  change Module.Finite ℤ (Fin 2 → ℤ)
  infer_instance

@[simp]
theorem hyperbolicPlane_pairing (x y : hyperbolicPlane.obj.carrier) :
    hyperbolicPlane.obj.pairing x y =
      Matrix.toBilin' hyperbolicPlaneGramMatrix x y :=
  rfl

/-- The standard basis has the hyperbolic Gram matrix. -/
theorem hyperbolicPlane_gramMatrix :
    gramMatrix hyperbolicPlane (Pi.basisFun ℤ (Fin 2)) =
      hyperbolicPlaneGramMatrix := by
  exact LinearMap.BilinForm.toMatrix'_toBilin' hyperbolicPlaneGramMatrix

/-- The integral hyperbolic plane is unimodular. -/
theorem hyperbolicPlane_isUnimodular : IsUnimodular hyperbolicPlane := by
  rw [isUnimodular_iff_isUnit_determinant hyperbolicPlane
    (Pi.basisFun ℤ (Fin 2))]
  rw [determinant, hyperbolicPlane_gramMatrix, hyperbolicPlaneGramMatrix,
    Matrix.det_fin_two]
  norm_num

/-- The integral hyperbolic plane is even. -/
theorem hyperbolicPlane_isEven : IsEven hyperbolicPlane := by
  apply isEven_of_basis hyperbolicPlane (Pi.basisFun ℤ (Fin 2))
  intro i
  rw [Ideal.mem_span_singleton]
  refine ⟨0, ?_⟩
  change Matrix.toBilin' hyperbolicPlaneGramMatrix
    ((Pi.basisFun ℤ (Fin 2)) i) ((Pi.basisFun ℤ (Fin 2)) i) = 2 * 0
  simp only [Pi.basisFun_apply, Matrix.toBilin'_single]
  fin_cases i <;> norm_num [hyperbolicPlaneGramMatrix]

/-- A real basis change diagonalizes the hyperbolic plane. -/
def hyperbolicRealChange : Matrix (Fin 2) (Fin 2) ℝ := !![1, 1; 1, -1]

noncomputable def hyperbolicRealChangeInverse : Matrix (Fin 2) (Fin 2) ℝ :=
  !![(1 : ℝ) / 2, (1 : ℝ) / 2; (1 : ℝ) / 2, -(1 : ℝ) / 2]

theorem hyperbolicRealChange_leftInverse :
    hyperbolicRealChangeInverse * hyperbolicRealChange = 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [hyperbolicRealChange, hyperbolicRealChangeInverse,
      Matrix.mul_apply, Fin.sum_univ_succ]

theorem hyperbolicRealChange_rightInverse :
    hyperbolicRealChange * hyperbolicRealChangeInverse = 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [hyperbolicRealChange, hyperbolicRealChangeInverse,
      Matrix.mul_apply, Fin.sum_univ_succ]

noncomputable def hyperbolicRealDiagonalEquiv :
    (Fin 2 → ℝ) ≃ₗ[ℝ] (Fin 2 → ℝ) :=
  Matrix.toLin'OfInv hyperbolicRealChange_leftInverse
    hyperbolicRealChange_rightInverse

noncomputable def hyperbolicRealWeights : Fin 2 → ℝ :=
  ![(1 : ℝ) / 2, -(1 : ℝ) / 2]

/-- The real hyperbolic form has one positive and one negative square. -/
noncomputable def hyperbolicRealDiagonalIsometry :
    (matrixQuadraticForm ℝ
      (hyperbolicPlaneGramMatrix.map (Int.castRingHom ℝ))).IsometryEquiv
      (QuadraticMap.weightedSumSquares ℝ hyperbolicRealWeights) where
  toLinearEquiv := hyperbolicRealDiagonalEquiv
  map_app' x := by
    change QuadraticMap.weightedSumSquares ℝ hyperbolicRealWeights
      (hyperbolicRealDiagonalEquiv x) =
      Matrix.toBilin' (hyperbolicPlaneGramMatrix.map (Int.castRingHom ℝ)) x x
    simp [QuadraticMap.weightedSumSquares_apply, hyperbolicRealWeights,
      hyperbolicRealDiagonalEquiv, Matrix.toLin'OfInv, Matrix.toLin'_apply',
      hyperbolicRealChange, hyperbolicPlaneGramMatrix,
      Matrix.toBilin'_apply, Fin.sum_univ_succ]
    simp [Matrix.vecHead, Matrix.vecTail]
    ring

theorem hyperbolicPlane_matrixSignature :
    matrixSignature ℝ
      (hyperbolicPlaneGramMatrix.map (Int.castRingHom ℝ)) = (1, 1, 0) := by
  rw [matrixSignature_eq_of_equivalent_weighted ℝ _ hyperbolicRealWeights
    ⟨hyperbolicRealDiagonalIsometry⟩]
  have hp : {i | 0 < hyperbolicRealWeights i} = {0} := by
    ext i
    fin_cases i <;> norm_num [hyperbolicRealWeights]
  have hn : {i | hyperbolicRealWeights i < 0} = {1} := by
    ext i
    fin_cases i <;> norm_num [hyperbolicRealWeights]
  have hz : {i | hyperbolicRealWeights i = 0} = ∅ := by
    ext i
    fin_cases i <;> norm_num [hyperbolicRealWeights]
  rw [hp, hn, hz]
  norm_num

/-- The integral hyperbolic plane has signature `(1,1,0)`. -/
theorem hyperbolicPlane_integralSignature :
    integralSignature hyperbolicPlaneFiniteLattice = (1, 1, 0) := by
  rw [integralSignature_eq_matrixSignature hyperbolicPlaneFiniteLattice
    (Pi.basisFun ℤ (Fin 2))]
  rw [show gramMatrix hyperbolicPlaneFiniteLattice.obj
    (Pi.basisFun ℤ (Fin 2)) = hyperbolicPlaneGramMatrix from
      hyperbolicPlane_gramMatrix]
  exact hyperbolicPlane_matrixSignature

theorem hyperbolicRealGram_factorization :
    hyperbolicPlaneGramMatrix.map (Int.castRingHom ℝ) =
      hyperbolicRealChange.transpose * Matrix.diagonal hyperbolicRealWeights *
        hyperbolicRealChange := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [hyperbolicPlaneGramMatrix, hyperbolicRealChange,
      hyperbolicRealWeights, Matrix.mul_apply, Matrix.diagonal,
      Fin.sum_univ_succ]

/-- The real root-coordinate map for negative `E₈`. -/
noncomputable def e8RealRootChange : Matrix (Fin 8) (Fin 8) ℝ := ![
  ![ (1 : ℝ) / 2, 1, -1,  0,  0,  0,  0, 0],
  ![-(1 : ℝ) / 2, 1,  1, -1,  0,  0,  0, 0],
  ![-(1 : ℝ) / 2, 0,  0,  1, -1,  0,  0, 0],
  ![-(1 : ℝ) / 2, 0,  0,  0,  1, -1,  0, 0],
  ![-(1 : ℝ) / 2, 0,  0,  0,  0,  1, -1, 0],
  ![-(1 : ℝ) / 2, 0,  0,  0,  0,  0,  1, -1],
  ![-(1 : ℝ) / 2, 0,  0,  0,  0,  0,  0, 1],
  ![ (1 : ℝ) / 2, 0,  0,  0,  0,  0,  0, 0]]

/-- The inverse root-coordinate map. -/
noncomputable def e8RealRootChangeInverse : Matrix (Fin 8) (Fin 8) ℝ := ![
  ![0, 0, 0, 0, 0, 0, 0, 2],
  ![(1 : ℝ) / 2, (1 : ℝ) / 2, (1 : ℝ) / 2, (1 : ℝ) / 2,
    (1 : ℝ) / 2, (1 : ℝ) / 2, (1 : ℝ) / 2, (5 : ℝ) / 2],
  ![-(1 : ℝ) / 2, (1 : ℝ) / 2, (1 : ℝ) / 2, (1 : ℝ) / 2,
    (1 : ℝ) / 2, (1 : ℝ) / 2, (1 : ℝ) / 2, (7 : ℝ) / 2],
  ![0, 0, 1, 1, 1, 1, 1, 5],
  ![0, 0, 0, 1, 1, 1, 1, 4],
  ![0, 0, 0, 0, 1, 1, 1, 3],
  ![0, 0, 0, 0, 0, 1, 1, 2],
  ![0, 0, 0, 0, 0, 0, 1, 1]]

theorem e8RealRootChange_leftInverse :
    e8RealRootChangeInverse * e8RealRootChange = 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [e8RealRootChange, e8RealRootChangeInverse,
      Matrix.mul_apply, Fin.sum_univ_succ]

theorem e8RealRootChange_rightInverse :
    e8RealRootChange * e8RealRootChangeInverse = 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [e8RealRootChange, e8RealRootChangeInverse,
      Matrix.mul_apply, Fin.sum_univ_succ]

noncomputable def e8RealRootEquiv :
    (Fin 8 → ℝ) ≃ₗ[ℝ] (Fin 8 → ℝ) :=
  Matrix.toLin'OfInv e8RealRootChange_leftInverse
    e8RealRootChange_rightInverse

def e8RealWeights : Fin 8 → ℝ := fun _ ↦ -1

theorem e8RealGram_factorization :
    e8GramMatrix.map (Int.castRingHom ℝ) =
      -(e8RealRootChange.transpose * e8RealRootChange) := by
  rw [e8GramMatrix_eq]
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [e8RealRootChange, Matrix.mul_apply, Fin.sum_univ_succ]

theorem e8RealGram_diagonal_factorization :
    e8GramMatrix.map (Int.castRingHom ℝ) =
      e8RealRootChange.transpose * Matrix.diagonal e8RealWeights *
        e8RealRootChange := by
  rw [e8RealGram_factorization]
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [e8RealRootChange, e8RealWeights, Matrix.mul_apply,
      Matrix.diagonal, Fin.sum_univ_succ]

theorem weightedNegativeSquares_eq_toBilin_transpose_mul
    {I : Type*} [Fintype I] [DecidableEq I]
    (B : Matrix I I ℝ) (x : I → ℝ) :
    QuadraticMap.weightedSumSquares ℝ (fun (_ : I) ↦ (-1 : ℝ)) (B.mulVec x) =
      Matrix.toBilin' (-(B.transpose * B)) x x := by
  rw [QuadraticMap.weightedSumSquares_apply, Matrix.toBilin'_apply']
  simp only [smul_eq_mul, neg_one_mul, Finset.sum_neg_distrib,
    Matrix.neg_mulVec, dotProduct_neg]
  congr 1
  rw [← Matrix.mulVec_mulVec]
  change dotProduct (B.mulVec x) (B.mulVec x) = _
  exact (Matrix.dotProduct_transpose_mulVec B x (B.mulVec x)).symm

theorem weightedSquares_eq_toBilin_transpose_diagonal_mul
    {I : Type*} [Fintype I] [DecidableEq I]
    (B : Matrix I I ℝ) (w : I → ℝ) (x : I → ℝ) :
    QuadraticMap.weightedSumSquares ℝ w (B.mulVec x) =
      Matrix.toBilin' (B.transpose * Matrix.diagonal w * B) x x := by
  rw [Matrix.toBilin'_apply']
  simp only [← Matrix.mulVec_mulVec]
  rw [Matrix.dotProduct_transpose_mulVec]
  rw [QuadraticMap.weightedSumSquares_apply]
  simp only [smul_eq_mul, dotProduct, Matrix.mulVec_diagonal]
  apply Finset.sum_congr rfl
  intro i _
  ring

/-- Negative `E₈` is a sum of eight negative real squares. -/
noncomputable def e8RealDiagonalIsometry :
    (matrixQuadraticForm ℝ
      (e8GramMatrix.map (Int.castRingHom ℝ))).IsometryEquiv
      (QuadraticMap.weightedSumSquares ℝ e8RealWeights) where
  toLinearEquiv := e8RealRootEquiv
  map_app' x := by
    change QuadraticMap.weightedSumSquares ℝ e8RealWeights
      (e8RealRootEquiv x) =
      Matrix.toBilin' (e8GramMatrix.map (Int.castRingHom ℝ)) x x
    rw [e8RealGram_factorization]
    exact weightedNegativeSquares_eq_toBilin_transpose_mul
      e8RealRootChange x

theorem e8Lattice_matrixSignature :
    matrixSignature ℝ (e8GramMatrix.map (Int.castRingHom ℝ)) = (0, 8, 0) := by
  rw [matrixSignature_eq_of_equivalent_weighted ℝ _ e8RealWeights
    ⟨e8RealDiagonalIsometry⟩]
  have hp : {i | 0 < e8RealWeights i} = ∅ := by
    ext i
    simp [e8RealWeights]
  have hn : {i | e8RealWeights i < 0} = Set.univ := by
    ext i
    simp [e8RealWeights]
  have hz : {i | e8RealWeights i = 0} = ∅ := by
    ext i
    simp [e8RealWeights]
  rw [hp, hn, hz]
  norm_num

/-- The negative `E₈` lattice has signature `(0,8,0)`. -/
theorem e8Lattice_integralSignature :
    integralSignature e8FiniteLattice = (0, 8, 0) := by
  rw [integralSignature_eq_matrixSignature e8FiniteLattice
    (Pi.basisFun ℤ (Fin 8))]
  rw [show gramMatrix e8FiniteLattice.obj (Pi.basisFun ℤ (Fin 8)) =
    e8GramMatrix from e8Lattice_gramMatrix]
  exact e8Lattice_matrixSignature

/-- The `K3` lattice `3U ⊥ 2E₈`, with negative `E₈`. -/
noncomputable def k3Lattice : IntegralLatticeCat ℤ :=
  orthogonalSum (orthogonalPower hyperbolicPlane 3)
    (orthogonalPower e8Lattice 2)

/-- The `K3` lattice as a finite projective lattice. -/
noncomputable def k3FiniteLattice : FiniteProjectiveLatticeCat ℤ ℤ := by
  refine ⟨k3Lattice, ?_⟩
  change Module.Finite ℤ ((Fin 3 → Fin 2 → ℤ) × (Fin 2 → Fin 8 → ℤ))
  infer_instance

abbrev K3Index :=
  (Σ _ : Fin 3, Fin 2) ⊕ (Σ _ : Fin 2, Fin 8)

noncomputable def hyperbolicPowerBasis :
    Module.Basis (Σ _ : Fin 3, Fin 2) ℤ (Fin 3 → Fin 2 → ℤ) :=
  (Pi.basisFun ℤ (Σ _ : Fin 3, Fin 2)).map
    (LinearEquiv.piCurry ℤ (fun _ : Fin 3 ↦ fun _ : Fin 2 ↦ ℤ))

noncomputable def e8PowerBasis :
    Module.Basis (Σ _ : Fin 2, Fin 8) ℤ (Fin 2 → Fin 8 → ℤ) :=
  (Pi.basisFun ℤ (Σ _ : Fin 2, Fin 8)).map
    (LinearEquiv.piCurry ℤ (fun _ : Fin 2 ↦ fun _ : Fin 8 ↦ ℤ))

@[simp]
theorem hyperbolicPowerBasis_apply (i : Σ _ : Fin 3, Fin 2) :
    hyperbolicPowerBasis i = Pi.single i.1 (Pi.single i.2 1) := by
  rcases i with ⟨i, a⟩
  ext j k
  by_cases h : j = i
  · subst j
    simp only [hyperbolicPowerBasis, Module.Basis.map_apply, Pi.basisFun_apply,
      LinearEquiv.piCurry_apply]
    change Pi.single (⟨i, a⟩ : Σ _ : Fin 3, Fin 2) 1
      (⟨i, k⟩ : Σ _ : Fin 3, Fin 2) = _
    simp [Pi.single_apply]
  · simp only [hyperbolicPowerBasis, Module.Basis.map_apply, Pi.basisFun_apply,
      LinearEquiv.piCurry_apply]
    change Pi.single (⟨i, a⟩ : Σ _ : Fin 3, Fin 2) 1
      (⟨j, k⟩ : Σ _ : Fin 3, Fin 2) = _
    simp [h]

@[simp]
theorem e8PowerBasis_apply (i : Σ _ : Fin 2, Fin 8) :
    e8PowerBasis i = Pi.single i.1 (Pi.single i.2 1) := by
  rcases i with ⟨i, a⟩
  ext j k
  by_cases h : j = i
  · subst j
    simp only [e8PowerBasis, Module.Basis.map_apply, Pi.basisFun_apply,
      LinearEquiv.piCurry_apply]
    change Pi.single (⟨i, a⟩ : Σ _ : Fin 2, Fin 8) 1
      (⟨i, k⟩ : Σ _ : Fin 2, Fin 8) = _
    simp [Pi.single_apply]
  · simp only [e8PowerBasis, Module.Basis.map_apply, Pi.basisFun_apply,
      LinearEquiv.piCurry_apply]
    change Pi.single (⟨i, a⟩ : Σ _ : Fin 2, Fin 8) 1
      (⟨j, k⟩ : Σ _ : Fin 2, Fin 8) = _
    simp [h]

noncomputable def k3Basis :
    Module.Basis K3Index ℤ k3Lattice.obj.carrier := by
  change Module.Basis K3Index ℤ
    ((Fin 3 → Fin 2 → ℤ) × (Fin 2 → Fin 8 → ℤ))
  exact hyperbolicPowerBasis.prod e8PowerBasis

noncomputable def k3GramMatrix : Matrix K3Index K3Index ℤ
  | Sum.inl ⟨i, a⟩, Sum.inl ⟨j, b⟩ =>
      if i = j then hyperbolicPlaneGramMatrix a b else 0
  | Sum.inr ⟨i, a⟩, Sum.inr ⟨j, b⟩ =>
      if i = j then e8GramMatrix a b else 0
  | _, _ => 0

noncomputable def k3RealChange : Matrix K3Index K3Index ℝ
  | Sum.inl ⟨i, a⟩, Sum.inl ⟨j, b⟩ =>
      if i = j then hyperbolicRealChange a b else 0
  | Sum.inr ⟨i, a⟩, Sum.inr ⟨j, b⟩ =>
      if i = j then e8RealRootChange a b else 0
  | _, _ => 0

noncomputable def k3RealChangeInverse : Matrix K3Index K3Index ℝ
  | Sum.inl ⟨i, a⟩, Sum.inl ⟨j, b⟩ =>
      if i = j then hyperbolicRealChangeInverse a b else 0
  | Sum.inr ⟨i, a⟩, Sum.inr ⟨j, b⟩ =>
      if i = j then e8RealRootChangeInverse a b else 0
  | _, _ => 0

noncomputable def k3RealWeights : K3Index → ℝ
  | Sum.inl ⟨_, a⟩ => hyperbolicRealWeights a
  | Sum.inr _ => -1

theorem k3Lattice_gramMatrix :
    gramMatrix k3Lattice k3Basis = k3GramMatrix := by
  ext i j
  rcases i with i | i <;> rcases j with j | j <;>
    rcases i with ⟨i, a⟩ <;> rcases j with ⟨j, b⟩
  · simp only [gramMatrix]
    rw [LinearMap.BilinForm.toMatrix_apply]
    change (orthogonalSum (orthogonalPower hyperbolicPlane 3)
      (orthogonalPower e8Lattice 2)).obj.pairing
        ((hyperbolicPowerBasis.prod e8PowerBasis) (Sum.inl ⟨i, a⟩))
        ((hyperbolicPowerBasis.prod e8PowerBasis) (Sum.inl ⟨j, b⟩)) = _
    rw [orthogonalSum_pairing]
    simp only [Module.Basis.prod_apply, LinearMap.coe_inl, LinearMap.coe_inr,
      Sum.elim_inl, Function.comp_apply, hyperbolicPowerBasis_apply,
      orthogonalPower_pairing, hyperbolicPlane_pairing, Pi.zero_apply,
      e8Lattice_pairing, map_zero,
      Finset.sum_const_zero, add_zero]
    fin_cases i <;> fin_cases j <;>
      simp [k3GramMatrix, Fin.sum_univ_succ, Pi.single_apply,
        Matrix.toBilin'_single]
  · simp only [gramMatrix]
    rw [LinearMap.BilinForm.toMatrix_apply]
    change (orthogonalSum (orthogonalPower hyperbolicPlane 3)
      (orthogonalPower e8Lattice 2)).obj.pairing
        ((hyperbolicPowerBasis.prod e8PowerBasis) (Sum.inl ⟨i, a⟩))
        ((hyperbolicPowerBasis.prod e8PowerBasis) (Sum.inr ⟨j, b⟩)) = _
    rw [orthogonalSum_pairing]
    simp [k3GramMatrix]
  · simp only [gramMatrix]
    rw [LinearMap.BilinForm.toMatrix_apply]
    change (orthogonalSum (orthogonalPower hyperbolicPlane 3)
      (orthogonalPower e8Lattice 2)).obj.pairing
        ((hyperbolicPowerBasis.prod e8PowerBasis) (Sum.inr ⟨i, a⟩))
        ((hyperbolicPowerBasis.prod e8PowerBasis) (Sum.inl ⟨j, b⟩)) = _
    rw [orthogonalSum_pairing]
    simp [k3GramMatrix]
  · simp only [gramMatrix]
    rw [LinearMap.BilinForm.toMatrix_apply]
    change (orthogonalSum (orthogonalPower hyperbolicPlane 3)
      (orthogonalPower e8Lattice 2)).obj.pairing
        ((hyperbolicPowerBasis.prod e8PowerBasis) (Sum.inr ⟨i, a⟩))
        ((hyperbolicPowerBasis.prod e8PowerBasis) (Sum.inr ⟨j, b⟩)) = _
    rw [orthogonalSum_pairing]
    simp only [Module.Basis.prod_apply, LinearMap.coe_inl, LinearMap.coe_inr,
      Sum.elim_inr, Function.comp_apply, e8PowerBasis_apply,
      orthogonalPower_pairing, Pi.zero_apply, hyperbolicPlane_pairing,
      map_zero, Finset.sum_const_zero,
      e8Lattice_pairing, Fin.sum_univ_two, Fin.isValue, zero_add]
    fin_cases i <;> fin_cases j <;>
      simp [k3GramMatrix, Matrix.toBilin'_single]

theorem k3RealGram_factorization :
    k3GramMatrix.map (Int.castRingHom ℝ) =
      k3RealChange.transpose * Matrix.diagonal k3RealWeights *
        k3RealChange := by
  classical
  ext i j
  rcases i with ⟨i, a⟩ | ⟨i, a⟩ <;>
    rcases j with ⟨j, b⟩ | ⟨j, b⟩
  all_goals
    simp [Matrix.mul_apply, Fintype.sum_sum_type, Fintype.sum_sigma,
      k3GramMatrix, k3RealChange, k3RealWeights, Matrix.diagonal]
  · by_cases h : i = j
    · subst j
      simpa [Matrix.mul_apply] using
        congrFun (congrFun hyperbolicRealGram_factorization a) b
    · simp [h, ne_comm]
  · by_cases h : i = j
    · subst j
      simpa [Matrix.mul_apply] using
        congrFun (congrFun e8RealGram_factorization a) b
    · simp [h, ne_comm]

theorem k3RealChange_leftInverse :
    k3RealChangeInverse * k3RealChange = 1 := by
  classical
  ext i j
  rcases i with ⟨i, a⟩ | ⟨i, a⟩ <;>
    rcases j with ⟨j, b⟩ | ⟨j, b⟩
  all_goals
    simp [Matrix.mul_apply, Fintype.sum_sum_type, Fintype.sum_sigma,
      k3RealChange, k3RealChangeInverse, Matrix.one_apply]
  · by_cases h : i = j
    · subst j
      simpa [Matrix.mul_apply, Matrix.one_apply] using
        congrFun (congrFun hyperbolicRealChange_leftInverse a) b
    · simp [h]
  · by_cases h : i = j
    · subst j
      simpa [Matrix.mul_apply, Matrix.one_apply] using
        congrFun (congrFun e8RealRootChange_leftInverse a) b
    · simp [h]

theorem k3RealChange_rightInverse :
    k3RealChange * k3RealChangeInverse = 1 := by
  classical
  ext i j
  rcases i with ⟨i, a⟩ | ⟨i, a⟩ <;>
    rcases j with ⟨j, b⟩ | ⟨j, b⟩
  all_goals
    simp [Matrix.mul_apply, Fintype.sum_sum_type, Fintype.sum_sigma,
      k3RealChange, k3RealChangeInverse, Matrix.one_apply]
  · by_cases h : i = j
    · subst j
      simpa [Matrix.mul_apply, Matrix.one_apply] using
        congrFun (congrFun hyperbolicRealChange_rightInverse a) b
    · simp [h]
  · by_cases h : i = j
    · subst j
      simpa [Matrix.mul_apply, Matrix.one_apply] using
        congrFun (congrFun e8RealRootChange_rightInverse a) b
    · simp [h]

noncomputable def k3RealEquiv :
    (K3Index → ℝ) ≃ₗ[ℝ] (K3Index → ℝ) :=
  Matrix.toLin'OfInv k3RealChange_leftInverse k3RealChange_rightInverse

/-- The `K3` Gram matrix is a sum of three positive and nineteen negative squares. -/
noncomputable def k3RealDiagonalIsometry :
    (matrixQuadraticForm ℝ
      (k3GramMatrix.map (Int.castRingHom ℝ))).IsometryEquiv
      (QuadraticMap.weightedSumSquares ℝ k3RealWeights) where
  toLinearEquiv := k3RealEquiv
  map_app' x := by
    change QuadraticMap.weightedSumSquares ℝ k3RealWeights
      (k3RealEquiv x) =
      Matrix.toBilin' (k3GramMatrix.map (Int.castRingHom ℝ)) x x
    rw [k3RealGram_factorization]
    exact weightedSquares_eq_toBilin_transpose_diagonal_mul
      k3RealChange k3RealWeights x

theorem k3Lattice_matrixSignature :
    matrixSignature ℝ (k3GramMatrix.map (Int.castRingHom ℝ)) =
      (3, 19, 0) := by
  rw [matrixSignature_eq_of_equivalent_weighted ℝ _ k3RealWeights
    ⟨k3RealDiagonalIsometry⟩]
  let positive : Fin 3 → K3Index :=
    fun i ↦ Sum.inl ⟨i, 0⟩
  let negativeU : Fin 3 → K3Index :=
    fun i ↦ Sum.inl ⟨i, 1⟩
  let negativeE8 : (Σ _ : Fin 2, Fin 8) → K3Index := Sum.inr
  have positive_injective : Function.Injective positive := by
    intro i j h
    simpa [positive] using h
  have negativeU_injective : Function.Injective negativeU := by
    intro i j h
    simpa [negativeU] using h
  have negativeE8_injective : Function.Injective negativeE8 := Sum.inr_injective
  have hp : {i | 0 < k3RealWeights i} = Set.range positive := by
    ext x
    rcases x with ⟨i, a⟩ | ⟨i, a⟩
    · fin_cases a <;> simp [k3RealWeights, hyperbolicRealWeights, positive]
    · simp [k3RealWeights, positive]
  have hn : {i | k3RealWeights i < 0} =
      Set.range negativeU ∪ Set.range negativeE8 := by
    ext x
    rcases x with ⟨i, a⟩ | ⟨i, a⟩
    · fin_cases a
      · norm_num [k3RealWeights, hyperbolicRealWeights, negativeU, negativeE8]
        constructor <;> intro x h <;> cases h
      · norm_num [k3RealWeights, hyperbolicRealWeights, negativeU, negativeE8]
    · simp [k3RealWeights, negativeU, negativeE8]
  have hz : {i | k3RealWeights i = 0} = ∅ := by
    ext x
    rcases x with ⟨i, a⟩ | ⟨i, a⟩
    · fin_cases a <;> simp [k3RealWeights, hyperbolicRealWeights]
    · simp [k3RealWeights]
  have hd : Disjoint (Set.range negativeU) (Set.range negativeE8) := by
    refine Set.disjoint_left.2 ?_
    intro x hx hy
    rcases hx with ⟨i, rfl⟩
    rcases hy with ⟨j, h⟩
    simp [negativeE8, negativeU] at h
  rw [hp, hn, hz, Set.ncard_union_eq hd,
    Set.ncard_range_of_injective positive_injective,
    Set.ncard_range_of_injective negativeU_injective,
    Set.ncard_range_of_injective negativeE8_injective]
  norm_num

/-- The `K3` lattice has signature `(3,19,0)`. -/
theorem k3Lattice_integralSignature :
    integralSignature k3FiniteLattice = (3, 19, 0) := by
  rw [integralSignature_eq_matrixSignature k3FiniteLattice k3Basis]
  rw [show gramMatrix k3FiniteLattice.obj k3Basis = k3GramMatrix from
    k3Lattice_gramMatrix]
  exact k3Lattice_matrixSignature
/-- The `K3` lattice is unimodular. -/
theorem k3Lattice_isUnimodular : IsUnimodular k3Lattice :=
  isUnimodular_orthogonalSum _ _
    (isUnimodular_orthogonalPower hyperbolicPlane 3 hyperbolicPlane_isUnimodular)
    (isUnimodular_orthogonalPower e8Lattice 2 e8Lattice_isUnimodular)

/-- The `K3` lattice is even. -/
theorem k3Lattice_isEven : IsEven k3Lattice :=
  isEven_orthogonalSum _ _
    (isEven_orthogonalPower hyperbolicPlane 3 hyperbolicPlane_isEven)
    (isEven_orthogonalPower e8Lattice 2 e8Lattice_isEven)

end LeanCategories.Lattices.Valued
