/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.Topology.Algebra.FilterBasis
public import Mathlib.Topology.Algebra.OpenSubgroup

/-!
# Topologies generated by descending subgroups

Atiyah–Macdonald (1969), printed pp. 102–103, FC04-C10-U006. A descending
sequence supplies a zero-neighborhood basis. Its subgroups are both open and closed.
The construction uses Mathlib's additive group filter bases and works without a
Hausdorff assumption. The source specializes to families with initial term the whole group.
-/

@[expose] public section

open Topology Filter
open scoped Pointwise

namespace AddSubgroup

variable {G : Type*} [AddCommGroup G]

/-- A descending subgroup family supplies an additive group filter basis. -/
@[instance_reducible]
def filterBasisOfAntitone (F : ℕ → AddSubgroup G) (hF : Antitone F) :
    AddGroupFilterBasis G :=
  addGroupFilterBasisOfComm (Set.range fun n => (F n : Set G))
    ⟨_, 0, rfl⟩
    (by
      rintro _ _ ⟨i, rfl⟩ ⟨j, rfl⟩
      exact ⟨_, ⟨max i j, rfl⟩, fun x hx =>
        ⟨hF (le_max_left i j) hx, hF (le_max_right i j) hx⟩⟩)
    (by rintro _ ⟨i, rfl⟩; exact (F i).zero_mem)
    (by
      rintro _ ⟨i, rfl⟩
      refine ⟨_, ⟨i, rfl⟩, ?_⟩
      rintro _ ⟨x, hx, y, hy, rfl⟩
      exact (F i).add_mem hx hy)
    (by
      rintro _ ⟨i, rfl⟩
      exact ⟨_, ⟨i, rfl⟩, fun x hx => (F i).neg_mem hx⟩)

/-- The topology generated by a descending subgroup family at zero. -/
@[instance_reducible]
def topologyOfAntitone (F : ℕ → AddSubgroup G) (hF : Antitone F) : TopologicalSpace G :=
  (filterBasisOfAntitone F hF).topology

/-- A set is a zero-neighborhood exactly when it contains a member of the family. -/
theorem hasBasis_nhds_zero_topologyOfAntitone (F : ℕ → AddSubgroup G) (hF : Antitone F) :
    HasBasis (@nhds G (topologyOfAntitone F hF) 0) (fun _ : ℕ => True)
      (fun n => (F n : Set G)) := by
  refine ⟨fun s => ?_⟩
  rw [(filterBasisOfAntitone F hF).nhds_zero_hasBasis.mem_iff]
  constructor
  · rintro ⟨U, ⟨n, rfl⟩, hU⟩
    exact ⟨n, trivial, hU⟩
  · rintro ⟨n, _, hU⟩
    exact ⟨_, ⟨n, rfl⟩, hU⟩

/-- Every subgroup in the defining family is open. -/
theorem isOpen_topologyOfAntitone (F : ℕ → AddSubgroup G) (hF : Antitone F) (n : ℕ) :
    @IsOpen G (topologyOfAntitone F hF) (F n : Set G) := by
  let : TopologicalSpace G := topologyOfAntitone F hF
  exact (F n).isOpen_of_mem_nhds (g := 0)
    ((hasBasis_nhds_zero_topologyOfAntitone F hF).mem_of_mem trivial)

/-- Every subgroup in the defining family is closed, without separation assumptions. -/
theorem isClosed_topologyOfAntitone (F : ℕ → AddSubgroup G) (hF : Antitone F) (n : ℕ) :
    @IsClosed G (topologyOfAntitone F hF) (F n : Set G) := by
  let : TopologicalSpace G := topologyOfAntitone F hF
  exact (F n).isClosed_of_isOpen (isOpen_topologyOfAntitone F hF n)

/-- Two descending subgroup families define the same topology exactly when they are cofinal. -/
theorem topologyOfAntitone_eq_iff (F H : ℕ → AddSubgroup G)
    (hF : Antitone F) (hH : Antitone H) :
    topologyOfAntitone F hF = topologyOfAntitone H hH ↔
      (∀ n, ∃ m, F m ≤ H n) ∧ (∀ n, ∃ m, H m ≤ F n) := by
  have bF := hasBasis_nhds_zero_topologyOfAntitone F hF
  have bH := hasBasis_nhds_zero_topologyOfAntitone H hH
  constructor
  · intro he
    constructor
    · intro n
      have hn := bH.mem_of_mem (i := n) trivial
      rw [← he] at hn
      obtain ⟨m, _, hm⟩ := bF.mem_iff.mp hn
      exact ⟨m, hm⟩
    · intro n
      have hn := bF.mem_of_mem (i := n) trivial
      rw [he] at hn
      obtain ⟨m, _, hm⟩ := bH.mem_iff.mp hn
      exact ⟨m, hm⟩
  · rintro ⟨hFH, hHF⟩
    apply IsTopologicalAddGroup.ext
      (filterBasisOfAntitone F hF).isTopologicalAddGroup
      (filterBasisOfAntitone H hH).isTopologicalAddGroup
    apply Filter.ext
    intro s
    rw [bF.mem_iff, bH.mem_iff]
    constructor
    · rintro ⟨n, _, hn⟩
      obtain ⟨m, hm⟩ := hHF n
      exact ⟨m, trivial, fun x hx => hn (hm hx)⟩
    · rintro ⟨n, _, hn⟩
      obtain ⟨m, hm⟩ := hFH n
      exact ⟨m, trivial, fun x hx => hn (hm hx)⟩

variable {H : Type*} [AddCommGroup H]

/-- Continuity of a homomorphism is detected by the two subgroup neighborhood bases. -/
theorem continuous_topologyOfAntitone_iff (F : ℕ → AddSubgroup G) (E : ℕ → AddSubgroup H)
    (hF : Antitone F) (hE : Antitone E) (f : G →+ H) :
    @Continuous G H (topologyOfAntitone F hF) (topologyOfAntitone E hE) f ↔
      ∀ n, ∃ m, F m ≤ (E n).comap f := by
  let : TopologicalSpace G := topologyOfAntitone F hF
  let : TopologicalSpace H := topologyOfAntitone E hE
  have bF := hasBasis_nhds_zero_topologyOfAntitone F hF
  have bE := hasBasis_nhds_zero_topologyOfAntitone E hE
  constructor
  · intro h
    have ht := h.continuousAt (x := 0)
    rw [ContinuousAt, map_zero] at ht
    intro n
    obtain ⟨m, _, hm⟩ := (bF.tendsto_iff bE).mp ht n trivial
    exact ⟨m, hm⟩
  · intro h
    apply continuous_of_tendsto_nhds_zero f
    exact (bF.tendsto_iff bE).mpr fun n _ => by
      obtain ⟨m, hm⟩ := h n
      exact ⟨m, trivial, hm⟩

end AddSubgroup
