/-
Copyright (c) 2026 Dzack Garza. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.RingTheory.MvPolynomial.Ideal
public import Mathlib.Algebra.MvPolynomial.PDeriv
public import Mathlib.LinearAlgebra.Dimension.Constructions
public import Mathlib.LinearAlgebra.StdBasis

/-!
# The ideal of the origin in affine space

Atiyah–Macdonald, *Introduction to Commutative Algebra* (1969), printed pp. 4–5,
FC04-C01-U032: the polynomials with zero constant term form a maximal ideal over a
field, and this ideal requires at least as many generators as there are variables.

The ideal, constant-coefficient map and partial derivatives are Mathlib's. The
generator bound follows by evaluating partial derivatives at the origin: a family
generating the ideal gives a spanning family of the coordinate vector space.
-/

@[expose] public section

namespace MvPolynomial

variable {σ R : Type*} [CommRing R]

/-- The ideal generated by the variables consists exactly of zero-constant-term polynomials. -/
theorem mem_idealOfVars_iff_constantCoeff_eq_zero (p : MvPolynomial σ R) :
    p ∈ idealOfVars σ R ↔ constantCoeff p = 0 := by
  rw [← pow_one (idealOfVars σ R), mem_pow_idealOfVars_iff']
  change (∀ d : σ →₀ ℕ, Finsupp.degree d < 1 → coeff d p = 0) ↔ coeff 0 p = 0
  simp only [Nat.lt_one_iff, Finsupp.degree_eq_zero_iff, forall_eq]

/-- The ideal of the origin is the kernel of evaluation at the origin. -/
theorem idealOfVars_eq_ker_constantCoeff :
    idealOfVars σ R = RingHom.ker (constantCoeff : MvPolynomial σ R →+* R) := by
  ext p
  exact mem_idealOfVars_iff_constantCoeff_eq_zero p

/-- Over a field, the ideal generated by all variables is maximal. -/
theorem idealOfVars_isMaximal {K : Type*} [Field K] :
    (idealOfVars σ K).IsMaximal := by
  rw [idealOfVars_eq_ker_constantCoeff]
  exact RingHom.ker_isMaximal_of_surjective _ fun a => ⟨C a, constantCoeff_C σ a⟩

/-- Every finite generating family of the ideal of the origin has at least as many
members as there are variables. This includes the source's sharper generator-count
assertion, not only the nonprincipality consequence. -/
theorem card_le_card_of_span_eq_idealOfVars {K τ : Type*} [Field K]
    [Fintype σ] [Fintype τ] (g : τ → MvPolynomial σ K)
    (hg : Ideal.span (Set.range g) = idealOfVars σ K) :
    Fintype.card σ ≤ Fintype.card τ := by
  classical
  let D : MvPolynomial σ K → (σ → K) := fun p i => constantCoeff (pderiv i p)
  let T : Submodule K (σ → K) := Submodule.span K (Set.range (fun j => D (g j)))
  have hmem : ∀ p ∈ Ideal.span (Set.range g), D p ∈ T := by
    intro p hp
    induction hp using Submodule.span_induction with
    | mem p hp =>
      obtain ⟨j, rfl⟩ := hp
      exact Submodule.subset_span ⟨j, rfl⟩
    | zero =>
      have he : D 0 = 0 := by
        ext i
        simp [D]
      rw [he]
      exact T.zero_mem
    | add p q _ _ hp hq =>
      have he : D (p + q) = D p + D q := by
        ext i
        simp [D]
      rw [he]
      exact T.add_mem hp hq
    | smul a p hp hDp =>
      have hz : constantCoeff p = 0 :=
        (mem_idealOfVars_iff_constantCoeff_eq_zero p).mp (hg ▸ hp)
      have he : D (a • p) = constantCoeff a • D p := by
        ext i
        simp [D, smul_eq_mul, Derivation.leibniz, hz]
      rw [he]
      exact T.smul_mem _ hDp
  have hX (i : σ) : D (X i) = (Pi.basisFun K σ) i := by
    ext j
    simp [D, Pi.basisFun_apply, pderiv_X, Pi.single_apply, eq_comm]
  have htop : T = ⊤ := by
    apply top_unique
    rw [← (Pi.basisFun K σ).span_eq]
    apply Submodule.span_le.mpr
    rintro _ ⟨i, rfl⟩
    rw [← hX]
    apply hmem
    rw [hg]
    exact Ideal.subset_span ⟨i, rfl⟩
  have h := finrank_le_of_span_eq_top (R := K) htop
  simpa using h

/-- With at least two variables, the ideal of the origin is not principal. -/
theorem idealOfVars_not_isPrincipal {K : Type*} [Field K] [Finite σ] [Nontrivial σ] :
    ¬ (idealOfVars σ K).IsPrincipal := by
  let := Fintype.ofFinite σ
  intro h
  obtain ⟨p, hp⟩ := h.principal
  have hg : Ideal.span (Set.range (fun _ : Unit => p)) = idealOfVars σ K := by
    simpa using hp.symm
  have hcard := card_le_card_of_span_eq_idealOfVars (fun _ : Unit => p) hg
  have htwo : 1 < Fintype.card σ := Fintype.one_lt_card_iff_nontrivial.mpr inferInstance
  simp only [Fintype.card_unique] at hcard
  exact (not_le_of_gt htwo) hcard

end MvPolynomial
